Repository weaveworks/weave-gitops, pull requests merged in 2021-11, with the labels that each got.

#931 Add integration tests
  .github/workflows/test.yml
  .gitignore
  Makefile
  go.mod
  pkg/apputils/serverutils.go
  pkg/gitproviders/provider.go
  pkg/gitproviders/provider_org.go
  pkg/gitproviders/provider_user.go
  pkg/kube/kube_suite_test.go
  pkg/kube/kubehttp.go
  pkg/logger/api.go
  pkg/middleware/middleware.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/suite_test.go
  pkg/testutils/testutils.go
  pkg/utils/common.go
  test/integration/server/add_test.go
  test/integration/server/helpers/helpers.go
  test/integration/server/helpers/yaml/deployment.yaml
  test/integration/server/helpers/yaml/kustomization.yaml
  test/integration/server/suite_test.go
  tools/tools.go
Labels: enhancement

#994 FIx beta install to create the GitOps runtime file
  pkg/services/gitops/install.go
  pkg/services/gitops/install_test.go
Labels: bug

#996 Upd bug template to use label 'bug'; ask for flux logs
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: exclude from release notes

#999 Move `app <app-name> get commits` to `get commits <app-name>`
  cmd/gitops/app/cmd.go
  cmd/gitops/get/cmd.go
  cmd/gitops/get/commits/cmd.go
  test/acceptance/test/add_tests.go
Labels: enhancement

#998 Move `app status` to `get app`
  cmd/gitops/app/cmd.go
  cmd/gitops/app/status/cmd.go
  cmd/gitops/get/app/cmd.go
  cmd/gitops/main.go
  test/acceptance/test/add_tests.go
  test/acceptance/test/help_tests.go
Labels: enhancement

#1000 Remove pr- prefix from flags
  cmd/gitops/delete/clusters/cmd.go
  cmd/gitops/upgrade/cmd.go
Labels: bug

#1006 Replacing undescore with dashs on cluster names
  pkg/kube/kubehttp.go
  pkg/kube/kubehttp_test.go
Labels: bug

#975 Add new App Fetcher
  cmd/gitops/get/app/cmd.go
  pkg/apputils/utils.go
  pkg/models/application.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/suite_test.go
  pkg/services/app/add.go
  pkg/services/applicationv2/applicationv2fakes/fake_fetcher.go
  pkg/services/applicationv2/fetcher.go
  pkg/services/applicationv2/fetcher_test.go
  pkg/services/applicationv2/suite_test.go
Labels: exclude from release notes

#1008 Fix delete cluster request body always being empty
  pkg/adapters/http.go
Labels: bug

#1014 Move auto-generated CLI reference under "CLI Reference" menu item
  tools/update-docs.sh
Labels: documentation, enhancement

#1015 Fixes add-app in wego-server
  pkg/kube/kubehttp.go
  pkg/kube/kubehttp_test.go
Labels: bug

#1009 Add flag validation for WGE commands
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/add/clusters/cmd_test.go
  cmd/gitops/cmderrors/errors.go
  cmd/gitops/delete/clusters/cmd.go
  cmd/gitops/delete/clusters/cmd_test.go
  cmd/gitops/get/clusters/cmd.go
  cmd/gitops/get/clusters/cmd_test.go
  cmd/gitops/get/commits/cmd.go
  cmd/gitops/get/credentials/cmd.go
  cmd/gitops/get/credentials/cmd_test.go
  cmd/gitops/get/templates/cmd.go
  cmd/gitops/get/templates/cmd_test.go
  cmd/gitops/main.go
  cmd/gitops/root/cmd.go
  pkg/adapters/http.go
  pkg/adapters/http_test.go
Labels: enhancement

#1020 Updating to version 0.4.1
  README.md
  package-lock.json
  package.json
Labels: exclude from release notes

#992 Allow adding a public gitlab project
  .github/actions/run-acceptance-test/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yaml
  pkg/flux/flux.go
  pkg/flux/flux_test.go
  pkg/flux/fluxfakes/fake_flux.go
  pkg/services/app/add.go
  pkg/services/app/add_test.go
  pkg/services/auth/auth.go
  pkg/services/gitops/install.go
  test/acceptance/README.md
  test/acceptance/test/add_tests.go
  test/acceptance/test/testsuite_common_test.go
  test/acceptance/test/utils.go
Labels: bug

#1019 setup kubebuilder before running unit tests.
  .github/workflows/deploy.yml
Labels: exclude from release notes

#989 Add remove app button
  Makefile
  README.md
  api/applications/applications.proto
  api/applications/applications.swagger.json
  buf.gen.yaml
  pkg/api/applications/applications.pb.gw.go
  ui/components/Alert.tsx
  ui/components/Flex.tsx
  ui/components/GithubDeviceAuthModal.tsx
  ui/components/Layout.tsx
  ui/components/Link.tsx
  ui/components/Modal.tsx
  ui/components/Page.tsx
  ui/components/__tests__/__snapshots__/CommitsTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/lib/api/applications/applications.pb.ts
  ui/lib/theme.ts
  ui/pages/ApplicationDetail.tsx
  ui/pages/Applications.tsx
Labels: ui

#1013 Adds acceptance test for a gitlab subgroup
  test/acceptance/test/add_tests.go
Labels: exclude from release notes

#1042 Commits show up in UI after authentication success
  ui/components/CommitsTable.tsx
  ui/components/__tests__/CommitsTable.test.tsx
  ui/pages/ApplicationDetail.tsx
Labels: ui

#1022 Add UI logging flag
  cmd/gitops/ui/run/cmd.go
  manifests/wego-app/deployment.yaml
Labels: enhancement

#1023 Clarify the description of "namespace" in the UI and CLI
  Makefile
  README.md
  cmd/gitops/root/cmd.go
  test/acceptance/test/install_tests.go
  ui/pages/ApplicationAdd.tsx
Labels: ui

#1047 Fix selenium for macOS on nightly
  go.mod
  go.sum
  test/acceptance/test/ui_tests.go
Labels: exclude from release notes

#966 Creating style guide
  doc/style.md
Labels: documentation, exclude from release notes

#1051 Increase graph node size, and decrease graph node drop shadow
  ui/components/DirectedGraph.tsx
  ui/components/ReconciliationGraph.tsx
Labels: ui

#1048 Updated error message when hit "not found error" in gitprovider
  pkg/gitproviders/provider.go
  pkg/gitproviders/provider_org_test.go
Labels: enhancement

#1060 Restore setup of beta install command
  cmd/gitops/beta/cmd/install.go
Labels: bug

#1063 1062 - Use the correct default config branch for auto-merge
  pkg/services/gitopswriter/gitopswriter.go
  pkg/services/gitopswriter/writer_add_test.go
Labels: bug, severity/Major

#1041 Add namespace to wego-app manifests
  manifests/manifests.go
  manifests/manifests_test.go
  manifests/wego-app/deployment.yaml.tpl
  manifests/wego-app/role-binding.yaml.tpl
  manifests/wego-app/role.yaml.tpl
  manifests/wego-app/service-account.yaml.tpl
  manifests/wego-app/service.yaml.tpl
  pkg/services/app/sync_test.go
  pkg/services/gitops/install.go
  pkg/services/gitops/install_test.go
  pkg/services/gitops/uninstall.go
  pkg/services/gitops/uninstall_test.go
  test/acceptance/test/install_tests.go
Labels: bug

#1052 Renaming Git Provider Token header
  pkg/server/middleware/middleware.go
  pkg/server/middleware/middleware_test.go
  ui/contexts/AppContext.tsx
Labels: enhancement

#1066 Add acceptance test for bug #810 and update how secret names are generated
  .github/actions/run-acceptance-test/action.yml
  pkg/services/app/add_test.go
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  pkg/services/automation/automation_test.go
  pkg/services/automation/generator.go
  pkg/services/gitops/install.go
  test/acceptance/test/add_tests.go
  test/acceptance/test/install_tests.go
  test/acceptance/test/scripts/kind-multi-cluster.sh
  test/acceptance/test/ui_tests.go
  test/acceptance/test/utils.go
  test/integration/server/add_test.go
Labels: enhancement

#1053 Add homebrew to release
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: enhancement

#1065 Changed URL type `git@` for one of the acceptance tests
  test/acceptance/test/install_tests.go
  test/integration/server/helpers/helpers.go
Labels: enhancement

#1072 Update jest, parcel for dependabot notice
  package-lock.json
  package.json
Labels: exclude from release notes

#1073 Ask for confirmation when running `gitops uninstall`.
  cmd/gitops/uninstall/cmd.go
  test/acceptance/test/install_tests.go
Labels: enhancement

#1054 Create empty ssh key for git client to avoid creating real deploy keys when using dry-run.
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  pkg/services/factory.go
Labels: bug

#1097 Add custom ssh key setup to fix actions
  .github/actions/run-acceptance-test/action.yml
  .github/actions/setup-ssh/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yaml
  .github/workflows/test.yml
Labels: exclude from release notes

#1046 Add GitLab OAuth flow the UI
  api/applications/applications.proto
  api/applications/applications.swagger.json
  doc/adr/0010-leaf-cluster-auth-strategy.md
  doc/adr/cluster_auth.seqdiag
  pkg/api/applications/applications.pb.go
  pkg/api/applications/applications.pb.gw.go
  pkg/api/applications/applications_grpc.pb.go
  pkg/server/middleware/middleware.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/suite_test.go
  pkg/services/auth/authfakes/fake_gitlab_auth_client.go
  pkg/services/auth/github.go
  pkg/services/auth/gitlab.go
  pkg/services/auth/gitlab_test.go
  pkg/services/auth/jwt.go
  pkg/services/auth/jwt_test.go
  pkg/services/auth/types/token.go
  test/integration/server/suite_test.go
  ui/App.tsx
  ui/components/AuthAlert.tsx
  ui/components/CommitsTable.tsx
  ui/components/GithubAuthButton.tsx
  ui/components/GithubDeviceAuthModal.tsx
  ui/components/GitlabAuthButton.tsx
  ui/components/Input.tsx
  ui/components/Page.tsx
  ui/components/RepoInputWithAuth.tsx
  ui/components/__tests__/GithubDeviceAuthModal.test.tsx
  ui/components/__tests__/RepoInputWithAuth.test.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/contexts/AppContext.tsx
  ui/contexts/CallbackStateContext.tsx
  ui/hooks/applications.ts
  ui/hooks/auth.ts
  ui/hooks/common.ts
  ui/index.ts
  ui/lib/api/applications/applications.pb.ts
  ui/lib/storage.ts
  ui/lib/test-utils.tsx
  ui/lib/types.ts
  ui/lib/utils.ts
  ui/pages/ApplicationAdd.tsx
  ui/pages/OAuthCallback.tsx
Labels: ui

#1064 Fix cluster pull request statuses
  pkg/adapters/http.go
  pkg/adapters/http_test.go
  pkg/clusters/clusters.go
  pkg/clusters/clusters_test.go
Labels: bug

#1069 Upgrade uses new helm repo
  cmd/gitops/upgrade/cmd.go
  go.mod
  go.sum
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: enhancement

#1078 Add missed changes to goreleaser for brew
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: exclude from release notes

#1087 Add SyncApplication Button to UI
  ui/App.tsx
  ui/components/__tests__/CommitsTable.test.tsx
  ui/components/__tests__/GithubDeviceAuthModal.test.tsx
  ui/components/__tests__/Page.test.tsx
  ui/components/__tests__/RepoInputWithAuth.test.tsx
  ui/contexts/AppContext.tsx
  ui/hooks/__tests__/applications.test.tsx
  ui/hooks/__tests__/auth.test.tsx
  ui/hooks/__tests__/navigation.test.tsx
  ui/lib/test-utils.tsx
  ui/pages/ApplicationDetail.tsx
  ui/pages/__tests__/ApplicationDetail.test.tsx
Labels: ui

#1110 Refactor tests to prevent nightly failures
  test/acceptance/test/add_tests.go
Labels: exclude from release notes

#1116 Adds capi-app when upgrading
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: exclude from release notes

#1112 Pass user token to API via an HTTP header
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/add/clusters/cmd_test.go
  cmd/gitops/cmderrors/errors.go
  cmd/gitops/delete/clusters/cmd.go
  cmd/gitops/delete/clusters/cmd_test.go
  cmd/internal/provider.go
  pkg/adapters/http.go
  pkg/capi/capi.go
  pkg/clusters/clusters.go
  pkg/testutils/testutils.go
Labels: enhancement

#1117 Ignore showing clusters PR url for statuses other than creation/deletion
  pkg/clusters/clusters.go
  pkg/clusters/clusters_test.go
Labels: bug

#1118 Update deps with go mod tidy
  go.mod
  go.sum
Labels: exclude from release notes

#1121 Update package.json for release
  package-lock.json
  package.json
Labels: exclude from release notes

#1119 Fix deploy job
  test/acceptance/test/testsuite_common_test.go
  test/acceptance/test/ui_tests.go
  test/acceptance/test/utils.go
Labels: exclude from release notes

#1127 Adds back file required for consuming as a go module
  Makefile
  pkg/flux/bin/go_embed_fs_cannot_be_empty.txt
Labels: exclude from release notes

#1129 Fixed ssh keys and refactor on reset cluster script
  .github/actions/run-acceptance-test/action.yml
  .github/actions/setup-ssh/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yaml
  .github/workflows/test.yml
  test/acceptance/test/add_tests.go
  test/acceptance/test/scripts/reset-wego.sh
  test/acceptance/test/version_tests.go
Labels: exclude from release notes

#1131 Add known_hosts and kubectl for bootstrap
  Dockerfile
Labels: exclude from release notes

#1099 Set missing namespace on role/rolebinding
  .github/actions/run-acceptance-test/action.yml
  .github/actions/setup-ssh/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yaml
  .github/workflows/test.yml
  manifests/wego-app/role-binding.yaml.tpl
  manifests/wego-app/role.yaml.tpl
  test/acceptance/test/add_tests.go
  test/acceptance/test/scripts/reset-wego.sh
  test/acceptance/test/version_tests.go
Labels: bug

#1146 Fixed adding a Gitlab app via UI
  pkg/server/server.go
Labels: enhancement
