Repository weaveworks/weave-gitops, pull requests merged in 2021-12, with the labels that each got.

#1137 changes ProfileVersion to Version
  cmd/gitops/upgrade/cmd.go
  pkg/upgrade/upgrade.go
Labels: enhancement

#1149 Fixes `gitops upgrade` with gitlab
  pkg/upgrade/upgrade.go
Labels: bug

#1156 Skip GitOps Core UI Tests
  test/acceptance/test/ui_tests.go
Labels: exclude from release notes

#1101 Add integration test coverage for adding an app in a GitLab repo
  .github/workflows/test.yml
  go.mod
  test/integration/server/add_test.go
  test/integration/server/helpers/fetcher.go
  test/integration/server/helpers/helpers.go
Labels: exclude from release notes

#1150 Adjustments to field ExpiresIn in TokenResponseState structure
  pkg/server/server.go
  pkg/services/auth/gitlab_test.go
  pkg/services/auth/types/token.go
  pkg/services/auth/types/token_test.go
  pkg/services/auth/types/types_suite_test.go
Labels: enhancement

#1153 Fixes `gitops install` wego-app.yaml deployment when running in container
  Makefile
  test/acceptance/test/version_tests.go
Labels: bug

#1159 Update package.json for release
  package-lock.json
  package.json
Labels: exclude from release notes

#1114 Add React Storybook + Stories for <Button />
  .storybook/main.js
  .storybook/preview.js
  README.md
  package-lock.json
  package.json
  ui/App.tsx
  ui/components/Alert.tsx
  ui/components/Button.tsx
  ui/components/DataTable.tsx
  ui/components/Flex.tsx
  ui/components/GithubDeviceAuthModal.tsx
  ui/components/Modal.tsx
  ui/components/__tests__/__snapshots__/Flex.test.tsx.snap
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/lib/fonts.ts
  ui/lib/theme.ts
  ui/pages/ApplicationAdd.tsx
  ui/pages/ApplicationDetail.tsx
  ui/pages/Applications.tsx
  ui/stories/Alert.stories.tsx
  ui/stories/Button.stories.tsx
  ui/stories/DataTable.stories.tsx
  ui/stories/Modal.stories.tsx
Labels: ui

#1161 Avoid running other release jobs if goreleaser does not complete
  .github/workflows/release.yaml
  pkg/services/auth/github_test.go
Labels: exclude from release notes

#1162 Set explicit node version
  .github/workflows/release.yaml
Labels: exclude from release notes

#1155 update protobuf files
  Makefile
  api/applications/applications.swagger.json
  buf.lock
  buf.yaml
  go.mod
  go.sum
  pkg/api/applications/applications.pb.go
  pkg/api/applications/applications.pb.gw.go
  pkg/api/applications/applications_grpc.pb.go
  tools/tools.go
Labels: exclude from release notes

#1157 Update Readme to add brew install instructions
  README.md
Labels: exclude from release notes

#1145 Add and Implement Theme Colors
  ui/components/Alert.tsx
  ui/components/Button.tsx
  ui/components/ConditionsTable.tsx
  ui/components/DataTable.tsx
  ui/components/Layout.tsx
  ui/components/Modal.tsx
  ui/components/__tests__/__snapshots__/CommitsTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/lib/theme.ts
  ui/pages/ApplicationAdd.tsx
  ui/stories/DataTable.stories.tsx
  ui/stories/Modal.stories.tsx
Labels: ui, team/bluetonium

#1134 Add negative tests for GitOps Enterprise
  .github/workflows/nightly.yaml
  test/acceptance/test/add_tests.go
  test/acceptance/test/utils.go
Labels: exclude from release notes

#1181 Adds the semver tag to the docker build
  .github/workflows/release.yaml
Labels: bug

#1184 Bump node package version
  package-lock.json
  package.json
Labels: exclude from release notes

#1174 Add app remove page
  ui/App.tsx
  ui/__tests__/library.test.tsx
  ui/components/Button.tsx
  ui/components/GithubAuthButton.tsx
  ui/components/GithubDeviceAuthModal.tsx
  ui/components/GitlabAuthButton.tsx
  ui/components/__tests__/GithubAuthButton.test.tsx
  ui/components/__tests__/__snapshots__/CommitsTable.test.tsx.snap
  ui/contexts/AppContext.tsx
  ui/contexts/GithubAuthContext.tsx
  ui/hooks/applications.ts
  ui/hooks/auth.ts
  ui/hooks/common.ts
  ui/lib/types.ts
  ui/lib/utils.ts
  ui/pages/ApplicationDetail.tsx
  ui/pages/ApplicationRemove.tsx
  ui/pages/__tests__/ApplicationDetail.test.tsx
Labels: ui

#1197 Debug brew
  .github/workflows/release.yaml
Labels: exclude from release notes

#1198 Remove token for pushing to homebrew tap
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: exclude from release notes

#1196 Add gitlab exports
  package-lock.json
  package.json
  pkg/services/auth/internal/gitlab.go
  ui/components/RepoInputWithAuth.tsx
  ui/contexts/AppContext.tsx
  ui/index.ts
  ui/pages/OAuthCallback.tsx
Labels: enhancement

#1187 Remove app-config-url references
  api/applications/applications.proto
  api/applications/applications.swagger.json
  api/v1alpha1/application_types.go
  cmd/gitops/add/app/cmd.go
  cmd/gitops/beta/cmd/add/app.go
  cmd/gitops/beta/cmd/install.go
  cmd/gitops/install/cmd.go
  cmd/gitops/upgrade/cmd.go
  go.mod
  go.sum
  manifests/crds/wego.weave.works_apps.yaml
  pkg/api/applications/applications.pb.go
  pkg/models/application.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/services/app/add.go
  pkg/services/app/add_test.go
  pkg/services/app/remove.go
  pkg/services/applicationv2/fetcher.go
  pkg/services/automation/automation_test.go
  pkg/services/automation/generator.go
  pkg/services/factory.go
  pkg/services/factory_test.go
  pkg/services/gitops/install.go
  pkg/services/gitops/install_test.go
  pkg/services/gitopswriter/writer_add_test.go
  pkg/services/gitopswriter/writer_remove_test.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  test/acceptance/test/add_tests.go
  test/acceptance/test/help_tests.go
  test/acceptance/test/install_tests.go
  test/acceptance/test/pages/add_application_page.go
  test/acceptance/test/ui_tests.go
  test/acceptance/test/utils.go
  test/integration/server/add_test.go
  ui/lib/api/applications/applications.pb.ts
  ui/pages/ApplicationAdd.tsx
Labels: enhancement

#1201 Removing brew temporarily
  .goreleaser.yml
Labels: exclude from release notes

#1195 Horizontal Distribution of Graph Nodes
  ui/components/DirectedGraph.tsx
Labels: ui

#1175 comment out library-integration-test
  .github/workflows/test.yml
Labels: exclude from release notes

#1186 Small Storybook Fixes
  .storybook/main.js
  .storybook/preview.js
  ui/components/Alert.tsx
  ui/components/Button.tsx
  ui/components/DataTable.tsx
  ui/components/GithubAuthButton.tsx
  ui/components/GitlabAuthButton.tsx
  ui/components/Icon.tsx
  ui/components/Modal.tsx
  ui/components/RepoInputWithAuth.tsx
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/pages/ApplicationAdd.tsx
  ui/pages/ApplicationDetail.tsx
  ui/pages/Applications.tsx
  ui/stories/Button.stories.tsx
Labels: ui

#1151 Remove apps via PR for Github and Gitlab
  cmd/gitops/delete/app/cmd.go
  pkg/git/git.go
  pkg/git/gitfakes/fake_git.go
  pkg/git/gogit.go
  pkg/git/gogit_test.go
  pkg/gitproviders/provider.go
  pkg/server/server.go
  pkg/services/app/remove.go
  pkg/services/gitopswriter/gitopswriter.go
  pkg/services/gitopswriter/writer_remove_test.go
  pkg/services/gitrepo/service.go
  test/integration/server/add_test.go
  test/integration/server/helpers/fetcher.go
  test/integration/server/helpers/helpers.go
  test/integration/server/remove_test.go
  test/integration/server/suite_test.go
Labels: enhancement

#1167 Validate namespaces in Gitops Install and Uninstall
  pkg/kube/kube.go
  pkg/kube/kubefakes/fake_kube.go
  pkg/kube/kubehttp.go
  pkg/kube/kubehttp_test.go
  pkg/services/gitops/install.go
  pkg/services/gitops/install_test.go
  pkg/services/gitops/uninstall.go
  pkg/services/gitops/uninstall_test.go
  pkg/testutils/testutils.go
Labels: enhancement

#1148 Add profiles API to query for available profiles
  api/profiles/profiles.proto
  api/profiles/profiles.swagger.json
  cmd/gitops-server/main.go
  cmd/gitops/ui/run/cmd.go
  go.mod
  go.sum
  manifests/manifests.go
  manifests/manifests_test.go
  manifests/wego-app/deployment.yaml.tpl
  manifests/wego-app/role-binding.yaml.tpl
  manifests/wego-app/role.yaml.tpl
  pkg/api/profiles/profiles.pb.go
  pkg/api/profiles/profiles.pb.gw.go
  pkg/api/profiles/profiles_grpc.pb.go
  pkg/helm/charts.go
  pkg/helm/charts_suite_test.go
  pkg/helm/charts_test.go
  pkg/helm/testdata/brokenyaml/index.yaml
  pkg/helm/testdata/charts/demo-profile-0.1.0.tgz
  pkg/helm/testdata/charts/demo-profile/.helmignore
  pkg/helm/testdata/charts/demo-profile/Chart.yaml
  pkg/helm/testdata/charts/demo-profile/templates/configmap.yaml
  pkg/helm/testdata/charts/demo-profile/values.yaml
  pkg/helm/testdata/invalid/index.yaml
  pkg/helm/testdata/no_profiles/index.yaml
  pkg/helm/testdata/parsing/profile.yaml
  pkg/helm/testdata/parsing/values.yaml
  pkg/helm/testdata/with_profiles/index.yaml
  pkg/server/handler.go
  pkg/server/profiles.go
  pkg/server/profiles_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/serverfakes/fake_helm_repo_manager.go
  pkg/services/gitops/install.go
  test/acceptance/test/profiles_test.go
  test/acceptance/test/utils.go
  ui/lib/api/profiles/profiles.pb.ts
Labels: enhancement

#1217 Fix uninstall build error
  manifests/manifests.go
  manifests/manifests_test.go
  pkg/services/gitops/install.go
  pkg/services/gitops/uninstall.go
  pkg/services/gitops/uninstall_test.go
Labels: exclude from release notes

#1218 Fix broken validation output from dry-run
  pkg/services/gitops/install.go
Labels: bug, aws-marketplace, team/pitch-black

#1222 Regenerate proto related objects after renaming ConfigURL to ConfigRepo
  api/profiles/profiles.swagger.json
  api/v1alpha1/application_types.go
  buf.lock
  manifests/crds/wego.weave.works_apps.yaml
  pkg/api/applications/applications.pb.go
  pkg/api/applications/applications.pb.gw.go
Labels: bug

#1223 Add support for cluster names with path separators
  pkg/git/git.go
  pkg/services/app/add_test.go
  pkg/services/gitops/install.go
  pkg/services/gitopswriter/gitopswriter.go
  pkg/services/gitopswriter/writer_remove_test.go
Labels: bug

#1182 contributing guide
  CONTRIBUTING.md
  Makefile
Labels: exclude from release notes

#1183 Check environment variables are set before running integration/acceptance tests
  .github/workflows/test.yml
  test/acceptance/test/add_tests.go
  test/acceptance/test/flux_tests.go
  test/acceptance/test/help_tests.go
  test/acceptance/test/install_tests.go
  test/acceptance/test/profiles_test.go
  test/acceptance/test/testsuite_common_test.go
  test/acceptance/test/ui_tests.go
  test/acceptance/test/utils.go
  test/acceptance/test/version_tests.go
  test/integration/server/add_test.go
  test/integration/server/suite_test.go
Labels: exclude from release notes

#1154 Add polling to Applications Page
  ui/components/PollingIndicator.tsx
  ui/pages/Applications.tsx
Labels: ui

#1219 Allow specifying git-host-to-provider-type mapping for on-prem gitlab support
  cmd/gitops/root/cmd.go
  cmd/internal/provider.go
  pkg/gitproviders/factory.go
  pkg/gitproviders/factory_test.go
  pkg/gitproviders/repo_url.go
  pkg/gitproviders/repo_url_test.go
  pkg/server/internal/provider.go
  pkg/services/auth/internal/gitlab.go
Labels: enhancement

#1221 Add GitLab auth flow to application detail and remove
  ui/components/CommitsTable.tsx
  ui/components/__tests__/CommitsTable.test.tsx
  ui/lib/storage.ts
  ui/pages/ApplicationDetail.tsx
  ui/pages/ApplicationRemove.tsx
Labels: ui

#1232 Revert field name from config_repo to config_url in wego app CRD
  api/v1alpha1/application_types.go
  manifests/crds/wego.weave.works_apps.yaml
Labels: exclude from release notes

#1234 Update docs for v0.6.0
  README.md
  package-lock.json
  package.json
Labels: exclude from release notes

#1237 Fixed bug in AuthAlert that prevented GithubDeviceAuthModal from opening
  ui/pages/ApplicationDetail.tsx
Labels: ui

#1243 Forcing kube apply
  pkg/kube/kubehttp.go
Labels: exclude from release notes

#1239 Configure zapr logger to skip the caller
  pkg/server/internal/logger.go
Labels: enhancement

#1233 Add Button Improvements and Update Logo
  ui/__tests__/library.test.tsx
  ui/components/ActionBar.tsx
  ui/components/Button.tsx
  ui/components/GithubDeviceAuthModal.tsx
  ui/components/Layout.tsx
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/images/logo.svg
  ui/lib/fonts.ts
  ui/lib/theme.ts
  ui/pages/ApplicationDetail.tsx
  ui/pages/Applications.tsx
  ui/stories/Button.stories.tsx
  ui/typedefs/styled.d.ts
Labels: ui

#1202 Improve Graph Zoom Functionality
  ui/components/DirectedGraph.tsx
  ui/components/Input.tsx
  ui/components/ReconciliationGraph.tsx
  ui/lib/theme.ts
Labels: ui

#1244 Update go version to 1.17
  .github/actions/run-acceptance-test/action.yml
  .github/workflows/deploy.yml
  .github/workflows/frontend.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/test.yml
  .github/workflows/upgrade-flux.yaml
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  manifests/crds/wego.weave.works_apps.yaml
  manifests/manifests.go
  test/integration/server/helpers/fetcher.go
  test/integration/server/helpers/helpers.go
  test/library/libtest.dockerfile
  tools/tools.go
Labels: enhancement, severity/Low, team/pitch-black

#1252 Removed duplicate fail register
  test/acceptance/test/testsuite_common_test.go
Labels: exclude from release notes

#1260 Attempt to fix CI by removing include in smoke-tests-long job
  .github/actions/run-acceptance-test/action.yml
  .github/workflows/test.yml
Labels: exclude from release notes
