Repository weaveworks/weave-gitops, pull requests merged in 2022-03, with the labels that each got.

#1567 docs: Ensure secret literal is quoted properly
  website/docs/gitops-dashboard.md
Labels: documentation, exclude from release notes

#1570 Fix useLocation hook use in nav.ts
  ui/components/Breadcrumbs.tsx
  ui/lib/nav.ts
Labels: ui

#1605 Add text style fixes and V2Route correction
  ui/components/Breadcrumbs.tsx
  ui/components/DataTable.tsx
  ui/components/InfoList.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/CommitsTable.test.tsx.snap
  ui/lib/nav.ts
  ui/lib/types.ts
Labels: ui

#1608 fix: smooth out v2 dev process
  README.md
  Tiltfile
  api/v1alpha1/application_types.go
  pkg/server/auth/server.go
  tools/dev-manifests/helm_watcher_role.yaml
  tools/dev-manifests/helm_watcher_role_binding.yaml
  tools/dev-manifests/role-binding.yaml
  tools/dev-manifests/role.yaml
  tools/dev-manifests/service-account.yaml
  tools/dev-manifests/wego-app.yaml
Labels: exclude from release notes

#1622 Add Status Icons
  ui/components/Icon.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/images/failed.svg
  ui/images/success.svg
  ui/images/suspended.svg
Labels: ui

#1636 Make Cluster Name Default for Single Cluster
  ui/components/AutomationsTable.tsx
  ui/components/SourcesTable.tsx
  ui/pages/v2/FluxRuntime.tsx
Labels: ui

#1647 docs: Fix old docs repo links in Website
  doc/release-process.md
  website/docusaurus.config.js
Labels: exclude from release notes

#1660 Adds a global `--insecure-skip-tls-verify` flag to the cli
  cmd/gitops/root/cmd.go
  cmd/gitops/root/cmd_test.go
  test/acceptance/test/install_tests.go
Labels: enhancement, team/pesto

#1635 Add Border to Source Detail Error Message
  ui/components/PageStatus.tsx
  ui/components/SourceDetail.tsx
  ui/pages/v2/HelmReleaseDetail.tsx
  ui/pages/v2/KustomizationDetail.tsx
Labels: ui

#1624 WG529 Auth styling and flags improvements
  cmd/gitops/cmderrors/errors.go
  cmd/gitops/ui/run/cmd.go
  cmd/gitops/ui/run/cmd_test.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  ui/components/UserSettings.tsx
  ui/contexts/AuthContext.tsx
  ui/contexts/FeatureFlags.tsx
  ui/images/SignInBackground.svg
  ui/images/SignInWheel.svg
  ui/lib/theme.ts
  ui/pages/SignIn.tsx
Labels: enhancement, team/pesto

#1689 Initial instructions on how to configure TLS in EE
  website/docs/enterprise/configuration.mdx
  website/docs/enterprise/tls.mdx
  website/docs/enterprise/upgrading.mdx
Labels: documentation, exclude from release notes, team/pesto

#1599 Update auth docs
  website/docs/enterprise/oidc.mdx
  website/docs/gitops-dashboard.md
Labels: exclude from release notes, team/pesto

#1729 Remove TLS certs from dev image and dev cycle
  README.md
  Tiltfile
  charts/weave-gitops/templates/wego-app.yaml
  dev.dockerfile
Labels: exclude from release notes

#1730 fix: Return UserInfo{} if superuser not logged in
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
Labels: bug

#1627 ClustersClientsPool Middleware
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/clustersmngrfakes/fake_cluster_fetcher.go
  core/clustersmngr/middleware.go
  core/clustersmngr/middleware_test.go
  core/clustersmngr/single_fetcher.go
  core/clustersmngr/single_fetcher_test.go
  core/clustersmngr/suite_test.go
  core/server/kustomization.go
  core/server/server.go
  core/server/suite_test.go
  pkg/server/handler.go
  ui/components/SearchField.tsx
  ui/components/SearchInput.tsx
  ui/stories/SearchInput.stories.tsx
Labels: enhancement

#1740 ref: Tidy up how we process OIDC config
  cmd/gitops-server/cmd/cmd.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
Labels: exclude from release notes

#1733 Remove surviving manifest
  manifests/wego-app/admin-role-binding.yaml.tpl
Labels: exclude from release notes

#1732 refactor: Clean up kube client initialization references
  cmd/gitops-server/cmd/cmd.go
  core/server/events_test.go
  core/server/fluxruntime_test.go
  core/server/helm_release_test.go
  core/server/kustomization_test.go
  core/server/namespace_test.go
  core/server/sources_test.go
Labels: enhancement

#1736 refactor: Clean up kube config getting refereces
  cmd/gitops-server/cmd/cmd.go
  pkg/kube/kubehttp.go
  pkg/server/server.go
Labels: enhancement

#1738 Removing gitprovider middleware
  pkg/server/handler.go
  pkg/server/middleware/middleware_test.go
Labels: enhancement

#1748 Log out response from GitHub when there's an error.
  pkg/services/auth/github.go
  pkg/services/auth/github_test.go
Labels: exclude from release notes

#1731 ci: Remove deploy workflow
  .github/workflows/deploy.yml
  .github/workflows/pr.yaml
Labels: exclude from release notes

#1753 Fix lint errors from #1748
  pkg/services/auth/github.go
Labels: exclude from release notes

#1750 Add polling through react-query
  ui/components/Layout.tsx
  ui/components/Page.tsx
  ui/components/PollingIndicator.tsx
  ui/components/SourceDetail.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/hooks/automations.ts
  ui/hooks/events.ts
  ui/hooks/flux.ts
  ui/hooks/sources.ts
  ui/pages/v2/Automations.tsx
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/FluxRuntime.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmReleaseDetail.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
  ui/pages/v2/KustomizationDetail.tsx
  ui/pages/v2/Sources.tsx
Labels: ui

#1756 Fix binary S3 upload
  .github/workflows/pr.yaml
Labels: exclude from release notes

#1764 Remove flux auto-upgrade
  .github/workflows/upgrade-flux.yaml
  tools/get-flux-update-pr.sh
Labels: exclude from release notes

#1760 fix: Check for readyText after it has been set
  ui/components/KubeStatusIndicator.tsx
Labels: bug

#1768 Remove unused commands
  cmd/gitops/install/cmd.go
  cmd/gitops/install/cmd_test.go
  cmd/gitops/root/cmd.go
  cmd/gitops/ui/cmd.go
Labels: exclude from release notes

#1769 fix: Fix buf warnings
  buf.gen.yaml
  buf.lock
  go.mod
  go.sum
  ui/lib/api/applications/applications.pb.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/profiles/profiles.pb.ts
  ui/lib/fetch.pb.ts
Labels: exclude from release notes

#1771 Upgrade prometheus client
  go.mod
  go.sum
Labels: exclude from release notes

#1758 Switch isFetching to useIsFetching
  ui/components/Page.tsx
  ui/components/PageStatus.tsx
  ui/components/SourceDetail.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/lib/test-utils.tsx
  ui/pages/v2/Automations.tsx
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/FluxRuntime.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmReleaseDetail.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
  ui/pages/v2/KustomizationDetail.tsx
  ui/pages/v2/Sources.tsx
Labels: ui

#1751 1560 upgrade command
  cmd/gitops/upgrade/cmd.go
  go.mod
  go.sum
  package-lock.json
  pkg/upgrade/upgrade.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  pkg/utils/testdata/config.yaml
  pkg/utils/testdata/ingress.yaml
  pkg/utils/testdata/partial-config.yaml
Labels: enhancement

#1775 ref: Refactor utils tests
  pkg/utils/common_test.go
  pkg/utils/utils_suite_test.go
Labels: exclude from release notes

#1770 Remove actively misleading help texts
  cmd/gitops/add/cmd.go
  cmd/gitops/delete/cmd.go
  cmd/gitops/get/cmd.go
  cmd/gitops/root/cmd.go
Labels: exclude from release notes

#1779 Helm upgrades
  Tiltfile
  charts/gitops-server/.helmignore
  charts/gitops-server/Chart.yaml
  charts/gitops-server/README.md
  charts/gitops-server/templates/NOTES.txt
  charts/gitops-server/templates/_helpers.tpl
  charts/gitops-server/templates/admin-user.yaml
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/templates/ingress.yaml
  charts/gitops-server/templates/role.yaml
  charts/gitops-server/templates/rolebinding.yaml
  charts/gitops-server/templates/service.yaml
  charts/gitops-server/templates/serviceaccount.yaml
  charts/gitops-server/templates/tests/test-connection.yaml
  charts/gitops-server/values.yaml
  charts/weave-gitops/Chart.yaml
  charts/weave-gitops/templates/admin.yaml
  charts/weave-gitops/templates/wego-app.yaml
  charts/weave-gitops/values.yaml
  tools/helm-values-dev.yaml
Labels: enhancement

#1797 Add a date prefix to the docker tag for PR images
  .github/workflows/pr.yaml
Labels: enhancement

#1802 Fix date substitution in PR workflow
  .github/workflows/pr.yaml
Labels: bug

#1803 More fix date images
  .github/workflows/pr.yaml
Labels: bug

#1799 Use Node 16 for the release and docs workflows
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
Labels: exclude from release notes

#1794 update dependencies
  website/package.json
  website/yarn.lock
Labels: enhancement

#1790 Allow overflowed data to scroll
  ui/components/AutomationsTable.tsx
  ui/components/DataTable.tsx
  ui/components/HashRouterTabs.tsx
  ui/components/Layout.tsx
  ui/components/Page.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/lib/theme.ts
Labels: ui

#1805 Remove title bar padding and shrink logo
  ui/components/Layout.tsx
  ui/components/Logo.tsx
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
Labels: ui

#1815 Update package.json for rc3
  package-lock.json
  package.json
  ui/components/AutomationsTable.tsx
  ui/components/Page.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/hooks/events.ts
  ui/hooks/flux.ts
  ui/pages/v2/KustomizationDetail.tsx
Labels: exclude from release notes

#1818 Fix newline problem
  package-lock.json
Labels: exclude from release notes

#1820 Specify docker file in release job
  .github/workflows/release.yaml
Labels: exclude from release notes

#1783 docs: Support staging multiple branches, remove docs front page
  .github/workflows/docs.yaml
  website/README.md
  website/src/components/HomepageFeatures.js
  website/src/components/HomepageFeatures.module.css
  website/src/pages/index.js
  website/src/pages/index.module.css
  website/src/pages/markdown-page.md
  website/static/index.html
Labels: exclude from release notes

#1824 README: Fix badges
  README.md
Labels: exclude from release notes

#1825 chore: Update PR/Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/pull_request_template.md
Labels: exclude from release notes

#1804 feat: Add over-engineered reboot script
  tools/reboot.sh
Labels: exclude from release notes

#1780 feat: Create a namespace client and watcher
  charts/gitops-server/templates/role.yaml
  core/cache/container.go
  core/cache/container_test.go
  core/cache/namespace.go
  core/cache/namespace_test.go
  core/logger/logger_test.go
  core/server/fluxruntime.go
  core/server/labels.go
  core/server/namespace.go
  core/server/namespace_test.go
  core/server/server.go
  core/server/sources.go
Labels: enhancement

#1823 Adds in the coveted reconciliation graph (again)
  package-lock.json
  package.json
  ui/components/ReconciledObjectsTable.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/RequestStateHandler.tsx
  ui/hooks/flux.ts
  ui/pages/v2/KustomizationDetail.tsx
Labels: ui

#1822 Add Tabs for Helm Release Detail
  ui/pages/v2/HelmReleaseDetail.tsx
Labels: ui

#1727 Write a more approachable release-tagging script
  tools/tag-release
  tools/tag-release.sh
Labels: exclude from release notes

#1807 Sort by Status
  ui/components/AutomationsTable.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/DataTable.test.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/lib/utils.ts
  ui/pages/v2/FluxRuntime.tsx
Labels: ui

#1828 website: Replace static file redirect with JS redirect
  .github/workflows/docs.yaml
  website/src/pages/index.js
  website/static/index.html
Labels: exclude from release notes

#1695 Put explicit snyk scan workflow back
  .github/workflows/pr.yaml
Labels: exclude from release notes

#1832 Release helm chart whenever it's changed
  .github/workflows/chart.yaml
  charts/gitops-server/Chart.yaml
  charts/gitops-server/values.yaml
  doc/release-process.md
Labels: enhancement

#1814 Clusters Client
  core/clustersmngr/client.go
  core/clustersmngr/client_test.go
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/middleware.go
  core/clustersmngr/middleware_test.go
  core/server/kustomization.go
  core/server/suite_test.go
  pkg/server/handler.go
Labels: enhancement

#1834 Add a fallback option to output the latest tag
  tools/tag-release
Labels: exclude from release notes

#1836 Generate documentation PRs against `main`
  .github/workflows/release.yaml
Labels: exclude from release notes

#1798 docs: add adr 0012-acceptance-testing document
  doc/adr/0012-acceptance-testing.md
Labels: documentation, exclude from release notes, area/testing

#1806 docs: add adr 0013-acceptance-testing-strategy document
  doc/adr/0013-acceptance-testing-strategy.md
Labels: documentation, exclude from release notes, area/testing

#1843 feat: Use client from pool to Get kustomization
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/single_fetcher.go
  core/server/kustomization.go
  core/server/kustomization_test.go
  core/server/types/kustomization.go
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  ui/App.tsx
  ui/components/AutomationsTable.tsx
  ui/hooks/automations.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/types.ts
  ui/pages/v2/KustomizationDetail.tsx
Labels: enhancement, team/mauvelous

#1839 fix: Interval values are not correct everywhere
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/helmrepository.go
  core/server/types/kustomization.go
  core/server/types/utils.go
Labels: bug

#1852 fix: Ordering within filter menu changes periodically
  ui/components/FilterDialog.tsx
Labels: bug

#1850 feat: Use clientpool to Get and List HelmReleases
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/helm_release.go
  core/server/helm_release_test.go
  core/server/server.go
  core/server/types/helmrelease.go
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  ui/hooks/automations.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/pages/v2/HelmReleaseDetail.tsx
Labels: enhancement, team/mauvelous

#1835 Convert DirectedGraph d3 logic into class
  ui/components/DirectedGraph.tsx
Labels: ui
