Repository weaveworks/weave-gitops, pull requests merged in 2022-05, with the labels that each got.

#2054 Make filter state url addressable
  ui/components/FilterDialog.tsx
  ui/components/FilterableTable.tsx
  ui/components/__tests__/FilterableTable.test.tsx
Labels: ui

#2058 fix: Timestamp column is empty on Event list pages
  core/server/events.go
  ui/components/Timestamp.tsx
Labels: bug

#2059 Update README.md for a better overview
  README.md
Labels: exclude from release notes

#2015 UI Responsiveness Pass
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/DataTable.tsx
  ui/components/DirectedGraph.tsx
  ui/components/EventsTable.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/InfoList.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/Layout.tsx
  ui/components/Page.tsx
  ui/components/PageStatus.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourceDetail.tsx
  ui/components/SourceLink.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/pages/v2/Automations.tsx
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/FluxRuntime.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmReleasePage.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
  ui/pages/v2/KustomizationPage.tsx
  ui/pages/v2/Sources.tsx
Labels: ui

#2060 Fix formatting on readme
  MAINTAINERS
  README.md
  doc/img/01-apps.png
  doc/img/02-reconciliation.png
  doc/img/03-sources.png
  doc/img/04-flux-runtime.png
Labels: exclude from release notes

#2056 feat: ClusterRole for default user
  charts/gitops-server/templates/admin-user.yaml
  charts/gitops-server/values.yaml
  website/docs/configuration/securing-access-to-the-dashboard.mdx
Labels: enhancement

#2011 feat: update profiles cmds to support API move to enterprise
  cmd/gitops/add/cmd.go
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/add/profiles/cmd_test.go
  cmd/gitops/get/cmd.go
  cmd/gitops/get/profiles/cmd.go
  cmd/gitops/update/cmd.go
  cmd/gitops/update/profiles/profiles.go
  cmd/gitops/update/profiles/profiles_test.go
  go.mod
  pkg/adapters/http.go
  pkg/services/profiles/add.go
  pkg/services/profiles/add_test.go
  pkg/services/profiles/get.go
  pkg/services/profiles/get_test.go
  pkg/services/profiles/profiles.go
  pkg/services/profiles/update.go
  pkg/services/profiles/update_test.go
Labels: exclude from release notes

#2025 Update WGE installation instructions after reloaded integration
  website/docs/_components/CurlCodeBlock.jsx
  website/docs/assets/example-enterprise-helm.yaml
  website/docs/cluster-management/assets/bootstrap/capi-gitops-cluster-bootstrap-config.yaml
  website/docs/cluster-management/assets/profiles/profile-repo.yaml
  website/docs/cluster-management/assets/templates/capd-template.yaml
  website/docs/cluster-management/deleting-a-cluster.mdx
  website/docs/cluster-management/getting-started.mdx
  website/docs/cluster-management/templates.mdx
  website/docs/configuration/tls.md
  website/docs/guides/deploying-capa.mdx
  website/docs/installation.mdx
Labels: exclude from release notes

#2073 fix: socially distanced if blocks are required, no touching please
  pkg/services/profiles/get.go
Labels: exclude from release notes

#2074 chore(ci): Skip CI runs if no code changes
  .github/workflows/pr.yaml
Labels: exclude from release notes

#1990 docs: Document Dex setup
  dev.dockerfile
  doc/setting-up-dex.md
  website/README.md
  website/docs/configuration/tls.md
  website/docs/guides/cert-manager.md
  website/docs/guides/setting-up-dex.md
  website/static/img/guides/setting-up-dex/dex-auth.png
  website/static/img/guides/setting-up-dex/github-auth.png
  website/static/img/guides/setting-up-dex/github-oauth-application.png
  website/static/img/guides/setting-up-dex/oidc-login.png
  website/static/img/guides/setting-up-dex/ui-logged-in.png
  website/yarn.lock
Labels: exclude from release notes

#2072 Backport WGE 0.8.0 docs
  website/versioned_docs/version-0.8.0/_components/CurlCodeBlock.jsx
  website/versioned_docs/version-0.8.0/assets/example-enterprise-helm.yaml
  website/versioned_docs/version-0.8.0/cluster-management/assets/bootstrap/capi-gitops-cluster-bootstrap-config.yaml
  website/versioned_docs/version-0.8.0/cluster-management/assets/profiles/profile-repo.yaml
  website/versioned_docs/version-0.8.0/cluster-management/assets/templates/capd-template.yaml
  website/versioned_docs/version-0.8.0/cluster-management/deleting-a-cluster.mdx
  website/versioned_docs/version-0.8.0/cluster-management/getting-started.mdx
  website/versioned_docs/version-0.8.0/cluster-management/templates.mdx
  website/versioned_docs/version-0.8.0/configuration/securing-access-to-the-dashboard.mdx
  website/versioned_docs/version-0.8.0/configuration/tls.md
  website/versioned_docs/version-0.8.0/guides/deploying-capa.mdx
  website/versioned_docs/version-0.8.0/installation.mdx
Labels: documentation, exclude from release notes

#2070 ci: Add step that fails if chart is changed but version isn't
  .github/workflows/chart.yaml
Labels: exclude from release notes

#2079 Add the reconciliation graph to HelmRelease detail page
  api/core/core.proto
  api/core/core.swagger.json
  core/server/helm_release.go
  pkg/api/core/core.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/FilterableTable.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/hooks/automations.ts
  ui/lib/api/core/core.pb.ts
  ui/pages/v2/HelmReleasePage.tsx
  ui/pages/v2/KustomizationPage.tsx
Labels: ui

#2094 ci: Fix check to see that chart version was bumped
  .github/workflows/chart.yaml
Labels: exclude from release notes

#2091 Add version endpoint
  Makefile
  api/core/core.proto
  api/core/core.swagger.json
  cmd/gitops-server/cmd/cmd.go
  core/server/version.go
  core/server/version_test.go
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  ui/lib/api/core/core.pb.ts
Labels: enhancement

#2101 Don't use quotes on flags to docker build action
  .github/workflows/pr.yaml
Labels: bug

#2103 Update bug report template with version info
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, exclude from release notes

#2102 feat: Show container image for applications [server side]
  api/core/core.swagger.json
  api/core/types.proto
  core/server/fluxruntime.go
  pkg/api/core/types.pb.go
  ui/lib/api/core/types.pb.ts
Labels: enhancement

#2100 fix: Missing deployments on Kustomization detail page
  core/server/fluxruntime.go
Labels: bug

#2118 fix: Applications object graph does not reconcile automatically
  ui/components/DirectedGraph.tsx
Labels: bug

#2112 Match AutomationDetail styling to SourceDetail
  ui/components/AutomationDetail.tsx
Labels: ui

#2088 Try to fix snyk, again
  .github/snyk_delta_all_projects.sh
  .github/workflows/pr.yaml
  package-lock.json
Labels: exclude from release notes

#2123 Shrink JS dependencies
  package-lock.json
  package.json
  ui/stories/Alert.stories.tsx
  ui/stories/Button.stories.tsx
  ui/stories/ChipGroup.stories.tsx
  ui/stories/DataTable.stories.tsx
  ui/stories/FilterBar.stories.tsx
  ui/stories/Modal.stories.tsx
  ui/stories/Pagination.stories.tsx
Labels: exclude from release notes

#2121 Removing unused things
  main.go
  main_test.go
Labels: exclude from release notes

#2122 Remove replace directives that weren't necessary
  go.mod
  go.sum
Labels: exclude from release notes

#2127 Add exports
  .proxyrc.js
  ui/components/DataTable.tsx
  ui/index.ts
Labels: ui

#2137 Continue processing and updating the clustermngr caches onError
  core/clustersmngr/factory.go
Labels: bug

#2111 docs: Add helm chart reference
  .github/workflows/prepare-release.yaml
  charts/gitops-server/Chart.yaml
  charts/gitops-server/README.md.gotmpl
  charts/gitops-server/templates/role.yaml
  charts/gitops-server/values.yaml
  tools/update-docs.sh
  website/docs/getting-started.mdx
  website/docs/installation.mdx
  website/docs/references/_category_.json
  website/docs/references/cli-reference/_category_.json
  website/docs/references/cli-reference/gitops.md
  website/docs/references/cli-reference/gitops_add.md
  website/docs/references/cli-reference/gitops_add_cluster.md
  website/docs/references/cli-reference/gitops_add_profile.md
  website/docs/references/cli-reference/gitops_check.md
  website/docs/references/cli-reference/gitops_completion.md
  website/docs/references/cli-reference/gitops_completion_bash.md
  website/docs/references/cli-reference/gitops_completion_fish.md
  website/docs/references/cli-reference/gitops_completion_powershell.md
  website/docs/references/cli-reference/gitops_completion_zsh.md
  website/docs/references/cli-reference/gitops_delete.md
  website/docs/references/cli-reference/gitops_delete_cluster.md
  website/docs/references/cli-reference/gitops_get.md
  website/docs/references/cli-reference/gitops_get_cluster.md
  website/docs/references/cli-reference/gitops_get_credential.md
  website/docs/references/cli-reference/gitops_get_profile.md
  website/docs/references/cli-reference/gitops_get_template.md
  website/docs/references/cli-reference/gitops_update.md
  website/docs/references/cli-reference/gitops_update_profile.md
  website/docs/references/cli-reference/gitops_upgrade.md
  website/docs/references/cli-reference/gitops_version.md
  website/docs/references/helm-reference.md
Labels: exclude from release notes

#2120 Clarify dev envs and docs
  .proxyrc.js
  CONTRIBUTING.md
  MAINTAINERS
  README.md
  Tiltfile
  doc/development-process.md
  doc/style.md
Labels: documentation, exclude from release notes

#2131 Upgrade docusaurus to latest version
  .github/workflows/pr.yaml
  website/README.md
  website/docs/installation.mdx
  website/docusaurus.config.js
  website/package.json
  website/versioned_docs/version-0.7.0/installation.mdx
  website/versioned_docs/version-0.8.0/installation.mdx
  website/yarn.lock
Labels: exclude from release notes

#2116 Supporting Partial success results for clustered list
  api/core/core.proto
  api/core/core.swagger.json
  core/clustersmngr/client.go
  core/clustersmngr/client_test.go
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/clustersmngrfakes/fake_clients_pool.go
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/kustomization.go
  pkg/api/core/core.pb.go
  ui/lib/api/core/core.pb.ts
Labels: enhancement

#2106 docs: Simplify OIDC documentation
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/versioned_docs/version-0.8.0/configuration/securing-access-to-the-dashboard.mdx
Labels: exclude from release notes

#2148 Stop using logrus
  README.md
  cmd/gitops/root/cmd.go
  cmd/gitops/version/cmd.go
  go.mod
Labels: exclude from release notes

#2128 Remove server internal module
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/update/profiles/profiles.go
  cmd/gitops/upgrade/cmd.go
  cmd/internal/logger.go
  cmd/internal/logger_test.go
  pkg/server/internal/internal_suite_test.go
  pkg/server/internal/logger.go
  pkg/server/internal/provider.go
  pkg/server/internal/provider_test.go
  pkg/server/server.go
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  pkg/services/factory.go
  pkg/services/factory_test.go
Labels: exclude from release notes

#2146 Use ready condition for automations table timestamp
  ui/components/AutomationsTable.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/lib/utils.ts
Labels: ui

#2096 Refactor table URL filtering for testability
  ui/components/AutomationDetail.tsx
  ui/components/AutomationsTable.tsx
  ui/components/DataTable.tsx
  ui/components/FilterDialog.tsx
  ui/components/FilterableTable.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/SourcesTable.tsx
  ui/components/URLAddressableTable.tsx
  ui/components/__tests__/FilterDialog.test.tsx
  ui/components/__tests__/FilterableTable.test.tsx
Labels: ui

#2147 Change table filtering logic to AND between categories, and OR within…
  ui/components/FilterableTable.tsx
  ui/components/__tests__/FilterableTable.test.tsx
Labels: ui

#2145 Simplify bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: exclude from release notes

#2139 server: Start logging all requests, and fix specifying log levels to application
  cmd/gitops-server/cmd/cmd.go
  core/logger/logger.go
  pkg/server/handler.go
  pkg/server/middleware/middleware.go
Labels: bug

#2153 Put tsconfig & parcelrc into UI build dockerfile
  gitops-server.dockerfile
Labels: exclude from release notes

#2152 Remove offline_access from OIDC token requests
  pkg/server/auth/auth.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/server.go
Labels: exclude from release notes

#2157 Dynamically pass in the right automation kind
  ui/components/AutomationDetail.tsx
Labels: bug

#2161 Pass in right source when automation is helm release
  ui/components/AutomationDetail.tsx
Labels: bug

#2155 580 UI need to improve the error message for wrong cluster user password
  ui/pages/SignIn.tsx
Labels: ui

#2142 [UI] Lottie and check update
  package-lock.json
  package.json
  ui/components/Animations/Error404.tsx
  ui/components/Animations/SignInBackground.tsx
  ui/components/__tests__/GithubAuthButton.test.tsx
  ui/components/__tests__/Page.test.tsx
  ui/contexts/FeatureFlags.tsx
  ui/hooks/featureflags.ts
  ui/hooks/gitprovider.ts
  ui/images/SignInBackground.json
  ui/images/SignInBackground.svg
  ui/images/error404.json
  ui/lib/images.ts
  ui/pages/Error.tsx
  ui/pages/SignIn.tsx
Labels: ui

#2136 Add some more detail about k8s RBAC
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/role.yaml
  charts/gitops-server/values.yaml
  tools/helm-values-dev.yaml
  website/docs/configuration/recommended-rbac-configuration.mdx
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/docs/configuration/service-account-permissions.mdx
  website/docs/configuration/tls.md
  website/docs/configuration/user-permissions.mdx
Labels: documentation, exclude from release notes

#2165 Use 'viewSecretsResourceNames' no 'viewSecrets' in dev values.yaml
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/role.yaml
  tools/helm-values-dev.yaml
  website/docs/configuration/service-account-permissions.mdx
Labels: bug

#2168 Listing cluster scoped objects + allow specifying sheme for clients factory
  cmd/gitops-server/cmd/cmd.go
  core/clustersmngr/client.go
  core/clustersmngr/client_test.go
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/factory.go
  core/clustersmngr/factory_test.go
  core/clustersmngr/middleware_test.go
  core/server/helm_release.go
  core/server/kustomization.go
  core/server/sources.go
  core/server/suite_test.go
Labels: enhancement

#2172 Add Suspend/Resume endpoint
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/internal/adapters.go
  core/server/suspend.go
  core/server/suspend_test.go
  core/server/sync.go
  core/server/sync_test.go
  core/server/types/kustomization.go
  core/server/types/utils.go
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourceDetail.tsx
  ui/components/SourcesTable.tsx
  ui/hooks/automations.ts
  ui/hooks/flux.ts
  ui/hooks/sources.ts
  ui/index.ts
  ui/lib/__tests__/graph.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/graph.ts
  ui/lib/nav.ts
  ui/lib/types.ts
Labels: enhancement

#2182 Provide auth compatibility for older images
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/deployment.yaml
Labels: bug

#2176 Display backend version in footer
  api/core/core.proto
  api/core/core.swagger.json
  core/server/version.go
  core/server/version_test.go
  pkg/api/core/core.pb.go
  ui/components/Footer.tsx
  ui/components/__tests__/Footer.test.tsx
  ui/components/__tests__/Page.test.tsx
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/hooks/version.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/test-utils.tsx
Labels: ui, team-denim

#2167 refactor CoreClientCOntext to be more extensible
  ui/contexts/CoreClientContext.tsx
  ui/index.ts
Labels: enhancement

#2190 Fix helmChart error
  ui/components/AutomationDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/ReconciliationGraph.tsx
Labels: ui, team-denim

#2189 Handle empty filter dialog options + adjust font sizes
  ui/components/DataTable.tsx
  ui/components/FilterDialog.tsx
  ui/components/Text.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/components/__tests__/__snapshots__/Text.test.tsx.snap
  ui/lib/theme.ts
  ui/typedefs/styled.d.ts
Labels: ui

#2193 ui: Fix a couple of problems displaying & linking to objects
  ui/components/AutomationsTable.tsx
  ui/hooks/sources.ts
Labels: bug

#2195 Fix documentation typo
  website/docs/installation.mdx
Labels: bug

#2126 Implement `add terraform` to apply a TF template
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/add/cmd.go
  cmd/gitops/add/terraform/cmd.go
  cmd/gitops/add/terraform/cmd_test.go
  cmd/internal/flags.go
  pkg/adapters/http.go
  pkg/adapters/http_test.go
  pkg/capi/capi.go
  pkg/capi/capi_test.go
  pkg/templates/templates.go
  pkg/templates/templates_test.go
  pkg/testutils/testutils.go
Labels: enhancement, team/pitch-black

#2192 Provide the correct source namespace in automations
  core/server/types/helmrelease.go
  core/server/types/helmrepository_test.go
  core/server/types/kustomization.go
  core/server/types/kustomization_test.go
  ui/components/AutomationsTable.tsx
Labels: bug

#2197 Upgrade a couple of dependencies with security warnings
  go.mod
  go.sum
Labels: exclude from release notes

#2199 Add support for showing helmrelease versions in UI
  api/core/core.swagger.json
  api/core/types.proto
  core/server/types/helmrelease.go
  core/server/types/helmrepository_test.go
  pkg/api/core/types.pb.go
  ui/lib/api/core/types.pb.ts
Labels: enhancement

#2200 Fix getting a helm release's inventory when using targetNamespace
  core/server/helm_release.go
Labels: bug

#2191 Fixes an issue where initial filter is set to the initial data
  .proxyrc.js
  ui/components/FilterDialog.tsx
  ui/components/FilterableTable.tsx
  ui/components/__tests__/FilterableTable.test.tsx
Labels: bug

#2203 Fix syncing sources
  core/server/internal/adapters.go
  core/server/sync.go
Labels: bug

#2109 Allow filter repos
  pkg/helm/charts.go
  pkg/helm/charts_test.go
Labels: enhancement

#2205 Fix the template for TFTemplate
  cmd/gitops/add/terraform/cmd.go
  pkg/adapters/http.go
  pkg/templates/templates.go
  pkg/templates/templates_test.go
Labels: bug

#2201 Fix listing Events for event types other than Kustomization
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/events.go
  core/server/events_test.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/helmrepository_test.go
  core/server/types/kustomization.go
  core/server/types/kustomization_test.go
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/EventsTable.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/SourceLink.tsx
  ui/hooks/events.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
Labels: bug

#2202 add username and apssword cli auth to enterprise endpoint
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/add/cmd.go
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/add/terraform/cmd.go
  cmd/gitops/delete/clusters/cmd.go
  cmd/gitops/delete/cmd.go
  cmd/gitops/get/clusters/cmd.go
  cmd/gitops/get/clusters/cmd_test.go
  cmd/gitops/get/cmd.go
  cmd/gitops/get/credentials/cmd.go
  cmd/gitops/get/profiles/cmd.go
  cmd/gitops/get/templates/cmd.go
  cmd/gitops/root/cmd.go
  cmd/gitops/update/cmd.go
  cmd/gitops/update/profiles/profiles.go
  pkg/adapters/http.go
  pkg/adapters/http_test.go
  pkg/templates/templates_test.go
Labels: exclude from release notes

#2198 ui: Use namespaces for finding sources
  ui/components/SourceDetail.tsx
Labels: bug

#2206 Fix snyk, fix build
  .github/snyk_delta_all_projects.sh
  .github/workflows/pr.yaml
  website/package-lock.json
  website/yarn.lock
Labels: exclude from release notes

#2208 Reorganize Detail Pages
  ui/components/AutomationDetail.tsx
  ui/components/DetailTitle.tsx
  ui/components/Icon.tsx
  ui/components/InfoList.tsx
  ui/components/PageStatus.tsx
  ui/components/SourceDetail.tsx
  ui/components/SyncButton.tsx
Labels: ui

#2214 Auto-update UI snapshots
  .github/workflows/prepare-release.yaml
  ui/components/__tests__/FilterableTable.test.tsx
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
Labels: exclude from release notes

#2210 Rename GitopsTemplate to GitOpsTemplate
  cmd/gitops/add/terraform/cmd.go
  pkg/adapters/http.go
  pkg/templates/templates.go
  pkg/templates/templates_test.go
Labels: enhancement

#2181 Removed extra port mappings from kind config in installation guide
  website/docs/cluster-management/cluster-api-providers.mdx
  website/docs/cluster-management/managing-existing-clusters.mdx
  website/docs/cluster-management/provider-identities.mdx
  website/docs/enterprise/intro.md
  website/docs/installation.mdx
  website/versioned_docs/version-0.8.0/cluster-management/cluster-api-providers.mdx
  website/versioned_docs/version-0.8.0/cluster-management/managing-existing-clusters.mdx
  website/versioned_docs/version-0.8.0/cluster-management/provider-identities.mdx
  website/versioned_docs/version-0.8.0/enterprise/intro.md
  website/versioned_docs/version-0.8.0/installation.mdx
Labels: documentation, exclude from release notes

#2230 parameterize dev image repository so that we can run Tilt with a remote cluster
  Tiltfile
Labels: exclude from release notes, team-denim

#2235 Tilt: Fixed default value for local dev
  Tiltfile
Labels: exclude from release notes, team-denim

#2238 Fix logging on cluster connection error
  core/clustersmngr/factory.go
Labels: exclude from release notes

#2185 Return Available Versions for Profiles in descending order
  go.mod
  pkg/helm/charts.go
  pkg/helm/charts_test.go
  pkg/helm/testdata/invalid-versions/index.yaml
  pkg/helm/testdata/with_profiles/index.yaml
Labels: enhancement

#2232 update `get clusters` to use the new endpoint
  README.md
  pkg/adapters/http.go
  pkg/adapters/http_test.go
  pkg/adapters/testdata/clusters.json
  pkg/clusters/clusters.go
  pkg/clusters/clusters_test.go
Labels: enhancement

#2242 Improve cluster middleware error message.
  core/clustersmngr/middleware.go
Labels: exclude from release notes

#2227 List and get terraform and capi templates
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/add/clusters/cmd_test.go
  cmd/gitops/add/terraform/cmd.go
  cmd/gitops/get/cmd.go
  cmd/gitops/get/credentials/cmd.go
  cmd/gitops/get/templates/cmd.go
  cmd/gitops/get/templates/terraform/cmd.go
  cmd/gitops/get/templates/terraform/cmd_test.go
  pkg/adapters/http.go
  pkg/adapters/http_test.go
  pkg/adapters/testdata/rendered_template_capi.json
  pkg/adapters/testdata/rendered_template_gitops.json
  pkg/adapters/testdata/single_capi_template.json
  pkg/adapters/testdata/single_terraform_template.json
  pkg/capi/capi.go
  pkg/capi/capi_test.go
  pkg/templates/templates.go
  pkg/templates/templates_test.go
Labels: enhancement, team/pitch-black

#2245 ui: Display object Kinds properly
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/ConditionsTable.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/SourceLink.tsx
  ui/components/SourcesTable.tsx
  ui/lib/utils.ts
Labels: ui

#2247 Throw an error on any number of ESLint warnings.
  package.json
  ui/components/DetailTitle.tsx
Labels: ui, team-denim
