Repository weaveworks/weave-gitops, pull requests merged in 2022-01, with the labels that each got.

#1261 Fix for image-spec vuln
  go.mod
  go.sum
Labels: exclude from release notes, ci

#1141 1002 cluster association
  cmd/gitops/install/cmd.go
  pkg/git/git.go
  pkg/kube/kube.go
  pkg/kube/kubefakes/fake_kube.go
  pkg/kube/kubehttp.go
  pkg/models/cluster.go
  pkg/services/applier/applier.go
  pkg/services/automation/automation_test.go
  pkg/services/automation/cluster_generator.go
  pkg/services/automation/generator.go
  pkg/services/gitopswriter/gitopswriter.go
  pkg/services/gitopswriter/writer_add_test.go
  pkg/services/gitopswriter/writer_install_test.go
  test/acceptance/test/install_tests.go
  test/acceptance/test/utils.go
  test/integration/server/add_test.go
  test/integration/server/helpers/helpers.go
  test/integration/server/remove_test.go
Labels: enhancement

#1272 Fix lint issues on CI
  test/acceptance/test/install_tests.go
Labels: exclude from release notes

#1249 Avoid uploading key in public repos
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  test/acceptance/test/add_tests.go
Labels: bug

#1265 Navigate to gitlab merge requests on app add
  ui/pages/ApplicationAdd.tsx
Labels: bug

#1267 Fixes Polling Errors on Remove Page
  pkg/server/server.go
  ui/lib/types.ts
  ui/pages/ApplicationRemove.tsx
Labels: ui

#1274 Add brew back into release
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: exclude from release notes

#1275 Validate credentials on `AddApplication` page
  README.md
  api/applications/applications.proto
  api/applications/applications.swagger.json
  pkg/api/applications/applications.pb.go
  pkg/api/applications/applications.pb.gw.go
  pkg/api/applications/applications_grpc.pb.go
  pkg/server/middleware/middleware.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/services/auth/auth.go
  pkg/services/auth/authfakes/fake_github_auth_client.go
  pkg/services/auth/authfakes/fake_gitlab_auth_client.go
  pkg/services/auth/github.go
  pkg/services/auth/github_test.go
  pkg/services/auth/gitlab.go
  pkg/services/auth/gitlab_test.go
  pkg/services/auth/internal/gitlab.go
  ui/components/Button.tsx
  ui/hooks/__tests__/auth.test.tsx
  ui/hooks/applications.ts
  ui/hooks/auth.ts
  ui/hooks/common.ts
  ui/lib/api/applications/applications.pb.ts
  ui/lib/test-utils.tsx
  ui/pages/ApplicationAdd.tsx
Labels: ui

#1268 Add WithAuth middleware
  cmd/gitops/root/cmd.go
  cmd/gitops/ui/cmd.go
  cmd/gitops/ui/run/cmd.go
  go.mod
  go.sum
  pkg/server/auth/auth.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/jwt.go
  pkg/server/auth/jwt_test.go
  pkg/server/auth/server.go
  pkg/server/handler.go
  pkg/testutils/testutils.go
Labels: exclude from release notes

#1282 Refresh AppDetail on Sync
  ui/pages/ApplicationDetail.tsx
Labels: ui

#1283 Remove Polling Message on Applications Page
  ui/components/PollingIndicator.tsx
  ui/pages/Applications.tsx
Labels: ui

#1277 Adds a layer field to the profiles response
  api/profiles/profiles.proto
  api/profiles/profiles.swagger.json
  pkg/api/profiles/profiles.pb.go
  pkg/helm/charts.go
  pkg/helm/charts_test.go
  pkg/helm/testdata/with_profiles/index.yaml
  ui/lib/api/profiles/profiles.pb.ts
Labels: enhancement

#1289 Disable checkpoint for all CI jobs
  .github/actions/run-acceptance-test/action.yml
  .github/workflows/deploy.yml
  .github/workflows/nightly.yaml
  test/acceptance/README.md
Labels: exclude from release notes

#1292 Refactor ListApplications to create fetcher at the time of the request
  pkg/server/auth/auth.go
  pkg/server/config_getter.go
  pkg/server/config_gettter_test.go
  pkg/server/handler.go
  pkg/server/server.go
  pkg/server/server_options.go
  pkg/server/server_test.go
  pkg/server/suite_test.go
  test/integration/server/suite_test.go
Labels: exclude from release notes

#1293 Fixes version reported by the `gitops` binary in the `wego-app` docker image in a tagged release
  .github/workflows/release.yaml
Labels: bug

#1192 Added `gitops check --pre` command
  cmd/gitops/check/cmd.go
  cmd/gitops/root/cmd.go
  go.mod
  pkg/flux/flux.go
  pkg/flux/fluxfakes/fake_flux.go
  pkg/kube/kube.go
  pkg/kube/kubefakes/fake_kube.go
  pkg/kube/kubehttp.go
  pkg/services/check/check.go
  pkg/services/check/check_suite_test.go
  pkg/services/check/check_test.go
  pkg/services/gitops/install.go
  pkg/services/gitops/install_test.go
  test/acceptance/test/add_tests.go
  test/acceptance/test/utils.go
Labels: enhancement

#1279 Extends Nav height to match Content
  ui/components/Layout.tsx
  ui/components/Page.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
Labels: ui

#1297 Fixes upgrade command
  README.md
  cmd/gitops/upgrade/cmd.go
  go.mod
  go.sum
  pkg/git/git.go
  pkg/git/gitfakes/fake_git.go
  pkg/git/gogit.go
  pkg/git/gogit_test.go
  pkg/server/profiles.go
  pkg/services/automation/automation_test.go
  pkg/services/automation/cluster_generator.go
  pkg/upgrade/upgrade.go
Labels: exclude from release notes

#1296 Update theme, title & button components and lib exports
  ui/components/Button.tsx
  ui/components/Icon.tsx
  ui/components/Page.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/index.ts
  ui/lib/theme.ts
  ui/pages/ApplicationDetail.tsx
  ui/pages/Applications.tsx
  ui/typedefs/styled.d.ts
Labels: exclude from release notes

#1309 Upgrades to a ggp w/ the on-prem-gitlab fix
  go.mod
  go.sum
  pkg/services/automation/cluster_generator.go
  pkg/upgrade/upgrade.go
Labels: exclude from release notes

#1312 Make docker builds faster
  .dockerignore
  Dockerfile
  tools/download-deps.sh
Labels: exclude from release notes

#1308 Include weave-gitops in resources managed by weave-gitops
  pkg/services/automation/automation_test.go
  pkg/services/automation/cluster_generator.go
Labels: exclude from release notes

#1300 Links to commits open new tab
  ui/components/CommitsTable.tsx
  ui/components/Link.tsx
Labels: ui

#1288 Watch and cache helmcharts
  cmd/gitops-server/main.go
  cmd/gitops/ui/run/cmd.go
  go.mod
  go.sum
  pkg/helm/charts.go
  pkg/helm/charts_test.go
  pkg/helm/helmfakes/fake_helm_repo_manager.go
  pkg/helm/watcher/cache/cache.go
  pkg/helm/watcher/cache/cache_test.go
  pkg/helm/watcher/cache/cachefakes/fake_cache.go
  pkg/helm/watcher/controller/artifact_update_predicate.go
  pkg/helm/watcher/controller/artifact_update_predicate_test.go
  pkg/helm/watcher/controller/delete_predicate.go
  pkg/helm/watcher/controller/delete_predicate_test.go
  pkg/helm/watcher/controller/helm_watcher.go
  pkg/helm/watcher/controller/helm_watcher_test.go
  pkg/helm/watcher/server.go
  pkg/server/handler.go
  pkg/server/profiles.go
  pkg/server/profiles_test.go
  pkg/server/server.go
Labels: enhancement, team/pitch-black

#1307 Refactor application endpoints to get `client` at the time of the request
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/suite_test.go
  test/integration/server/suite_test.go
Labels: exclude from release notes

#1227 add `gitops get profiles` command
  cmd/gitops/get/cmd.go
  cmd/gitops/get/profiles/cmd.go
  cmd/gitops/ui/run/cmd.go
  go.mod
  pkg/server/server.go
  pkg/services/profiles/get.go
  pkg/services/profiles/get_test.go
  pkg/services/profiles/profiles_suite_test.go
  test/acceptance/test/profiles_test.go
Labels: enhancement, profiles-improvement

#1315 Reformat add app help text
  cmd/gitops/add/app/cmd.go
Labels: bug

#1322 Fix cache value being overwritten
  pkg/helm/watcher/controller/helm_watcher.go
  pkg/helm/watcher/controller/helm_watcher_test.go
Labels: bug, team/pitch-black

#1301 Add deploy key for public repo
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/delete/clusters/cmd.go
  cmd/gitops/install/cmd.go
  cmd/internal/provider_test.go
  pkg/flux/flux_test.go
  pkg/gitproviders/provider_org_test.go
  pkg/gitproviders/provider_user_test.go
  pkg/gitproviders/repo_url.go
  pkg/gitproviders/repo_url_test.go
  pkg/server/internal/provider_test.go
  pkg/server/server.go
  pkg/services/app/add.go
  pkg/services/app/commit.go
  pkg/services/applicationv2/fetcher.go
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  pkg/services/automation/automation_test.go
  pkg/services/automation/generator.go
  pkg/services/factory.go
  pkg/services/gitops/install.go
  pkg/services/gitopswriter/writer_add_test.go
  pkg/upgrade/upgrade.go
  test/acceptance/test/utils.go
  test/integration/server/add_test.go
Labels: bug

#1324 Updated version on package.json and package-lock.json files
  package-lock.json
  package.json
Labels: exclude from release notes

#1325 Temporarily remove brew
  .goreleaser.yml
Labels: exclude from release notes

#1314 Fix flaky unit test
  go.mod
  go.sum
  pkg/services/auth/github_test.go
Labels: exclude from release notes

#1286 Fix nightly tests and refactor add tests
  .github/workflows/nightly.yaml
  test/acceptance/test/add_tests.go
Labels: exclude from release notes

#1326 Updated weave-gitops version on curl command in README.md
  README.md
Labels: exclude from release notes

#1284 Refactor install
  cmd/gitops/install/cmd.go
  manifests/manifests.go
  manifests/manifests_test.go
  package-lock.json
  package.json
  pkg/models/manifest.go
  pkg/models/manifest_test.go
  pkg/models/manifests_suite_test.go
  pkg/services/app/add.go
  pkg/services/applier/applier.go
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  pkg/services/automation/automation_test.go
  pkg/services/automation/cluster_generator.go
  pkg/services/automation/generator.go
  pkg/services/gitops/gitops_suite_test.go
  pkg/services/gitops/install.go
  pkg/services/gitops/install_test.go
  pkg/services/gitops/uninstall.go
  pkg/services/gitops/uninstall_test.go
  pkg/services/gitopswriter/gitopswriter.go
  pkg/services/gitopswriter/writer_install_test.go
  pkg/services/gitrepo/service.go
  pkg/services/install/install.go
  pkg/services/install/install_suite_test.go
  pkg/services/install/install_test.go
  pkg/upgrade/upgrade.go
  test/acceptance/test/install_tests.go
  test/integration/server/add_test.go
Labels: enhancement

#1321 Adds Sorting to Data Table
  ui/components/CommitsTable.tsx
  ui/components/DataTable.tsx
  ui/components/Icon.tsx
  ui/components/__tests__/DataTable.test.tsx
  ui/components/__tests__/__snapshots__/CommitsTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/stories/DataTable.stories.tsx
Labels: ui

#1343 Re-disable GitHub auth flow tests
  pkg/services/auth/github_test.go
Labels: exclude from release notes

#1328 Add missing roles for the helm watcher
  manifests/manifests_test.go
  manifests/wego-app/helm_watcher_role.yaml.tpl
  manifests/wego-app/helm_watcher_role_binding.yaml.tpl
  pkg/helm/watcher/server.go
  pkg/services/gitops/uninstall.go
  pkg/services/gitops/uninstall_test.go
  test/acceptance/test/profiles_test.go
Labels: bug, team/pitch-black

#1336 Change nightly tests and add weekly tests
  .github/workflows/nightly.yaml
  test/acceptance/test/add_tests.go
  test/acceptance/test/scripts/reset-wego.sh
Labels: exclude from release notes

#1341 Fix flaky test by disabling Prometheus metrics
  pkg/testutils/testutils.go
Labels: exclude from release notes

#1346 Use Makefile job for linter and update package.json before release
  Makefile
  package-lock.json
  package.json
  pkg/server/suite_test.go
  test/integration/server/add_test.go
  test/integration/server/remove_test.go
  test/integration/server/suite_test.go
  tools/download-deps.sh
Labels: exclude from release notes

#1345 Get kube client during HTTP request
  cmd/gitops/add/app/cmd.go
  cmd/gitops/app/status/cmd.go
  cmd/gitops/beta/cmd/add/app.go
  cmd/gitops/beta/cmd/install.go
  cmd/gitops/delete/app/cmd.go
  cmd/gitops/get/app/cmd.go
  cmd/gitops/get/commits/cmd.go
  cmd/gitops/install/cmd.go
  cmd/gitops/resume/app/cmd.go
  cmd/gitops/suspend/app/cmd.go
  cmd/gitops/upgrade/cmd.go
  go.sum
  pkg/server/config_getter.go
  pkg/server/server.go
  pkg/server/server_options.go
  pkg/server/server_test.go
  pkg/server/suite_test.go
  pkg/services/factory.go
  pkg/services/factory_test.go
  pkg/services/servicesfakes/fake_factory.go
  test/integration/server/remove_test.go
  test/integration/server/suite_test.go
Labels: exclude from release notes

#1347 Add Background
  ui/components/Layout.tsx
  ui/images/General-backgroundok.png
  ui/lib/theme.ts
Labels: ui

#1339 Validate app naming using IsDNS1123Label from k8s
  cmd/gitops/add/app/cmd.go
  pkg/models/manifest.go
  pkg/models/manifest_test.go
  pkg/services/app/add.go
  pkg/services/app/add_test.go
Labels: enhancement

#1355 Only run tests when PRing to main
  .github/workflows/test.yml
Labels: exclude from release notes

#1356 Adds some new endpoint test coverage and filtering logic
  .github/workflows/scan.yaml
  .gitignore
  core/server/e2e_test.go
  core/server/kustomization.go
  core/server/kustomization_test.go
  core/server/sources.go
  core/server/types/app.go
  core/server/types/gitrepository.go
  core/server/types/kustomization.go
  pkg/services/auth/gitlab.go
Labels: exclude from release notes

#1353 Update profile endpoints to request a `client.Client` during an HTTP request
  cmd/gitops-server/main.go
  cmd/gitops/cmderrors/errors.go
  cmd/gitops/ui/run/cmd.go
  cmd/gitops/ui/run/cmd_test.go
  pkg/server/profiles.go
  pkg/server/profiles_test.go
Labels: exclude from release notes

#1348 Add tilt.dev support for local development
  .dockerignore
  .gitignore
  .proxyrc
  Dockerfile
  Makefile
  README.md
  Tiltfile
  dev.dockerfile
  tools/download-deps.sh
  tools/kind-with-registry.sh
  tools/wego-app-dev.yaml
Labels: enhancement

#1350 Fix readme version number
  README.md
Labels: exclude from release notes

#1352 Initial work implementing HelmRepository to the API
  api/app/apps.proto
  api/app/apps.swagger.json
  api/app/source.proto
  core/server/kustomization.go
  core/server/sources.go
  core/server/sources_test.go
  core/server/types/helmrepository.go
  pkg/api/app/apps.pb.go
  pkg/api/app/apps.pb.gw.go
  pkg/api/app/apps_grpc.pb.go
  pkg/api/app/flux.pb.go
  pkg/api/app/source.pb.go
  pkg/api/applications/applications.pb.go
  pkg/api/profiles/profiles.pb.go
  ui/lib/api/app/apps.pb.ts
  ui/lib/api/app/source.pb.ts
Labels: enhancement

#1317 Add notifications if a new profile version is available
  cmd/gitops-server/main.go
  cmd/gitops/ui/run/cmd.go
  pkg/helm/watcher/cache/cache.go
  pkg/helm/watcher/cache/cache_test.go
  pkg/helm/watcher/cache/cachefakes/fake_cache.go
  pkg/helm/watcher/controller/controllerfakes/fake_event_recorder.go
  pkg/helm/watcher/controller/helm_watcher.go
  pkg/helm/watcher/controller/helm_watcher_test.go
  pkg/helm/watcher/server.go
Labels: enhancement, team/pitch-black

#1329 Report correct version when building docker image on-release
  .github/workflows/release.yaml
Labels: exclude from release notes

#1366 Added prototype endpoints to Add and List helmcharts
  api/app/apps.proto
  api/app/apps.swagger.json
  api/app/source.proto
  core/server/kustomization.go
  core/server/sources.go
  core/server/sources_test.go
  core/server/types/gitrepository.go
  core/server/types/helmchart.go
  core/server/types/helmrepository.go
  core/server/types/kustomization.go
  core/server/types/utils.go
  core/server/utils.go
  pkg/api/app/apps.pb.go
  pkg/api/app/apps.pb.gw.go
  pkg/api/app/apps_grpc.pb.go
  pkg/api/app/source.pb.go
  ui/lib/api/app/apps.pb.ts
  ui/lib/api/app/source.pb.ts
Labels: enhancement

#1370 Fix nightly syntax
  .github/workflows/nightly.yaml
Labels: exclude from release notes

#1365 Add initial UI components for v2 prototype
  .github/workflows/v2.yml
  Makefile
  Tiltfile
  api/app/kustomize.swagger.json
  api/v1alpha2/application_types.go
  manifests/crds/wego.weave.works_apps.yaml
  manifests/crds/wego.weave.works_apps2.yaml
  package-lock.json
  package.json
  pkg/api/applications/applications.pb.go
  pkg/api/profiles/profiles.pb.go
  ui/App.tsx
  ui/components/AddAppForm.tsx
  ui/components/AddGitRepoForm.tsx
  ui/components/AddKustomizationForm.tsx
  ui/components/ErrorPage.tsx
  ui/components/FancyCard.tsx
  ui/components/Form.tsx
  ui/components/FormCheckbox.tsx
  ui/components/FormInput.tsx
  ui/components/FormSelect.tsx
  ui/components/Icon.tsx
  ui/components/Layout.tsx
  ui/components/Link.tsx
  ui/components/Page.tsx
  ui/components/Spacer.tsx
  ui/components/Text.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/contexts/AppContext.tsx
  ui/hooks/apps.ts
  ui/hooks/kustomizations.ts
  ui/hooks/sources.ts
  ui/images/background.svg
  ui/images/fancy-card-background-blue.svg
  ui/images/fancy-card-background-orange.svg
  ui/images/fancy-card-background.svg
  ui/lib/api/app/kustomize.pb.ts
  ui/lib/images.ts
  ui/lib/types.ts
  ui/lib/utils.ts
  ui/pages/ApplicationDetail.tsx
  ui/pages/v2/AddApp/Wizard.tsx
  ui/pages/v2/AddGitRepo.tsx
  ui/pages/v2/AddKustomization.tsx
  ui/pages/v2/AddSource.tsx
  ui/pages/v2/Application/Application.tsx
  ui/pages/v2/Application/EmptyApplication.tsx
  ui/pages/v2/ApplicationList/AppOnboarding.tsx
  ui/pages/v2/ApplicationList/ApplicationList.tsx
  ui/pages/v2/NewApp.tsx
Labels: exclude from release notes

#1368 Update containerd and runc(go), trim and parcel (UI) for known alerts
  go.mod
  go.sum
  package-lock.json
  package.json
Labels: exclude from release notes
