Repository weaveworks/weave-gitops, pull requests merged in 2022-04, with the labels that each got.

#1854 feat: Use clientpool to Get flux runtime objects
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  ui/components/ReconciledObjectsTable.tsx
  ui/components/ReconciliationGraph.tsx
  ui/hooks/flux.ts
  ui/lib/__tests__/graph.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/graph.ts
  ui/pages/v2/FluxRuntime.tsx
  ui/pages/v2/HelmReleaseDetail.tsx
  ui/pages/v2/KustomizationDetail.tsx
Labels: enhancement, team/mauvelous

#1840 ci: Fix snyk image monitor command
  .github/workflows/pr.yaml
Labels: exclude from release notes

#1864 ci: Fix name of helm chart
  .github/workflows/pr.yaml
Labels: exclude from release notes

#1862 feat: Derive Cluster from Source object response
  api/core/core.swagger.json
  api/core/types.proto
  core/server/sources.go
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/helmchart.go
  core/server/types/helmrepository.go
  pkg/api/core/types.pb.go
  ui/components/SourcesTable.tsx
  ui/lib/api/core/types.pb.ts
  ui/lib/types.ts
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
Labels: enhancement

#1865 fix: Reconciled objects not appearing in a helm release
  ui/hooks/flux.ts
  ui/lib/__tests__/graph.test.ts
  ui/lib/graph.ts
Labels: bug

#1745 Only return deployments with part-of=flux
  .proxyrc.js
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/namespace.go
  package-lock.json
  ui/components/AutomationsTable.tsx
Labels: ui

#1867 Fix merge flow, take 4
  .github/workflows/pr.yaml
Labels: exclude from release notes

#1870 Fix snyk CLI pipeline, take 5
  .github/workflows/pr.yaml
Labels: exclude from release notes

#1871 Add optional annotations to the charts's service
  charts/gitops-server/templates/service.yaml
  charts/gitops-server/values.yaml
Labels: enhancement

#1856 Make core work to embed in into enterprise
  .parcelrc
  package-lock.json
  package.json
  ui/components/AutomationsTable.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/Icon.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/Logo.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/SourceDetail.tsx
  ui/components/SourceLink.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/index.ts
  ui/lib/images.ts
  ui/pages/v2/HelmReleaseDetail.tsx
  ui/pages/v2/KustomizationDetail.tsx
Labels: exclude from release notes

#1873 Remove CLI auth code
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/update/profiles/profiles.go
  cmd/gitops/upgrade/cmd.go
  cmd/internal/handler.go
  cmd/internal/provider.go
  cmd/internal/provider_test.go
  pkg/services/auth/auth.go
  pkg/services/auth/github.go
  pkg/services/auth/github_test.go
  pkg/services/auth/gitlab.go
  pkg/services/auth/gitlab_test.go
  pkg/services/factory.go
Labels: exclude from release notes

#1857 Add nsaccess package to determine if a user "has access" to a namespace
  .proxyrc
  charts/gitops-server/templates/admin-user.yaml
  core/clustersmngr/client.go
  core/clustersmngr/clustersmngr.go
  core/nsaccess/nsaccess.go
  core/nsaccess/nsaccess_test.go
  core/nsaccess/nsaccessfakes/fake_checker.go
  core/server/kustomization_test.go
  core/server/namespace.go
  core/server/namespace_test.go
  core/server/server.go
  core/server/suite_test.go
  pkg/kube/kubehttp.go
  ui/pages/v2/Automations.tsx
Labels: enhancement

#1863 fix: LastUpdatedAt value is always an empty string
  core/server/types/helmrelease.go
  core/server/types/helmrepository.go
  core/server/types/utils.go
Labels: bug

#1881 Update package.json for rc11
  package-lock.json
  package.json
Labels: exclude from release notes

#1883 core/server: Error out if we can't create controller client
  core/server/server.go
  core/server/suite_test.go
Labels: exclude from release notes

#1879 refactor: Remove unused ProtoToSomething functions
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/helmrepository.go
  core/server/types/kustomization.go
  core/server/types/utils.go
Labels: exclude from release notes

#1887 Fix svg loading
  .parcelrc
  ui/components/Icon.tsx
Labels: exclude from release notes

#1869 Adjust filter chip spacing
  ui/components/ChipGroup.tsx
  ui/components/SourcesTable.tsx
  ui/pages/v2/Automations.tsx
Labels: ui

#1793 Added static tls files to helm template
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/values.yaml
  tools/helm-values-dev.yaml
Labels: enhancement

#1891 Remove animation from sign_on screen
  ui/images/SignInBackground.svg
Labels: bug

#1889 Change graph node shape + add status + add cluster name
  api/core/core.swagger.json
  api/core/types.proto
  core/server/fluxruntime.go
  pkg/api/core/types.pb.go
  ui/components/DirectedGraph.tsx
  ui/components/HashRouterTabs.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/LoadingPage.tsx
  ui/components/Page.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/lib/api/core/types.pb.ts
  ui/lib/theme.ts
  ui/typedefs/styled.d.ts
Labels: ui

#1896 Fixes image loading when using UI as a module
  ui/components/Icon.tsx
  ui/components/Logo.tsx
  ui/lib/images.ts
  ui/lib/theme.ts
  ui/pages/SignIn.tsx
Labels: bug

#1897 Fix width and height of Kustomization Detail
  ui/components/KustomizationDetail.tsx
  ui/pages/v2/KustomizationDetail.tsx
Labels: ui

#1898 Fixes a couple of broken images when using UI as a module
  ui/components/ReconciliationGraph.tsx
  ui/index.ts
Labels: exclude from release notes

#1847 update-upgrade-command-to-deal-with-weave-gitops-helm-repo
  pkg/utils/common.go
  pkg/utils/testdata/config.yaml
  pkg/utils/testdata/partial-config.yaml
Labels: enhancement

#1893 final changes to generate a release
  gitops-server.dockerfile
  package-lock.json
  package.json
  tools/update-docs.sh
Labels: enhancement

#1888 feat: Query kustomizations across namespaces for a cluster
  api/core/core.swagger.json
  api/core/types.proto
  core/cache/container.go
  core/cache/container_test.go
  core/cache/namespace.go
  core/cache/namespace_test.go
  core/cache/suite_test.go
  core/clustersmngr/client_test.go
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/middleware.go
  core/server/kustomization.go
  core/server/namespace.go
  core/server/server.go
  core/server/suite_test.go
  core/server/types/namespace.go
  pkg/api/core/types.pb.go
  ui/lib/api/core/types.pb.ts
Labels: enhancement

#1903 feat: Add cross-namespace querying to all listing endpoints
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/helm_release.go
  core/server/helm_release_test.go
  core/server/kustomization_test.go
  core/server/list.go
  core/server/sources.go
  core/server/sources_test.go
  core/server/suite_test.go
Labels: enhancement

#1902 Add automation sync endpoints and UI
  Makefile
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  charts/gitops-server/templates/admin-user.yaml
  core/clustersmngr/client.go
  core/server/internal/adapters.go
  core/server/sync.go
  core/server/sync_test.go
  core/server/types/kustomization.go
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  ui/components/EventsTable.tsx
  ui/components/Flex.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/Page.tsx
  ui/components/PollingIndicator.tsx
  ui/components/SyncButton.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/Flex.test.tsx.snap
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/hooks/automations.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/types.ts
  ui/pages/SignIn.tsx
Labels: enhancement

#1846 V2 restructure
  tools/update-docs.sh
  website/docs/architecture.md
  website/docs/aws-marketplace.md
  website/docs/cli-reference/_category_.json
  website/docs/cluster-management/_category_.json
  website/docs/cluster-management/getting-started.mdx
  website/docs/configuration/_category_.json
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/docs/configuration/tls.md
  website/docs/enterprise/intro.md
  website/docs/enterprise/oidc.mdx
  website/docs/enterprise/tls.mdx
  website/docs/enterprise/upgrading.mdx
  website/docs/examples/_category_.json
  website/docs/examples/sock-shop.md
  website/docs/feedback-and-telemetry.md
  website/docs/getting-started.md
  website/docs/getting-started.mdx
  website/docs/gitops-automation.md
  website/docs/guides/_category_.json
  website/docs/guides/assets/templates/capa-template.yaml
  website/docs/guides/deploying-capa.mdx
  website/docs/help-and-support.md
  website/docs/installation.md
  website/docs/installation.mdx
  website/docs/intro.md
  website/docs/troubleshooting.md
  website/docusaurus.config.js
  website/static/img/dashboard-application-events.png
  website/static/img/dashboard-application-flux.png
  website/static/img/dashboard-application-reconciliation.png
  website/static/img/dashboard-applications-overview.png
  website/static/img/dashboard-applications-with-podinfo.png
  website/static/img/dashboard-flux-runtime.png
  website/static/img/dashboard-login.png
  website/static/img/dashboard-podinfo-details.png
  website/static/img/dashboard-podinfo-suspended.png
  website/static/img/dashboard-podinfo-updated.png
  website/static/img/dashboard-source-flux.png
  website/static/img/dashboard-sources.png
Labels: exclude from release notes

#1895 Make namespace cache mockable when starting server
  cmd/gitops-server/cmd/cmd.go
  core/cache/cachefakes/fake_container.go
  core/cache/container.go
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/clustersmngrfakes/fake_clients_pool.go
  core/server/server.go
  core/server/server_test.go
  core/server/suite_test.go
Labels: exclude from release notes

#1821 Restyle Filter Modal
  ui/components/AutomationsTable.tsx
  ui/components/DataTable.tsx
  ui/components/FilterDialog.tsx
  ui/components/FilterableTable.tsx
  ui/components/Flex.tsx
  ui/components/Footer.tsx
  ui/components/HashRouterTabs.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/Layout.tsx
  ui/components/Page.tsx
  ui/components/SourceDetail.tsx
  ui/components/SourcesTable.tsx
  ui/components/SyncButton.tsx
  ui/components/__tests__/FilterDialog.test.tsx
  ui/components/__tests__/FilterableTable.test.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/lib/theme.ts
  ui/pages/SignIn.tsx
Labels: ui

#1908 Fix Spacing in Page Component
  ui/components/Page.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
Labels: exclude from release notes

#1912 refactor: Make namespace force recache a sync operation
  core/cache/namespace.go
  core/cache/namespace_test.go
  core/server/namespace_test.go
  core/server/suite_test.go
Labels: enhancement

#1914 Update helm chart + CLI release version
  README.md
  charts/gitops-server/Chart.yaml
  charts/gitops-server/values.yaml
Labels: exclude from release notes

#1920 fix: Namespace cach can be called before the first results come back
  core/cache/container.go
  core/cache/namespace.go
  core/cache/namespace_test.go
Labels: bug

#1921 docs: Fix manual download instructions, update readme
  README.md
  tools/update-docs.sh
  website/docs/cli-reference/_category_.json
  website/docs/installation.mdx
Labels: exclude from release notes

#1929 Added missing version prefix. Command was broken.
  website/docs/installation.mdx
Labels: exclude from release notes

#1926 Add Filtering Options
  ui/components/AutomationsTable.tsx
  ui/components/FilterDialog.tsx
  ui/components/FilterableTable.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/FilterableTable.test.tsx
Labels: ui

#1931 Remove flux-system as the default namespace from requests
  ui/components/AddGitRepoForm.tsx
  ui/components/AutomationsTable.tsx
  ui/components/EventsTable.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourcesTable.tsx
  ui/hooks/automations.ts
  ui/hooks/flux.ts
  ui/hooks/sources.ts
  ui/lib/nav.ts
  ui/lib/types.ts
Labels: ui

#1904 Switch to path routing (from hash routing)
  ui/App.tsx
  ui/components/DataTable.tsx
  ui/components/EventsTable.tsx
  ui/components/HashRouterTabs.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/SourceDetail.tsx
  ui/components/SubRouterTabs.tsx
  ui/lib/nav.ts
  ui/pages/v2/KustomizationDetail.tsx
Labels: bug

#1936 Do not delete `.idea` folder on `make clean`
  Makefile
Labels: exclude from release notes

#1935 Populate namespace on automation detail screens
  ui/App.tsx
  ui/components/AutomationsTable.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/SourceLink.tsx
  ui/hooks/automations.ts
  ui/pages/v2/HelmReleaseDetail.tsx
  ui/pages/v2/KustomizationDetail.tsx
Labels: bug

#1937 Improve Filter Animation
  ui/components/FilterDialog.tsx
  ui/components/FilterDialogButton.tsx
  ui/components/FilterableTable.tsx
Labels: ui

#1940 Style Icon Button Hover State
  ui/components/Button.tsx
  ui/components/ChipGroup.tsx
  ui/components/FilterDialogButton.tsx
  ui/components/FilterableTable.tsx
  ui/components/SearchField.tsx
  ui/components/SourcesTable.tsx
  ui/pages/v2/Automations.tsx
Labels: ui

#1941 Stop the testEnv
  core/nsaccess/nsaccess_test.go
Labels: exclude from release notes

#1930 Replace the release process with a workflow
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
  doc/release-process.md
  tools/tag-release
  tools/update-docs.sh
Labels: exclude from release notes

#1932 Redirect to sign in on AJAX requests
  pkg/server/auth/server.go
  ui/App.tsx
  ui/contexts/AppContext.tsx
  ui/contexts/AuthContext.tsx
  ui/contexts/CoreClientContext.tsx
  ui/hooks/automations.ts
  ui/hooks/events.ts
  ui/hooks/flux.ts
  ui/hooks/sources.ts
  ui/pages/SignIn.tsx
Labels: bug

#1945 Make sourceRef namespace optional
  ui/components/AutomationsTable.tsx
Labels: bug

#1944 Docs fixes
  website/docs/cluster-management/getting-started.mdx
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/docs/getting-started.mdx
  website/docs/guides/deploying-capa.mdx
  website/docs/installation.mdx
  website/docusaurus.config.js
  website/versioned_docs/version-0.7.0/cluster-management/getting-started.mdx
  website/versioned_docs/version-0.7.0/configuration/securing-access-to-the-dashboard.mdx
  website/versioned_docs/version-0.7.0/getting-started.mdx
  website/versioned_docs/version-0.7.0/guides/deploying-capa.mdx
  website/versioned_docs/version-0.7.0/installation.mdx
Labels: exclude from release notes

#1922 Introducing limited user
  Tiltfile
  cmd/gitops-server/cmd/cmd.go
  tools/charts/dev/.helmignore
  tools/charts/dev/Chart.yaml
  tools/charts/dev/templates/_helpers.tpl
  tools/charts/dev/templates/limited-user.yaml
  tools/charts/dev/values.yaml
Labels: enhancement

#1950 Fix HelmRelease nav and styling
  ui/App.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/pages/v2/HelmReleasePage.tsx
  ui/pages/v2/KustomizationPage.tsx
Labels: bug

#1951 Add dedicated components for core details functionality, export flux hook
  ui/components/BucketDetail.tsx
  ui/components/FluxRuntime.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/index.ts
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/FluxRuntime.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
Labels: exclude from release notes

#1958 update docs based on sync requirements
  website/docs/getting-started.mdx
  website/versioned_docs/version-0.7.0/getting-started.mdx
Labels: exclude from release notes

#1954 Remove width constraints from data tables to allow for horizontal scrolling
  ui/components/AutomationsTable.tsx
  ui/components/ConditionsTable.tsx
  ui/components/DataTable.tsx
  ui/components/EventsTable.tsx
  ui/components/FilterDialog.tsx
  ui/components/FilterableTable.tsx
  ui/components/Layout.tsx
  ui/components/Page.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
Labels: ui

#1924 Run release process as weave-gitops-bot, and re-enable homebrew tap generation
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
  .goreleaser.brew.yml
  .goreleaser.yml
Labels: exclude from release notes

#1938 Kustomizations pagination
  api/core/core.proto
  api/core/core.swagger.json
  core/server/kustomization.go
  core/server/pagination.go
  core/server/pagination_test.go
  core/server/utils.go
  pkg/api/core/core.pb.go
  ui/lib/api/core/core.pb.ts
Labels: enhancement

#1974 release: Fix condition to skip brew tap generation
  .github/workflows/release.yaml
Labels: exclude from release notes

#1972 ui: Make CoreClientContext monkeypatch work
  ui/contexts/CoreClientContext.tsx
  ui/contexts/__tests__/CoreClientContext.test.tsx
Labels: bug

#1973 Fix sub page navigation
  ui/App.tsx
  ui/components/DataTable.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
Labels: bug

#1978 Final* small release process changes
  .github/workflows/prepare-release.yaml
  doc/release-process.md
Labels: exclude from release notes

#1963 ref: Remove kube.Kube interface and implementation
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/update/profiles/profiles.go
  cmd/gitops/upgrade/cmd.go
  core/server/fluxruntime_test.go
  pkg/kube/client_getter.go
  pkg/kube/kube.go
  pkg/kube/kube_suite_test.go
  pkg/kube/kubefakes/fake_kube.go
  pkg/kube/kubefakes/fake_kube_getter.go
  pkg/kube/kubehttp.go
  pkg/kube/kubehttp_test.go
  pkg/server/server.go
  pkg/server/server_options.go
  pkg/server/server_test.go
  pkg/server/suite_test.go
  pkg/services/factory.go
  pkg/services/factory_test.go
  pkg/services/servicesfakes/fake_factory.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: enhancement

#1984 Move javascript out of the server binary
  Makefile
  Tiltfile
  cmd/gitops-server/cmd/cmd.go
  gitops-server.dockerfile
  package.json
Labels: exclude from release notes

#1986 ref: delete gitproviders/cache
  pkg/gitproviders/README.md
  pkg/gitproviders/cache/commits.yaml
  pkg/gitproviders/cache/deploy_key_org.yaml
  pkg/gitproviders/cache/deploy_key_user.yaml
  pkg/gitproviders/cache/get_user_repo_info.yaml
  pkg/gitproviders/cache/gitlab_repo_group_exists.yaml
  pkg/gitproviders/cache/gitlab_repo_personal_exists.yaml
  pkg/gitproviders/cache/pull_requests.yaml
  pkg/gitproviders/cache/repo_org_exists.yaml
  pkg/gitproviders/cache/repo_personal_exists.yaml
Labels: exclude from release notes, team/mauvelous

#1948 Better bcrypt use
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/admin-user.yaml
  charts/gitops-server/values.yaml
  website/docs/getting-started.mdx
  website/docs/installation.mdx
  website/versioned_docs/version-0.7.0/getting-started.mdx
  website/versioned_docs/version-0.7.0/installation.mdx
Labels: documentation, enhancement

#1989 Update auth check
  ui/contexts/AuthContext.tsx
  ui/contexts/CoreClientContext.tsx
Labels: exclude from release notes

#1988 Fix dev chart values
  tools/helm-values-dev.yaml
Labels: bug

#1979 Add Select All box to filter bar categories
  ui/components/FilterDialog.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/FilterableTable.test.tsx
Labels: ui

#1987 refactor: clean up `pkg/models`
  cmd/gitops/add/profiles/cmd.go
  pkg/models/cluster.go
  pkg/models/manifests_suite_test.go
  pkg/names/names.go
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  pkg/services/profiles/add.go
  pkg/services/profiles/add_test.go
  pkg/services/profiles/update.go
  pkg/services/profiles/update_test.go
  pkg/upgrade/upgrade.go
Labels: exclude from release notes, team/mauvelous

#1996 Fix mis-spelling of HelmRelease for stable documentation
  website/versioned_docs/version-0.7.0/installation.mdx
Labels: exclude from release notes

#1997 docs: Copy the changes from #1985 to the unstable docs
  website/docs/getting-started.mdx
  website/versioned_docs/version-0.7.0/getting-started.mdx
Labels: exclude from release notes

#1995 refactor: Use the camelCase fieds in all proto files
  api/core/core.proto
  api/core/types.proto
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
Labels: enhancement

#1999 refactor: Tidy up server tests a little
  pkg/server/server_suite_test.go
  pkg/server/server_test.go
Labels: exclude from release notes, team/mauvelous

#1993 Align titles, fix fonts, and link logo to applications page
  ui/components/InfoList.tsx
  ui/components/Layout.tsx
  ui/components/Logo.tsx
  ui/components/Page.tsx
  ui/components/PageStatus.tsx
  ui/components/SubRouterTabs.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/Logo.test.tsx
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
Labels: ui

#2004 Fix empty reconciled object tables
  ui/components/KustomizationDetail.tsx
Labels: ui

#2007 Remove unused code in pkg/utils
  go.mod
  go.sum
  pkg/utils/common.go
  pkg/utils/common_test.go
Labels: exclude from release notes

#1952 Cross cluster querying
  cmd/gitops-server/cmd/cmd.go
  core/clustersmngr/client.go
  core/clustersmngr/client_test.go
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/clustersmngrfakes/fake_clients_factory.go
  core/clustersmngr/factory.go
  core/clustersmngr/factory_caches.go
  core/clustersmngr/factory_caches_test.go
  core/clustersmngr/factory_test.go
  core/clustersmngr/fetcher/single.go
  core/clustersmngr/fetcher/single_test.go
  core/clustersmngr/middleware.go
  core/clustersmngr/middleware_test.go
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/helm_release.go
  core/server/helm_release_test.go
  core/server/kustomization.go
  core/server/kustomization_test.go
  core/server/list.go
  core/server/pagination.go
  core/server/pagination_test.go
  core/server/server.go
  core/server/server_test.go
  core/server/sources.go
  core/server/sources_test.go
  core/server/suite_test.go
  core/server/utils.go
  go.mod
  go.sum
  pkg/server/handler.go
Labels: enhancement

#2005 Add missing url in getting started guide
  website/docs/getting-started.mdx
  website/versioned_docs/version-0.7.0/getting-started.mdx
Labels: documentation, exclude from release notes

#2014 Allow exclusion of issue from release notes via the "exclude from release notes" label
  .github/changelog/changelog_configuration.json
Labels: bug

#2012 Convert ssh urls to http
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
Labels: ui

#2022 chore: Alert Slack when CI fails on main
  .github/workflows/pr.yaml
Labels: exclude from release notes, team/mauvelous

#1998 Refactor auth service tests
  pkg/services/auth/auth.go
  pkg/services/auth/auth_suite_test.go
  pkg/services/auth/auth_test.go
  pkg/services/auth/github.go
  pkg/services/auth/github_test.go
  pkg/services/auth/gitlab_test.go
  pkg/services/auth/internal/gitlab_test.go
  pkg/services/auth/internal/verifier.go
  pkg/services/auth/internal/verifier_test.go
  pkg/services/auth/jwt_test.go
  pkg/services/factory.go
Labels: exclude from release notes, team/mauvelous

#2024 Cleaning up packages after cross-cluster query changes
  cmd/gitops-server/cmd/cmd.go
  core/cache/cachefakes/fake_cache.go
  core/cache/cachefakes/fake_container.go
  core/cache/container.go
  core/cache/container_test.go
  core/cache/fake_test.go
  core/cache/namespace.go
  core/cache/namespace_test.go
  core/cache/suite_test.go
  core/clustersmngr/middleware.go
  core/clustersmngr/middleware_test.go
  core/server/fluxruntime.go
  core/server/kustomization.go
  core/server/namespace.go
  core/server/namespace_test.go
  core/server/server.go
  core/server/suite_test.go
  pkg/server/handler.go
Labels: exclude from release notes

#2028 Fix: getting started missing admin user values
  website/docs/getting-started.mdx
  website/versioned_docs/version-0.7.0/getting-started.mdx
Labels: exclude from release notes

#1967 Update all Flux (related) dependencies
  core/clustersmngr/client_test.go
  core/server/internal/adapters.go
  core/server/kustomization_test.go
  core/server/sources.go
  core/server/sources_test.go
  core/server/sync_test.go
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/helmchart.go
  core/server/types/helmrepository.go
  core/server/types/kustomization.go
  core/server/types/utils.go
  go.mod
  go.sum
  pkg/helm/charts.go
  pkg/helm/charts_test.go
  pkg/helm/helmfakes/fake_helm_repo_manager.go
  pkg/helm/releases.go
  pkg/helm/releases_test.go
  pkg/helm/testdata/parsing/profile.yaml
  pkg/helm/watcher/controller/artifact_update_predicate.go
  pkg/helm/watcher/controller/artifact_update_predicate_test.go
  pkg/helm/watcher/controller/delete_predicate.go
  pkg/helm/watcher/controller/delete_predicate_test.go
  pkg/helm/watcher/controller/helm_watcher.go
  pkg/helm/watcher/controller/helm_watcher_test.go
  pkg/helm/watcher/server.go
  pkg/kube/kubehttp.go
  pkg/server/profiles.go
  pkg/server/profiles_test.go
  pkg/testutils/testutils.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/utils/testdata/config.yaml
  pkg/utils/testdata/partial-config.yaml
  tools/dependencies.toml
  tools/testcrds/source.toolkit.fluxcd.io_buckets.yaml
  tools/testcrds/source.toolkit.fluxcd.io_gitrepositories.yaml
  tools/testcrds/source.toolkit.fluxcd.io_helmcharts.yaml
  tools/testcrds/source.toolkit.fluxcd.io_helmrepositories.yaml
  website/docs/cluster-management/assets/profiles/profile-repo.yaml
  website/docs/getting-started.mdx
  website/docs/installation.mdx
Labels: enhancement

#2031 chore: Update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: exclude from release notes

#2033 fix: wego-admin unable to view events for weave gitops app
  api/core/core.proto
  api/core/core.swagger.json
  core/server/events.go
  core/server/events_test.go
  pkg/api/core/core.pb.go
  ui/components/EventsTable.tsx
  ui/hooks/events.ts
  ui/lib/api/core/core.pb.ts
Labels: bug

#2037 release: Thread release notes into the PR, too
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
Labels: exclude from release notes

#2040 Waiting the initial load of clusters
  core/clustersmngr/factory.go
Labels: exclude from release notes

#2013 Change doc screenshot to reflect current changes
  website/static/img/dashboard-application-reconciliation.png
Labels: documentation, exclude from release notes

#2044 chart: Remove --helm-repo-namespace from flags
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/deployment.yaml
Labels: exclude from release notes

#2046 fix: HelmChart links from Helm Releases point to an invalid object
  api/core/core.swagger.json
  api/core/types.proto
  core/server/types/helmrelease.go
  pkg/api/core/types.pb.go
  ui/components/HelmReleaseDetail.tsx
  ui/lib/api/core/types.pb.ts
Labels: bug

#2048 Adding testutils methods to delete resources
  core/server/kustomization_test.go
  pkg/testutils/testutils.go
Labels: exclude from release notes

#2052 Deploy new chart and docs for new release
  .github/workflows/release.yaml
  charts/gitops-server/Chart.yaml
  tools/update-docs.sh
  website/docs/installation.mdx
  website/versioned_docs/version-0.8.0/installation.mdx
Labels: exclude from release notes

#2042 Avoid ignoring helmreleases on source detail page
  api/core/core.proto
  api/core/core.swagger.json
  core/server/helm_release.go
  core/server/types/helmrelease.go
  pkg/api/core/core.pb.go
  ui/components/HelmReleaseDetail.tsx
  ui/components/SourceDetail.tsx
  ui/hooks/automations.ts
  ui/lib/api/core/core.pb.ts
Labels: bug
