Repository weaveworks/weave-gitops, pull requests merged in 2022-06, with the labels that each got.

#2257 Support multiline text and auto-wrap long lines in message table cells
  ui/components/AutomationsTable.tsx
  ui/components/EventsTable.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourcesTable.tsx
Labels: ui, team/denim

#2259 release: Don't try to update non-existing CLI installation steps
  tools/update-docs.sh
Labels: exclude from release notes, team/denim

#2261 cli: Remove gitops check --pre flag
  cmd/gitops/check/cmd.go
Labels: bug

#2260 Add Suspend/Resume to the UI
  ui/components/AutomationDetail.tsx
  ui/components/SourceDetail.tsx
  ui/components/SyncButton.tsx
  ui/hooks/flux.ts
Labels: ui

#2140 Adds MultiClusterFetcher instructions to user-guide
  website/docs/assets/example-enterprise-helm.yaml
  website/docs/cluster-management/assets/rbac/wego-admin.yaml
  website/docs/cluster-management/assets/templates/capd-template.yaml
  website/docs/cluster-management/getting-started.mdx
  website/docs/cluster-management/managing-existing-clusters.mdx
  website/docs/guides/assets/templates/capa-template.yaml
  website/docs/installation.mdx
  website/versioned_docs/version-0.8.1/assets/example-enterprise-helm.yaml
  website/versioned_docs/version-0.8.1/cluster-management/assets/rbac/wego-admin.yaml
  website/versioned_docs/version-0.8.1/cluster-management/assets/templates/capd-template.yaml
  website/versioned_docs/version-0.8.1/cluster-management/getting-started.mdx
  website/versioned_docs/version-0.8.1/cluster-management/managing-existing-clusters.mdx
  website/versioned_docs/version-0.8.1/guides/assets/templates/capa-template.yaml
  website/versioned_docs/version-0.8.1/installation.mdx
Labels: enhancement

#2251 use window location to refresh to reset application
  ui/contexts/AuthContext.tsx
  ui/contexts/CoreClientContext.tsx
Labels: bug

#2270 Add raw GetObject view, and use it to display yaml, metadata
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/objects.go
  core/server/objects_test.go
  core/server/types/objects.go
  package-lock.json
  package.json
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/Metadata.tsx
  ui/components/SourceDetail.tsx
  ui/components/SourceLink.tsx
  ui/components/SourcesTable.tsx
  ui/components/YamlView.tsx
  ui/hooks/objects.ts
  ui/lib/__tests__/objects.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/nav.ts
  ui/lib/objects.ts
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
Labels: enhancement

#2263 Expose the API version for all objects over API
  api/core/core.swagger.json
  api/core/types.proto
  core/server/helm_release.go
  core/server/kustomization.go
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/helmrepository.go
  core/server/types/helmrepository_test.go
  core/server/types/kustomization.go
  core/server/types/kustomization_test.go
  pkg/api/core/types.pb.go
  ui/lib/api/core/types.pb.ts
Labels: exclude from release notes, team/denim

#2249 Make nav sticky and adjust logo/top bar height
  ui/components/DirectedGraph.tsx
  ui/components/Layout.tsx
  ui/components/Logo.tsx
  ui/components/Page.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/images/Title.svg
  ui/lib/images.ts
Labels: ui

#2275 Fix frontend build using node 16.15
  .github/workflows/pr.yaml
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
  doc/development-process.md
  package-lock.json
  package.json
Labels: exclude from release notes

#2272 Fix loading icon size inside buttons
  ui/components/Button.tsx
Labels: ui

#2277 Link to Flux resources in the details table for Kustomizations and Helm Releases
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/SourceLink.tsx
  ui/components/SourcesTable.tsx
  ui/lib/nav.ts
  ui/lib/utils.ts
Labels: ui, team/denim

#2273 Add number lines to yaml tab
  ui/components/YamlView.tsx
Labels: ui

#2282 Kustomizations and Helm Releases display images in tables
  ui/components/ReconciledObjectsTable.tsx
  ui/lib/utils.ts
Labels: ui

#2293 Add copyable kubectl get command to yaml tab
  ui/components/AutomationDetail.tsx
  ui/components/Icon.tsx
  ui/components/SourceDetail.tsx
  ui/components/YamlView.tsx
Labels: ui

#2292 Replace `npm ci` with `npm i` in releases
  .github/workflows/prepare-release.yaml
Labels: exclude from release notes

#2294 js: Test that all dependencies are listed, add yaml dependency
  .github/workflows/pr.yaml
  Makefile
  package-lock.json
  package.json
Labels: bug

#2297 Adds multiline and link support to metadata
  ui/components/InfoList.tsx
  ui/components/Metadata.tsx
  ui/components/SourcesTable.tsx
Labels: ui

#2306 Fix the reference error by rolling `yaml` back to the stable version.
  package-lock.json
  package.json
Labels: bug

#2298 Display missing resources from a Kustomization's inventory
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/admin-user-roles.yaml
  charts/gitops-server/values.yaml
  core/server/fluxruntime.go
  core/server/types/kustomization.go
  ui/lib/graph.ts
  website/docs/configuration/user-permissions.mdx
Labels: bug

#2308 Fix invalid URL caused by filters
  ui/components/FilterableTable.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourceDetail.tsx
  ui/components/__tests__/FilterableTable.test.tsx
Labels: ui

#2309 graph: Hide ReplicaSets with zero pods
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
Labels: bug, team/denim

#2314 Fix filtering by name (searching) on Automation details tab
  ui/components/ReconciledObjectsTable.tsx
Labels: ui, team/denim

#2316 2269 Format metadata keys; 2301 Sort metadata key/value pairs by key
  ui/components/InfoList.tsx
  ui/components/Metadata.tsx
  ui/components/__tests__/Metadata.test.tsx
  ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: ui, team/denim

#2296 Add exports and fix unprotected map
  api/core/core.swagger.json
  api/core/types.proto
  buf.lock
  pkg/api/core/types.pb.go
  ui/components/AutomationsTable.tsx
  ui/index.ts
  ui/lib/api/core/types.pb.ts
Labels: bug

#2283 Add Policy Docs
  website/docs/policy/_category_.json
  website/docs/policy/assets/bootstrap/calico-crs-configmap.yaml
  website/docs/policy/assets/bootstrap/calico-crs.yaml
  website/docs/policy/assets/bootstrap/capi-gitops-cluster-bootstrap-config.yaml
  website/docs/policy/assets/profiles/profile-repo.yaml
  website/docs/policy/assets/rbac/wego-admin.yaml
  website/docs/policy/assets/templates/.keep
  website/docs/policy/assets/templates/capd-template.yaml
  website/docs/policy/commit-time-checks.mdx
  website/docs/policy/getting-started.mdx
  website/docs/policy/img/violations-log-detail.png
  website/docs/policy/img/violations-logs.png
  website/docs/policy/img/weave-policies.png
  website/docs/policy/img/weave-policy-profile.png
  website/docs/policy/intro.mdx
  website/docs/policy/weave-policy-profile.mdx
  website/versioned_docs/version-0.8.1/policy/_category_.json
  website/versioned_docs/version-0.8.1/policy/assets/bootstrap/calico-crs-configmap.yaml
  website/versioned_docs/version-0.8.1/policy/assets/bootstrap/calico-crs.yaml
  website/versioned_docs/version-0.8.1/policy/assets/bootstrap/capi-gitops-cluster-bootstrap-config.yaml
  website/versioned_docs/version-0.8.1/policy/assets/profiles/profile-repo.yaml
  website/versioned_docs/version-0.8.1/policy/assets/rbac/wego-admin.yaml
  website/versioned_docs/version-0.8.1/policy/assets/templates/.keep
  website/versioned_docs/version-0.8.1/policy/assets/templates/capd-template.yaml
  website/versioned_docs/version-0.8.1/policy/commit-time-checks.mdx
  website/versioned_docs/version-0.8.1/policy/getting-started.mdx
  website/versioned_docs/version-0.8.1/policy/img/violations-log-detail.png
  website/versioned_docs/version-0.8.1/policy/img/violations-logs.png
  website/versioned_docs/version-0.8.1/policy/img/weave-policies.png
  website/versioned_docs/version-0.8.1/policy/img/weave-policy-profile.png
  website/versioned_docs/version-0.8.1/policy/intro.mdx
  website/versioned_docs/version-0.8.1/policy/weave-policy-profile.mdx
Labels: documentation, exclude from release notes

#2319 ADR 0014 Kubernetes Client API Fairness and Rate Limits
  doc/adr/0014-k8s-client-api-fairness-and-rate-limits.md
Labels: exclude from release notes

#2332 change chart image to chart location
  .github/workflows/chart.yaml
Labels: exclude from release notes, team/denim

#2336 Docs updates
  website/docs/getting-started.mdx
  website/docs/guides/displaying-custom-metadata.mdx
  website/static/img/dashboard-application-events.png
  website/static/img/dashboard-application-flux.png
  website/static/img/dashboard-application-reconciliation.png
  website/static/img/dashboard-application-yaml.png
  website/static/img/dashboard-applications-overview.png
  website/static/img/dashboard-applications-with-podinfo.png
  website/static/img/dashboard-flux-runtime.png
  website/static/img/dashboard-podinfo-details-suspended.png
  website/static/img/dashboard-podinfo-details.png
  website/static/img/dashboard-podinfo-suspended.png
  website/static/img/dashboard-podinfo-updated.png
  website/static/img/dashboard-source-flux.png
  website/static/img/dashboard-sources.png
  website/static/img/metadata-display.png
Labels: documentation, exclude from release notes

#2256 Remove code coverage & embedded package manager
  .github/workflows/pr.yaml
  Makefile
  core/clustersmngr/suite_test.go
  core/server/suite_test.go
  go.mod
  go.sum
  pkg/api/applications/applications.pb.go
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  pkg/api/profiles/profiles.pb.go
  pkg/services/auth/auth_test.go
  tools/dependencies.toml
  tools/download-deps.sh
  tools/functions.sh
  tools/tools.go
Labels: exclude from release notes

#2341 docker: Use cache mounts when building gitops-server
  gitops-server.dockerfile
Labels: exclude from release notes

#2343 release: Don't run make dependencies, don't set flux version
  .github/workflows/release.yaml
Labels: exclude from release notes

#2276 use server-side fairness policy if applicable
  core/clustersmngr/clustersmngr.go
  go.mod
  go.sum
Labels: enhancement

#2345 Duplicates on detail pages table view
  core/server/fluxruntime.go
Labels: bug, team/denim

#2322 Display oci helm repositories well
  api/core/core.swagger.json
  api/core/types.proto
  core/server/types/helmrelease_test.go
  core/server/types/helmrepository.go
  core/server/types/helmrepository_test.go
  go.mod
  go.sum
  pkg/api/core/types.pb.go
  pkg/server/auth/token_signer_verifier.go
  pkg/services/auth/jwt.go
  pkg/services/auth/jwt_test.go
  ui/components/HelmRepositoryDetail.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/Breadcrumbs.test.tsx
  ui/components/__tests__/Metadata.test.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
  ui/lib/api/core/types.pb.ts
  ui/lib/types.ts
Labels: enhancement

#2351 Show Reconciling State in UI
  ui/components/FilterableTable.tsx
  ui/components/Icon.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/components/PageStatus.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/FilterableTable.test.tsx
  ui/images/reconcile.svg
  ui/lib/__tests__/utils.test.ts
  ui/lib/images.ts
  ui/lib/utils.ts
Labels: ui

#2339 Add `Using Terraform templates` Guide to docs
  website/docs/guides/using-terraform-templates.mdx
Labels: documentation, exclude from release notes, team/pitch-black

#2374 Link to images in detail pages
  ui/components/ImageLink.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: ui

#2349 Make it easy to find out the k8s and flux version
  api/core/core.proto
  api/core/core.swagger.json
  core/clustersmngr/clustersmngrfakes/fake_clients_factory.go
  core/clustersmngr/factory.go
  core/clustersmngr/factory_test.go
  core/server/version.go
  core/server/version_test.go
  pkg/api/core/core.pb.go
  ui/components/Footer.tsx
  ui/components/Layout.tsx
  ui/components/Text.tsx
  ui/components/Version.tsx
  ui/components/__tests__/Version.test.tsx
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/components/__tests__/__snapshots__/Version.test.tsx.snap
  ui/lib/api/core/core.pb.ts
Labels: enhancement, team/denim

#2387 Removes tags from image links
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: ui
