Repository weaveworks/weave-gitops, pull requests merged in 2022-07, with the labels that each got.

#2379 Allow the oidc secret to be named other than 'oidc-auth' and improve logging
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/oidc-auth-secret.yaml
  charts/gitops-server/values.yaml
  cmd/gitops-server/cmd/cmd.go
  core/server/featureflags.go
  core/server/featureflags_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/versioned_docs/version-0.8.0/configuration/securing-access-to-the-dashboard.mdx
  website/versioned_docs/version-0.8.1/configuration/securing-access-to-the-dashboard.mdx
  website/versioned_docs/version-0.9.0/configuration/securing-access-to-the-dashboard.mdx
Labels: enhancement

#2390 Graph view hides resources with default zoom
  ui/components/DirectedGraph.tsx
  ui/components/Footer.tsx
  ui/components/ReconciliationGraph.tsx
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: bug, team/denim

#2394 Fixed bug in computeReady function
  ui/components/KubeStatusIndicator.tsx
  ui/components/__tests__/KubeStatusIndicator.test.tsx
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
Labels: ui

#2393 granted permissions for chart publication
  .github/workflows/chart.yaml
Labels: exclude from release notes, team/denim

#2372 manual: Update AWS Marketplace installation instructions
  website/docs/installation.mdx
  website/versioned_docs/version-0.9.0/installation.mdx
Labels: exclude from release notes

#2400 Update README.md
  README.md
Labels: exclude from release notes

#2401 Help command for gitops beta run
  cmd/gitops/beta/cmd.go
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/cmderrors/errors.go
  cmd/gitops/root/cmd.go
Labels: enhancement, team/denim

#2407 don't leave exited container dangling on user's system
  website/docs/getting-started.mdx
Labels: documentation, exclude from release notes

#2408 fix nil pointer deref in GitRepositoryToProto
  core/server/types/gitrepository.go
  core/server/types/gitrepository_test.go
Labels: bug

#2403 add gitops bucket server
  Makefile
  cmd/gitops-bucket-server/main.go
  gitops-bucket-server.dockerfile
  go.mod
  go.sum
Labels: enhancement

#2395 Redirect to previous location on 401
  ui/contexts/AuthContext.tsx
  ui/contexts/CoreClientContext.tsx
Labels: ui

#2413 reduce logging verbosity
  pkg/server/auth/jwt.go
  pkg/server/middleware/middleware.go
Labels: exclude from release notes

#2406 Introduce BE featureflags, make the auth system use them
  cmd/gitops-server/cmd/cmd.go
  core/server/featureflags.go
  core/server/featureflags_test.go
  pkg/featureflags/featureflags.go
  pkg/featureflags/featureflags_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
Labels: enhancement

#2411 Add functionality to gitops beta run command
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/cmderrors/errors.go
  core/server/version.go
  go.mod
  go.sum
  pkg/run/run.go
Labels: enhancement, team/denim

#2424 Set version flags when building release images, too
  .github/workflows/release.yaml
Labels: bug, team/denim

#2389 Nav fixed vertically, but scrolls horizontally
  ui/components/Layout.tsx
Labels: ui

#2427 clustersmngr: Make it possible to inject another clusterpool
  cmd/gitops-server/cmd/cmd.go
  core/clustersmngr/factory.go
  core/clustersmngr/factory_test.go
  core/server/fluxruntime_test.go
  core/server/suite_test.go
Labels: exclude from release notes

#2433 Update example-enterprise-helm.yaml
  website/versioned_docs/version-0.9.0/assets/example-enterprise-helm.yaml
Labels: documentation, exclude from release notes

#2410 feat: kubeconfig token passthrough authentication for WGE commands in CLI
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/add/clusters/cmd_test.go
  cmd/gitops/add/cmd.go
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/add/profiles/cmd_test.go
  cmd/gitops/add/terraform/cmd.go
  cmd/gitops/add/terraform/cmd_test.go
  cmd/gitops/beta/cmd.go
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/config/options.go
  cmd/gitops/delete/clusters/cmd.go
  cmd/gitops/delete/clusters/cmd_test.go
  cmd/gitops/delete/cmd.go
  cmd/gitops/get/clusters/cmd.go
  cmd/gitops/get/clusters/cmd_test.go
  cmd/gitops/get/cmd.go
  cmd/gitops/get/credentials/cmd.go
  cmd/gitops/get/credentials/cmd_test.go
  cmd/gitops/get/profiles/cmd.go
  cmd/gitops/get/templates/cmd.go
  cmd/gitops/get/templates/cmd_test.go
  cmd/gitops/get/templates/terraform/cmd.go
  cmd/gitops/get/templates/terraform/cmd_test.go
  cmd/gitops/main.go
  cmd/gitops/root/cmd.go
  cmd/gitops/root/cmd_test.go
  cmd/gitops/update/cmd.go
  cmd/gitops/update/profiles/profiles.go
  cmd/gitops/update/profiles/profiles_test.go
  pkg/adapters/http.go
  pkg/adapters/http_test.go
  pkg/kube/config_getter.go
  pkg/server/auth/auth.go
  pkg/server/auth/passthrough.go
  pkg/templates/templates_test.go
Labels: enhancement, team/pesto, team/denim

#2419 Add command to generate a secret
  cmd/gitops/get/bcrypt/cmd.go
  cmd/gitops/get/cmd.go
  go.mod
Labels: enhancement

#2438 Export Data Table
  ui/index.ts
Labels: exclude from release notes

#2434 Add flags to gitops run
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/cmderrors/errors.go
  pkg/run/forwarder/forwarder.go
  pkg/run/install_dev_bucket.go
  pkg/run/install_flux.go
  pkg/run/run.go
  pkg/version/version.go
Labels: enhancement, team/denim

#2440 Allow adding new allowed kinds to some of the generic endpoints
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/events.go
  core/server/events_test.go
  core/server/objects.go
  core/server/objects_test.go
  core/server/primarykinds.go
  core/server/server.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/helmrelease_test.go
  core/server/types/kustomization.go
  core/server/types/kustomization_test.go
  core/server/types/objects.go
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  ui/components/EventsTable.tsx
  ui/components/SourceLink.tsx
  ui/components/YamlView.tsx
  ui/hooks/events.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
Labels: exclude from release notes

#2444 Enable the metrics port on the deployment if metrics are enabled
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/deployment.yaml
Labels: exclude from release notes

#2445 Upgrade containerd
  go.mod
  go.sum
Labels: bug

#2446 Use access token for UserInfo endpoint access
  pkg/server/auth/auth.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
Labels: bug, team/sunglow, area/security

#2381 docs: Document manual approval steps for progressive delivery
  website/docs/guides/flagger-manual-gating.mdx
  website/static/img/pd-details-waiting.png
  website/static/img/pd-events-gate-passed.png
  website/static/img/pd-table-progressing.png
  website/static/img/pd-table-promoting.png
  website/static/img/pd-table-succeeded.png
  website/static/img/pd-table-waiting.png
Labels: documentation, exclude from release notes

#2449 Export YamlView
  ui/index.ts
Labels: exclude from release notes

#2450 Adding env var for the endpoint into the help message
  cmd/gitops/root/cmd.go
Labels: exclude from release notes

#2448 release: Set tag on the correct commit
  .github/workflows/release.yaml
Labels: bug

#2442 export link nav components
  ui/index.ts
Labels: exclude from release notes

#2443 implement sync for gitops run
  cmd/gitops/beta/run/cmd.go
  go.mod
  go.sum
  pkg/run/forward_port.go
  pkg/run/forwarder/const.go
  pkg/run/forwarder/forwarder.go
  pkg/run/forwarder/utils.go
  pkg/run/install_bucket_source_and_ks.go
  pkg/run/install_dev_bucket_server.go
  pkg/run/utils.go
Labels: enhancement

#2463 Add gitops get bcrypt-hash command to relevant docs
  charts/gitops-server/Chart.yaml
  charts/gitops-server/values.yaml
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/docs/getting-started.mdx
  website/docs/installation.mdx
Labels: exclude from release notes

#2458 add filterable table to flux runtime
  ui/components/FluxRuntime.tsx
Labels: enhancement

#2464 Fix repostats workflow
  .github/workflows/repostats.yaml
Labels: exclude from release notes

#2470 Unify oci link handling
  ui/components/HelmRepositoryDetail.tsx
  ui/components/Link.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/Link.test.tsx
  ui/index.ts
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: bug

#2469 Install GitOps Dashboard for gitops beta run
  cmd/gitops/beta/run/cmd.go
  go.mod
  go.sum
  pkg/run/apply_manifests.go
  pkg/run/get_kube_client.go
  pkg/run/install_dashboard.go
  pkg/run/install_flux.go
  pkg/run/run.go
  pkg/utils/ui.go
Labels: enhancement, team/denim

#2478 Updated readme with new screenshots
  README.md
  doc/img/01-apps.png
  doc/img/01-workloads.png
  doc/img/02-reconciliation.png
  doc/img/02-workload-detail.png
  doc/img/03-rbac.jpg
  doc/img/03-sources.png
  doc/img/04-flux-runtime.png
  doc/img/04-sources.jpg
  doc/img/05-runtime.jpg
Labels: exclude from release notes

#2479 Move Cluster column forward on Sources page
  ui/components/SourcesTable.tsx
Labels: ui

#2459 docs: Add progressive delivery docs
  website/docs/guides/delivery.mdx
  website/docs/guides/flagger-manual-gating.mdx
  website/static/img/dashboard-applications-delivery.png
  website/static/img/pd-details-initialized.png
  website/static/img/pd-details-progressing.png
  website/static/img/pd-details-succeeded.png
Labels: exclude from release notes

#2481 GitOps Run - add compile-time variable for the Dev Bucket container image
  Makefile
  pkg/run/install_dev_bucket_server.go
Labels: enhancement, team/denim

#2482 fix: stop auth passthrough from ignoring token in favour of SA
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/token_review_crb.yaml
  core/clustersmngr/clustersmngr.go
  pkg/kube/config_getter.go
  pkg/kube/kubehttp.go
  pkg/server/auth/auth.go
  pkg/server/auth/passthrough.go
Labels: exclude from release notes, team/pesto

#2488 refactor: move AddToScheme to scheme builder and handle errors
  cmd/gitops-server/cmd/cmd.go
  core/clustersmngr/client_test.go
  core/clustersmngr/factory_test.go
  core/nsaccess/nsaccess_test.go
  core/server/events_test.go
  core/server/fluxruntime_test.go
  core/server/helm_release_test.go
  core/server/kustomization_test.go
  core/server/objects_test.go
  core/server/sources_test.go
  core/server/suite_test.go
  core/server/suspend_test.go
  core/server/sync_test.go
  core/server/version_test.go
  pkg/kube/kubehttp.go
  pkg/server/server_suite_test.go
  pkg/server/server_test.go
  pkg/services/auth/auth_suite_test.go
  pkg/testutils/testutils.go
Labels: exclude from release notes

#2476 Remove DagreD3 to make a solid foundation for the graph
  ui/components/DirectedGraph.tsx
  ui/components/FilterableTable.tsx
  ui/components/GraphNode.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/components/ReconciliationGraph.tsx
  ui/hooks/objects.ts
  ui/lib/__tests__/graph.test.ts
  ui/lib/graph.ts
  ui/lib/utils.ts
Labels: ui

#2497 Port forwarding error immediately after installing the GitOps Dashboard not on the same run when installing Flux
  cmd/gitops/beta/run/cmd.go
  pkg/run/forward_port.go
  pkg/run/install_dashboard.go
  pkg/run/install_dev_bucket_server.go
Labels: bug, team/denim

#2498 remove tenancy cmd from core
  cmd/gitops/create/cmd.go
  cmd/gitops/create/tenants/cmd.go
  cmd/gitops/root/cmd.go
  go.mod
  go.sum
  pkg/tenancy/tenancy.go
  pkg/tenancy/tenancy_test.go
  pkg/tenancy/testdata/example.yaml
  pkg/tenancy/testdata/example.yaml.golden
Labels: exclude from release notes

#2472 display error messages when dev-ks fails
  cmd/gitops/beta/run/cmd.go
  pkg/run/forward_port.go
  pkg/run/install_bucket_source_and_ks.go
  pkg/run/install_bucket_source_and_ks_test.go
  pkg/run/install_dashboard.go
  pkg/run/install_dev_bucket_server.go
  pkg/run/install_flux.go
  pkg/run/run_suite_test.go
Labels: enhancement

#2499 fix: GetImpersonatedClient returns a multierror for use in API response
  api/core/core.proto
  api/core/core.swagger.json
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/clustersmngrfakes/fake_clients_factory.go
  core/clustersmngr/factory.go
  core/server/fluxruntime.go
  core/server/helm_release.go
  core/server/kustomization.go
  core/server/objects.go
  core/server/sources.go
  core/server/suite_test.go
  core/server/suspend.go
  core/server/sync.go
  core/server/version.go
  go.mod
  go.sum
  pkg/api/core/core.pb.go
  ui/lib/api/core/core.pb.ts
Labels: bug, team/pesto

#2496 build multi-platform container image upon release
  .github/workflows/release.yaml
Labels: enhancement

#2492 Remove the vertical scrollbar at login and showing two backgrounds stacking
  ui/components/Animations/SignInBackground.tsx
Labels: bug

#2501 release: Fix setting build-args when building the release image
  .github/workflows/release.yaml
Labels: exclude from release notes

#2487 List CRDs in Flux Runtime
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/admin-user-roles.yaml
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/ChipGroup.tsx
  ui/components/ControllersTable.tsx
  ui/components/CrdsTable.tsx
  ui/components/DetailTitle.tsx
  ui/components/FilterDialog.tsx
  ui/components/FilterableTable.tsx
  ui/components/FluxRuntime.tsx
  ui/components/SourceDetail.tsx
  ui/components/SubRouterTabs.tsx
  ui/components/Text.tsx
  ui/hooks/flux.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/pages/v2/FluxRuntime.tsx
Labels: enhancement

#2502 Change graph line path
  package-lock.json
  package.json
  ui/components/DirectedGraph.tsx
Labels: ui

#2494 Add SubRouterTab Styles
  ui/components/SubRouterTabs.tsx
Labels: ui

#2510 cli: Move CLI logger out of internal
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/get/profiles/cmd.go
  cmd/gitops/logger/logger.go
  cmd/gitops/logger/logger_test.go
  cmd/gitops/update/profiles/profiles.go
  cmd/gitops/upgrade/cmd.go
  cmd/gitops/version/cmd.go
Labels: exclude from release notes

#2495 Update logo
  ui/components/Link.tsx
  ui/components/Logo.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/components/__tests__/__snapshots__/Version.test.tsx.snap
  ui/images/Title.svg
  ui/images/logo.svg
  ui/lib/images.ts
Labels: ui

#2402 Website updates for the WGE 0.9.1 release
  website/docs/assets/example-enterprise-helm.yaml
  website/docs/cluster-management/assets/bootstrap/capi-gitops-cluster-bootstrap-config.yaml
  website/docs/cluster-management/getting-started.mdx
  website/docs/cluster-management/managing-existing-clusters.mdx
  website/docs/installation.mdx
  website/docs/policy/weave-policy-profile.mdx
  website/versioned_docs/version-0.9.1/assets/example-enterprise-helm.yaml
  website/versioned_docs/version-0.9.1/cluster-management/assets/bootstrap/capi-gitops-cluster-bootstrap-config.yaml
  website/versioned_docs/version-0.9.1/cluster-management/getting-started.mdx
  website/versioned_docs/version-0.9.1/cluster-management/managing-existing-clusters.mdx
  website/versioned_docs/version-0.9.1/installation.mdx
  website/versioned_docs/version-0.9.1/policy/weave-policy-profile.mdx
Labels: documentation, exclude from release notes

#2508 Remove brilliant but now unused graph utils + other unused components
  ui/components/ActionBar.tsx
  ui/components/AutomationSelector.tsx
  ui/components/Heading.tsx
  ui/components/KeyValueTable.tsx
  ui/components/PollingIndicator.tsx
  ui/components/TabPanel.tsx
  ui/components/__tests__/KeyValueTable.test.tsx
  ui/components/__tests__/__snapshots__/KeyValueTable.test.tsx.snap
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: ui

#2511 cli: Remove client from bcrypt command
  cmd/gitops/get/bcrypt/cmd.go
  cmd/gitops/get/cmd.go
Labels: exclude from release notes
