Repository weaveworks/weave-gitops, pull requests merged in 2022-11, with the labels that each got.

#2951 update templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/ISSUE_TEMPLATE/story.md
Labels: documentation, exclude from release notes, team/sunglow

#2947 Add test for ListSources
  ui/hooks/sources.ts
  ui/pages/__tests__/Automations.test.tsx
  ui/pages/__tests__/Sources.test.tsx
Labels: ui

#2969 update guidance for adminUser.username
  charts/gitops-server/values.yaml
  website/docs/references/helm-reference.md
Labels: documentation, exclude from release notes

#2962 Update filterByTypeCallback
  ui/components/DataTable.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/__tests__/DataTableFilters.test.tsx
  ui/index.ts
Labels: ui

#2964 Protect against undefined labels in ControllersTable
  ui/components/ControllersTable.tsx
Labels: ui

#2953 add pipeline promotion documentation
  website/docs/enterprise/pipelines/github-pr-promotions.mdx
  website/docs/enterprise/pipelines/img/promotion-pr.png
  website/docs/enterprise/pipelines/spec/_category_.json
Labels: documentation, exclude from release notes

#2972 Documentation update: small fix to change control planes to worker nodes in description
  website/docs/assets/templates/capd-template.yaml
Labels: exclude from release notes, team/denim

#2976 changes support email to sales email
  ui/components/Footer.tsx
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  website/docusaurus.config.js
Labels: documentation, ui, exclude from release notes, team/sunglow

#2979 Make custom icons obey size prop
  Tiltfile
  ui/components/Icon.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
Labels: bug

#2983 docs: fix typos, make markdownlint happy
  website/docs/configuration/tls.md
  website/docs/feedback-and-telemetry.md
  website/docs/getting-started.mdx
  website/docs/guides/cert-manager.md
  website/docs/guides/setting-up-dex.md
  website/docs/help-and-support.md
  website/docs/installation.mdx
  website/docs/intro.md
  website/docs/references/helm-reference.md
Labels: documentation, exclude from release notes

#2970 add yaml validation
  cmd/gitops/beta/run/cmd.go
  go.mod
  go.sum
  pkg/validate/validate.go
Labels: team/denim

#2989 fix error when parsing port-forward in session mode
  cmd/gitops/beta/run/cmd.go
Labels: team/denim

#2992 docs: More typo fixes
  website/docs/cluster-management/deleting-a-cluster.mdx
  website/docs/cluster-management/profiles.mdx
  website/docs/enterprise/multi-tenancy.mdx
  website/docs/gitops-run/overview.mdx
  website/docs/gitops-templates/templates.mdx
  website/docs/installation.mdx
  website/docs/intro.md
  website/docs/policy/commit-time-checks.mdx
  website/docs/policy/releases.mdx
  website/docs/policy/weave-policy-profile.mdx
Labels: documentation, skip-release-notes

#2977 Change `type` to `kind` on detail `<Info />` components
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/OCIRepositoryDetail.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourcesTable.tsx
Labels: ui

#2997 exchange promotion PR screenshot
  website/docs/enterprise/pipelines/img/promotion-pr.png
Labels: documentation

#2999 Add policy docs to v0.10.1
  website/versioned_docs/version-0.10.1/policy/commit-time-checks.mdx
  website/versioned_docs/version-0.10.1/policy/configuration.mdx
  website/versioned_docs/version-0.10.1/policy/getting-started.mdx
  website/versioned_docs/version-0.10.1/policy/policy-configuration.mdx
  website/versioned_docs/version-0.10.1/policy/policy-set.mdx
  website/versioned_docs/version-0.10.1/policy/policy.mdx
  website/versioned_docs/version-0.10.1/policy/releases.mdx
  website/versioned_docs/version-0.10.1/policy/weave-policy-profile.mdx
Labels: exclude from release notes

#3000 Add the latest policy docs to 0.10.2
  website/versioned_docs/version-0.10.2/policy/commit-time-checks.mdx
  website/versioned_docs/version-0.10.2/policy/configuration.mdx
  website/versioned_docs/version-0.10.2/policy/getting-started.mdx
  website/versioned_docs/version-0.10.2/policy/policy-configuration.mdx
  website/versioned_docs/version-0.10.2/policy/policy-set.mdx
  website/versioned_docs/version-0.10.2/policy/policy.mdx
  website/versioned_docs/version-0.10.2/policy/releases.mdx
  website/versioned_docs/version-0.10.2/policy/weave-policy-profile.mdx
Labels: exclude from release notes

#3002 Show namespace for Applications
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
Labels: ui

#3008 Open up ListObjects to allow for non-Kinds
  ui/hooks/objects.ts
Labels: exclude from release notes

#3021 Add transformFunc argument to filterConfig function
  ui/components/DataTable.tsx
  ui/components/FilterDialog.tsx
  ui/components/__tests__/DataTableFilters.test.tsx
  ui/components/__tests__/FilterDialog.test.tsx
Labels: ui

#3024 Constrain Revision column width on the automations table
  ui/components/AutomationsTable.tsx
Labels: ui

#3018 Support multiple instances of Flux in Flux Runtime view
  ui/components/ControllersTable.tsx
  ui/components/FluxRuntime.tsx
  ui/components/FluxVersionsTable.tsx
Labels: ui, team/sunglow

#3032 Fix formatting of tab
  website/docs/gitops-run/get-started.mdx
  website/versioned_docs/version-0.10.0/gitops-run/get-started.mdx
  website/versioned_docs/version-0.10.1/gitops-run/get-started.mdx
  website/versioned_docs/version-0.10.2/gitops-run/get-started.mdx
Labels: exclude from release notes

#3031 advise on flag usage
  website/docs/enterprise/pipelines/getting-started.mdx
  website/versioned_docs/version-0.10.2/enterprise/pipelines/getting-started.mdx
Labels: exclude from release notes, team/sunglow

#3037 docs/installation: use tabs for gitops cli installation
  website/docs/installation.mdx
Labels: documentation, exclude from release notes, skip-release-notes

#3041 3035 update docs with pendo info
  website/docs/feedback-and-telemetry.md
Labels: documentation, team/denim

#2868 Create config file on CLI action with user prompt for analytics
  cmd/gitops/get/config/cmd.go
  cmd/gitops/root/cmd.go
  cmd/gitops/set/config/cmd.go
  pkg/config/config.go
Labels: enhancement

#3039 Break up installation docs
  doc/setting-up-dex.md
  website/docs/cluster-management/getting-started.mdx
  website/docs/getting-started.mdx
  website/docs/gitops-run/get-started.mdx
  website/docs/guides/cert-manager.md
  website/docs/guides/deploying-capa.mdx
  website/docs/guides/setting-up-dex.md
  website/docs/guides/using-terraform-templates.mdx
  website/docs/installation.mdx
  website/docs/installation/_category_.json
  website/docs/installation/aws-marketplace.mdx
  website/docs/installation/overview.mdx
  website/docs/installation/weave-gitops-enterprise.mdx
  website/docs/installation/weave-gitops.mdx
Labels: documentation, exclude from release notes

#3044 update to docusaurus 2.2.0
  website/package.json
  website/yarn.lock
Labels: documentation, exclude from release notes

#2893 Add Pendo Track Events for Weave GitOps CLI
  .goreleaser.yml
  Makefile
  cmd/gitops/get/config/cmd.go
  cmd/gitops/root/cmd.go
  cmd/gitops/set/config/cmd.go
  go.mod
  go.sum
  pkg/analytics/analytics.go
  pkg/analytics/analytics_suite_test.go
  pkg/analytics/analytics_test.go
Labels: enhancement, team/denim

#3058 docs: remove duplicate "installation" entry from left nav
  website/docs/cluster-management/getting-started.mdx
  website/docs/getting-started.mdx
  website/docs/gitops-run/get-started.mdx
  website/docs/guides/cert-manager.md
  website/docs/guides/deploying-capa.mdx
  website/docs/guides/setting-up-dex.md
  website/docs/guides/using-terraform-templates.mdx
  website/docs/installation.mdx
  website/docs/installation/index.mdx
  website/docs/installation/weave-gitops.mdx
  website/docs/intro.md
Labels: documentation, team/denim

#3063 Rename `testSecret` to `testPasswordHash` in the install dashboard tests.
  pkg/run/install/install_dashboard_test.go
Labels: exclude from release notes, team/denim

#3061 Update update-docs.sh
  tools/update-docs.sh
Labels: documentation, exclude from release notes

#3043 add helm chart reloading capability
  cmd/gitops/beta/run/cmd.go
  pkg/run/paths.go
  pkg/run/watch/install_dev_bucket_server.go
  pkg/run/watch/setup_bucket_source.go
  pkg/run/watch/setup_dev_helm.go
  pkg/run/watch/setup_dev_ks.go
  pkg/run/watch/setup_dev_ks_test.go
Labels: team/denim

#3069 Pendo during signup screen
  ui/components/Pendo.tsx
  ui/pages/SignIn.tsx
Labels: ui, team/denim

#3060 backport the installation page fixes from #3058
  website/docusaurus.config.js
  website/versioned_docs/version-0.11.0/cluster-management/getting-started.mdx
  website/versioned_docs/version-0.11.0/getting-started.mdx
  website/versioned_docs/version-0.11.0/gitops-run/get-started.mdx
  website/versioned_docs/version-0.11.0/guides/cert-manager.md
  website/versioned_docs/version-0.11.0/guides/deploying-capa.mdx
  website/versioned_docs/version-0.11.0/guides/setting-up-dex.md
  website/versioned_docs/version-0.11.0/guides/using-terraform-templates.mdx
  website/versioned_docs/version-0.11.0/installation.mdx
  website/versioned_docs/version-0.11.0/installation/index.mdx
  website/versioned_docs/version-0.11.0/installation/weave-gitops.mdx
  website/versioned_docs/version-0.11.0/intro.md
Labels: documentation, exclude from release notes

#3085 Update Release Notes
  website/docs/enterprise/releases.mdx
  website/docs/gitops-templates/templates.mdx
  website/versioned_docs/version-0.11.0/enterprise/releases.mdx
  website/versioned_docs/version-0.11.0/gitops-templates/templates.mdx
Labels: documentation, exclude from release notes

#3075 Allow the wego-admin user read access to all objects
  charts/gitops-server/templates/admin-user-roles.yaml
  core/server/fluxruntime.go
  package-lock.json
  website/docs/configuration/user-permissions.mdx
Labels: ui
