Repository weaveworks/weave-gitops, pull requests merged in 2022-02, with the labels that each got.

#1374 Tilt install fix
  tools/dependencies.toml
  tools/download-deps.sh
Labels: exclude from release notes

#1334 Only add deploy key when needed
  cmd/gitops/add/app/cmd.go
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/beta/cmd/install.go
  cmd/gitops/delete/clusters/cmd.go
  cmd/gitops/install/cmd.go
  cmd/gitops/upgrade/cmd.go
  cmd/internal/provider_test.go
  pkg/flux/flux_test.go
  pkg/gitproviders/provider_org_test.go
  pkg/gitproviders/provider_user_test.go
  pkg/gitproviders/repo_url.go
  pkg/gitproviders/repo_url_test.go
  pkg/models/manifest_test.go
  pkg/server/internal/provider_test.go
  pkg/server/server.go
  pkg/services/app/add.go
  pkg/services/app/commit.go
  pkg/services/applicationv2/fetcher.go
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  pkg/services/automation/automation_test.go
  pkg/services/automation/generator.go
  pkg/services/factory.go
  pkg/services/factory_test.go
  pkg/services/gitops/install.go
  pkg/services/gitopswriter/writer_add_test.go
  pkg/services/install/install_test.go
  pkg/upgrade/upgrade.go
  test/acceptance/test/add_tests.go
  test/acceptance/test/utils.go
  test/integration/server/add_test.go
Labels: exclude from release notes

#1377 Expose test fakes as a package
  cmd/gitops-server/main.go
  cmd/gitops/ui/run/cmd.go
  go.mod
  go.sum
  pkg/kube/client_getter.go
  pkg/kube/cluster_config.go
  pkg/kube/config_getter.go
  pkg/kube/kube.go
  pkg/kube/kubefakes/fake_client_getter.go
  pkg/kube/kubefakes/fake_kube_getter.go
  pkg/server/config_getter.go
  pkg/server/config_getter_test.go
  pkg/server/profiles.go
  pkg/server/profiles_test.go
  pkg/server/server.go
  pkg/server/server_options.go
  pkg/server/server_test.go
  pkg/server/suite_test.go
  pkg/services/applicationv2/applicationv2fakes/fake_fetcher_factory.go
  pkg/services/applicationv2/fetcher.go
  test/integration/server/suite_test.go
Labels: exclude from release notes

#1375 Added prototype endpoints for adding and listing helm releases
  api/app/apps.proto
  api/app/apps.swagger.json
  api/app/source.proto
  core/server/sources.go
  core/server/sources_test.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/helmrepository.go
  core/server/types/utils.go
  pkg/api/app/apps.pb.go
  pkg/api/app/apps.pb.gw.go
  pkg/api/app/apps_grpc.pb.go
  pkg/api/app/source.pb.go
  ui/lib/api/app/apps.pb.ts
  ui/lib/api/app/source.pb.ts
Labels: exclude from release notes

#1358 Restructure GitHub auth test to remove flakiness
  pkg/services/auth/github_test.go
Labels: exclude from release notes

#1320 Print out GitSource from config repository on dry-run
  cmd/gitops/install/cmd.go
  pkg/models/manifest.go
  pkg/models/manifest_test.go
  pkg/services/auth/auth.go
  pkg/services/auth/auth_test.go
  pkg/services/factory.go
  pkg/services/install/install.go
  pkg/services/install/install_test.go
Labels: bug

#1384 Fix the downloading of tilt on OSX
  tools/download-deps.sh
Labels: bug, team/pitch-black

#1385 Add new components and navigation wiring
  manifests/wego-app/role.yaml.tpl
  ui/App.tsx
  ui/components/AddGitRepoForm.tsx
  ui/components/AutomationSelector.tsx
  ui/components/AutomationsTable.tsx
  ui/components/Layout.tsx
  ui/components/Page.tsx
  ui/components/SourcesTable.tsx
  ui/hooks/kustomizations.ts
  ui/hooks/sources.ts
  ui/lib/types.ts
  ui/lib/utils.ts
  ui/pages/v2/AddAutomation.tsx
  ui/pages/v2/AddGitRepo.tsx
  ui/pages/v2/AddKustomization.tsx
  ui/pages/v2/AddSource.tsx
  ui/pages/v2/Application/Application.tsx
  ui/pages/v2/KustomizationList.tsx
Labels: exclude from release notes

#1360 Implement `add profile` to install a profile to a cluster
  .gitignore
  cmd/gitops/add/cmd.go
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/add/profiles/cmd_test.go
  cmd/gitops/add/profiles/profile_suite_test.go
  cmd/gitops/get/profiles/cmd.go
  go.mod
  go.sum
  pkg/git/git.go
  pkg/gitproviders/dryrun.go
  pkg/gitproviders/gitprovidersfakes/fake_git_provider.go
  pkg/gitproviders/provider.go
  pkg/gitproviders/provider_org.go
  pkg/gitproviders/provider_org_test.go
  pkg/gitproviders/provider_user.go
  pkg/gitproviders/provider_user_test.go
  pkg/helm/releases.go
  pkg/helm/releases_test.go
  pkg/helm/watcher/controller/helm_watcher.go
  pkg/models/manifest.go
  pkg/models/manifest_test.go
  pkg/services/install/install_test.go
  pkg/services/profiles/add.go
  pkg/services/profiles/add_test.go
  pkg/services/profiles/get.go
  pkg/services/profiles/get_test.go
  pkg/services/profiles/profiles.go
  pkg/vendorfakes/fakegitprovider/file_client.go
  pkg/vendorfakes/fakegitprovider/org_repository.go
  pkg/vendorfakes/fakegitprovider/pull_request.go
  pkg/vendorfakes/fakegitprovider/user_repository.go
  pkg/vendorfakes/generate.go
  test/acceptance/test/profiles_test.go
  test/acceptance/test/utils.go
  tools/testcrds/helm.toolkit.fluxcd.io_helmreleases.yaml
Labels: enhancement, type/story, team/pitch-black

#1391 Add groups scope
  go.mod
  go.sum
  pkg/kube/client_getter.go
  pkg/kube/kubehttp.go
  pkg/server/auth/auth.go
  pkg/server/auth/server.go
Labels: bug

#1393 Pend the profiles test until we can figure out a better way to run them
  test/acceptance/test/profiles_test.go
Labels: bug, team/pitch-black

#1390 Notify Slack when the `main` branch build fails
  .github/workflows/test.yml
Labels: exclude from release notes, team/bluetonium

#1398 use gopkg.in/yaml.v2 2.4.0 to resolve snyk warning
  go.mod
  go.sum
  pkg/services/profiles/add.go
Labels: exclude from release notes

#1403 Fix the tilt build locally
  Makefile
  Tiltfile
  pkg/models/manifest.go
  test/acceptance/test/scripts/kind-cluster.sh
  tools/deploy-local-registry.sh
  tools/kind-with-registry.sh
  tools/wego-app-dev.yaml
Labels: bug, team/pitch-black

#1396 Fixes system kustomization reconciling if no profiles installed
  pkg/models/manifest.go
  pkg/models/manifest_test.go
  pkg/services/install/install_test.go
  test/acceptance/test/add_tests.go
  test/acceptance/test/utils.go
Labels: exclude from release notes

#1400 improve waiting for resources to exist
  test/acceptance/test/add_tests.go
  test/acceptance/test/scripts/kind-cluster.sh
  test/acceptance/test/scripts/kind-multi-cluster.sh
  test/acceptance/test/utils.go
Labels: exclude from release notes

#1407 Use snyk for js, go & docker, upload results properly
  .github/workflows/scan.yaml
Labels: exclude from release notes

#1404 Add conditions field to flux objects
  .github/workflows/v2.yml
  api/app/apps.swagger.json
  api/app/flux.proto
  api/app/flux.swagger.json
  api/app/source.proto
  api/app/source.swagger.json
  api/applications/applications.swagger.json
  api/profiles/profiles.swagger.json
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/kustomization.go
  core/server/types/utils.go
  go.mod
  go.sum
  pkg/api/app/apps.pb.go
  pkg/api/app/flux.pb.go
  pkg/api/app/source.pb.go
  pkg/api/applications/applications.pb.go
  pkg/api/profiles/profiles.pb.go
  ui/components/KustomizationTable.tsx
  ui/components/SourcesTable.tsx
  ui/lib/api/app/flux.pb.ts
  ui/lib/api/app/source.pb.ts
  ui/lib/types.ts
  ui/lib/utils.ts
  ui/pages/v2/KustomizationList.tsx
Labels: exclude from release notes

#1408 Modify the local build to install and configure tilt for first runners
  Makefile
  README.md
  Tiltfile
Labels: enhancement

#1405 fix deploy workflow
  .github/actions/run-acceptance-test/action.yml
  .github/workflows/deploy.yml
Labels: exclude from release notes, ci

#1413 change kind-cluster script to bash
  .github/workflows/deploy.yml
  test/acceptance/test/scripts/kind-cluster.sh
Labels: exclude from release notes

#1428 clean up docs references to `wego` CLI
  cmd/gitops/flux/cmd.go
  website/docs/cli-reference/gitops_flux.md
Labels: exclude from release notes

#1387 Add instructions on `gitops upgrade` for hosted/on-prem gitlab
  website/docs/cluster-management/deleting-a-cluster.mdx
  website/docs/cluster-management/getting-started.mdx
  website/docs/cluster-management/managing-existing-clusters.mdx
  website/docs/cluster-management/profiles.mdx
  website/docs/cluster-management/provider-identities.mdx
  website/docs/cluster-management/templates.mdx
  website/docs/enterprise/deploying-capa.mdx
  website/docs/enterprise/upgrading-eks.mdx
  website/docs/enterprise/upgrading.mdx
Labels: documentation, exclude from release notes, team/pesto

#1427 Add OIDC docs for WGE
  website/docs/enterprise/oidc.mdx
Labels: exclude from release notes

#1430 Fix the notification controller address
  cmd/gitops-server/main.go
  cmd/gitops/ui/run/cmd.go
Labels: bug

#1433 Fix nightly CI failures
  test/acceptance/test/add_tests.go
Labels: exclude from release notes

#1438 Pass Credentials from the HelmRepository
  pkg/helm/charts.go
Labels: enhancement, team/pitch-black

#1458 Pend failing smoke test
  test/acceptance/test/add_tests.go
Labels: exclude from release notes, area/testing, skip-release-notes

#1447 Add Title To Logo
  ui/components/Logo.tsx
  ui/components/__tests__/Logo.test.tsx
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/images/Title.svg
Labels: ui

#1450 Fix workflow link in the `website` README
  website/README.md
Labels: exclude from release notes

#1461 Stop describing releases as straightforward
  doc/release-process.md
Labels: exclude from release notes

#1470 Resolve wait times issues for tests
  test/acceptance/test/add_tests.go
  test/acceptance/test/utils.go
Labels: exclude from release notes

#1463 Add option for configuring PR settings in add/update profile
  cmd/gitops/add/clusters/cmd.go
  cmd/gitops/add/profiles/cmd.go
  cmd/gitops/update/profiles/profiles.go
  cmd/internal/flags.go
  pkg/services/profiles/add.go
  pkg/services/profiles/add_test.go
  pkg/services/profiles/profiles.go
  pkg/services/profiles/update.go
  pkg/services/profiles/update_test.go
Labels: enhancement, profiles-improvement, team/pitch-black

#1472 Add logout endpoint
  pkg/server/auth/auth.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
Labels: enhancement

#1490 Auth SignIn - OIDC / Superuser
  .proxyrc
  api/applications/applications.proto
  api/applications/applications.swagger.json
  cmd/gitops/ui/run/cmd.go
  cmd/gitops/ui/run/cmd_test.go
  go.mod
  package.json
  pkg/api/applications/applications.pb.go
  pkg/api/applications/applications.pb.gw.go
  pkg/api/applications/applications_grpc.pb.go
  pkg/server/auth/auth.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/jwt.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
  pkg/server/auth/token_signer_verifier.go
  pkg/server/handler.go
  pkg/server/server.go
  ui/App.tsx
  ui/contexts/AuthContext.tsx
  ui/images/SignInBackground.svg
  ui/images/SignInWheel.svg
  ui/images/WeaveLogo.svg
  ui/index.ts
  ui/lib/api/applications/applications.pb.ts
  ui/pages/SignIn.tsx
Labels: enhancement

#1504 Upgrade weaveworks/go-checkpoint to version with go.mod
  go.mod
  go.sum
Labels: exclude from release notes

#1488 Enhance Data Table Sorting Functionality
  ui/__tests__/library.test.tsx
  ui/components/AutomationsTable.tsx
  ui/components/CommitsTable.tsx
  ui/components/ConditionsTable.tsx
  ui/components/DataTable.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/DataTable.test.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/pages/Applications.tsx
  ui/pages/__tests__/ApplicationDetail.test.tsx
  ui/pages/v2/FluxRuntime.tsx
  ui/stories/DataTable.stories.tsx
Labels: ui

#1492 Auth logout
  ui/App.tsx
  ui/components/Icon.tsx
  ui/components/Layout.tsx
  ui/components/UserSettings.tsx
  ui/contexts/AuthContext.tsx
  ui/contexts/FeatureFlags.tsx
  ui/index.ts
Labels: enhancement

#1489 Add reconciled and child object API endpoints and KustomizationDetail page
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/automations.go
  core/server/automations_test.go
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/server.go
  core/server/suite_test.go
  core/server/types/kustomization.go
  go.mod
  go.sum
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  tools/testcrds/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  ui/App.tsx
  ui/components/AutomationsTable.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/hooks/automations.ts
  ui/hooks/flux.ts
  ui/lib/__tests__/graph.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/graph.ts
  ui/pages/ApplicationDetail.tsx
  ui/pages/v2/KustomizationDetail.tsx
Labels: team/mauvelous

#1531 Turn off gitlab acceptance tests
  .github/workflows/test.yml
Labels: exclude from release notes

#1483 Serve `ui run` over https
  .proxyrc
  .proxyrc.js
  cmd/gitops/cmderrors/errors.go
  cmd/gitops/ui/run/cmd.go
  cmd/gitops/ui/run/cmd_test.go
  pkg/server/auth/server.go
  pkg/server/server.go
  pkg/server/tls/tls.go
  pkg/server/tls/tls_test.go
  pkg/services/profiles/get.go
  test/acceptance/test/profiles_test.go
  website/docs/getting-started.md
  website/docs/gitops-dashboard.md
  website/versioned_docs/version-0.4.1/getting-started.md
Labels: enhancement

#1529 ci: Don't need to run snyk test manually
  .github/workflows/scan.yaml
Labels: exclude from release notes

#1493 Add docs for superuser flow
  website/docs/gitops-dashboard.md
Labels: exclude from release notes

#1516 Rate limit login requests
  cmd/gitops/ui/run/cmd.go
  go.mod
  go.sum
  pkg/server/auth/auth.go
  pkg/server/auth/auth_test.go
Labels: exclude from release notes

#1528 Add exports
  package-lock.json
  package.json
  ui/contexts/AuthContext.tsx
  ui/index.ts
  ui/lib/images.ts
  ui/pages/SignIn.tsx
Labels: exclude from release notes

#1525 Adjust Nav Styling
  ui/components/Layout.tsx
  ui/components/Logo.tsx
  ui/components/Page.tsx
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/images/background.svg
  ui/lib/theme.ts
Labels: ui

#1524 Add a RoleBinding for `User: admin`
  manifests/wego-app/admin-role-binding.yaml.tpl
  pkg/services/gitops/uninstall_test.go
Labels: enhancement

#1547 Images for ee
  ui/lib/images.ts
Labels: exclude from release notes
