Repository weaveworks/weave-gitops, pull requests merged in 2022-12, with the labels that each got.

#3059 Add `--skip-dashboard-install` flag to GitOps Run
  cmd/gitops/beta/run/cmd.go
Labels: enhancement, team/denim

#3092 Pendo Agent for Enterprise
  cmd/gitops-server/cmd/cmd.go
  core/server/server.go
  package.json
  pkg/telemetry/telemetry.go
  tools/helm-values-dev.yaml
  ui/App.tsx
  ui/components/AlertsTable.tsx
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/ControllersTable.tsx
  ui/components/CrdsTable.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/NotificationsTable.tsx
  ui/components/OCIRepositoryDetail.tsx
  ui/components/Pendo.tsx
  ui/components/SourcesTable.tsx
  ui/contexts/CoreClientContext.tsx
  ui/hooks/featureflags.ts
  ui/index.ts
  ui/pages/SignIn.tsx
Labels: enhancement, team/denim

#3102 implement auth middleware for s3
  cmd/gitops-bucket-server/main.go
  pkg/s3/auth_middleware.go
  pkg/s3/auth_middleware_test.go
Labels: enhancement

#3111 test: fix occasional panic sending on a closed channel
  core/server/sync_test.go
Labels: area/testing, team/denim

#3106 use HTTPS in `gitops run` S3 bucket server
  Makefile
  cmd/gitops/beta/run/cmd.go
  pkg/logger/s3_log_writer.go
  pkg/run/watch/install_dev_bucket_server.go
  pkg/s3/minio.go
  pkg/tls/certs.go
  pkg/tls/certs_test.go
Labels: gitops-run

#3110 Fix incorrect message display for reconciled objects
  ui/components/ReconciledObjectsTable.tsx
Labels: ui

#3112 Return empty string on unknown route
  ui/components/FluxObjectsTable.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/__tests__/FluxObjectsTable.test.tsx
  ui/lib/fixtures/objects_table.ts
  ui/lib/nav.ts
Labels: bug

#3115 Pipeline docs for using GitOpsTemplates
  website/docs/enterprise/pipelines/img/pipelines-table-create.png
  website/docs/enterprise/pipelines/img/pipelines-templates.png
  website/docs/enterprise/pipelines/pipeline-templates.mdx
Labels: documentation, exclude from release notes, team/sunglow

#3121 bump golang.org/x/net to fix CVE
  go.mod
  go.sum
Labels: team/denim, area/security

#3108 Hyperlink to Cluster details page when referenced
  ui/components/BucketDetail.tsx
  ui/components/ClusterDashboardLink.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/OCIRepositoryDetail.tsx
Labels: ui

#3128 fix version in gitops download link in 0.11.0 docs
  website/versioned_docs/version-0.11.0/installation/weave-gitops.mdx
Labels: documentation

#3116 helm: Use HTTPS scheme for liveness/readiness probe when serverTLS is enabled
  charts/gitops-server/templates/deployment.yaml
Labels: bug, team/denim

#3131 update guidance
  website/docs/installation/weave-gitops.mdx
  website/versioned_docs/version-0.12.0/installation/weave-gitops.mdx
Labels: documentation, exclude from release notes, team/sunglow

#3136 guidance on oss release notes
  website/docs/releases.mdx
  website/versioned_docs/version-0.12.0/releases.mdx
Labels: documentation, exclude from release notes

#3132 updated pipeline pull request git provider type docs
  website/docs/pipelines/promoting-applications.mdx
  website/docs/pipelines/spec/v1alpha1/pipeline.mdx
  website/versioned_docs/version-0.12.0/pipelines/promoting-applications.mdx
  website/versioned_docs/version-0.12.0/pipelines/spec/v1alpha1/pipeline.mdx
Labels: documentation, exclude from release notes

#3147 removing from docs as it was not from v0.12
  website/versioned_docs/version-0.12.0/pipelines/promoting-applications.mdx
  website/versioned_docs/version-0.12.0/pipelines/spec/v1alpha1/pipeline.mdx
Labels: documentation, exclude from release notes

#3140 Update exports
  ui/index.ts
Labels: exclude from release notes

#3158 fix flaky multi-server test
  pkg/http/server_test.go
Labels: skip-release-notes

#3161 update URL for FAQs
  README.md
Labels: documentation, exclude from release notes

#3134 Keyboard shortcuts for "port forwards" on GitOps Run
  cmd/gitops/beta/run/cmd.go
  go.mod
  go.sum
  pkg/run/watch/forward_port.go
Labels: enhancement, gitops-run

#3166 Pendo: Get rid of anonymous visitors on sign in page
  ui/components/Pendo.tsx
  ui/pages/SignIn.tsx
Labels: enhancement

#3170 feat: support for -n flag for --namespace
  cmd/gitops/root/cmd.go
Labels: team/sunglow

#3143 Added extraVolumes and extraVolumesMounts.
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/values.yaml
Labels: enhancement

#3162 Added podLabels value.
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/values.yaml
Labels: enhancement

#3186 Add versioning section to docs
  doc/release-process.md
Labels: exclude from release notes

#3190 migrate tf commands from tfctl
  cmd/gitops/create/cmd.go
  cmd/gitops/create/terraform/cmd.go
  cmd/gitops/delete/cmd.go
  cmd/gitops/delete/terraform/cmd.go
  cmd/gitops/logs/cmd.go
  cmd/gitops/logs/terraform/cmd.go
  cmd/gitops/replan/cmd.go
  cmd/gitops/replan/terraform/cmd.go
  cmd/gitops/resume/cmd.go
  cmd/gitops/resume/terraform/cmd.go
  cmd/gitops/root/cmd.go
  cmd/gitops/suspend/cmd.go
  cmd/gitops/suspend/terraform/cmd.go
  go.mod
  go.sum
Labels: enhancement, terraform

#3194 sanitize input when processing S3 authorization header
  pkg/s3/auth_middleware.go
  pkg/s3/auth_middleware_test.go
Labels: bug, area/security, gitops-run

#3172 Pendo: Track if users are coming from OSS or Ent and latest version
  ui/App.tsx
  ui/components/Footer.tsx
  ui/components/Pendo.tsx
  ui/components/PendoContainer.tsx
  ui/components/Version.tsx
  ui/components/__tests__/Version.test.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
  ui/pages/SignIn.tsx
Labels: ui

#3196 Make context the first param of Go functions
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/create/dashboard/cmd.go
  pkg/run/install/apply_manifests.go
  pkg/run/install/apply_manifests_test.go
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_dashboard_test.go
  pkg/run/install/install_flux.go
  pkg/run/install/install_flux_test.go
  pkg/server/server_test.go
Labels: go
