Repository weaveworks/weave-gitops, pull requests merged in 2022-08, with the labels that each got.

#2504 2489 gitops run port forwarding error follow up
  cmd/gitops/beta/run/cmd.go
  pkg/run/errors.go
  pkg/run/forward_port.go
  pkg/run/install_dashboard.go
  pkg/run/install_dev_bucket_server.go
  pkg/run/utils.go
Labels: bug, team/denim

#2516 docs: Use new algolia to re-enable search
  website/docusaurus.config.js
Labels: exclude from release notes

#2521 Only release helm chart when the Chart version has changed
  .github/workflows/chart.yaml
Labels: exclude from release notes

#2525 add unit tests for get pod from spec map
  pkg/run/forward_port.go
  pkg/run/forward_port_test.go
  pkg/run/install_bucket_source_and_ks_test.go
Labels: exclude from release notes

#2513 increase Flux resource intervals
  website/docs/assets/example-enterprise-helm.yaml
  website/docs/getting-started.mdx
  website/docs/installation.mdx
Labels: documentation, enhancement, team/sunglow

#2509 change docs to refer to the OCI registry for chart storage
  website/docs/getting-started.mdx
  website/docs/installation.mdx
Labels: documentation, enhancement, team/sunglow

#2518 Use getObject for all sources details
  package.json
  tsconfig.json
  ui/components/AutomationDetail.tsx
  ui/components/BucketDetail.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/SourceDetail.tsx
  ui/hooks/objects.ts
  ui/lib/__tests__/objects.test.ts
  ui/lib/objects.ts
Labels: ui

#2533 use proper numbered lists
  website/docs/getting-started.mdx
Labels: bug, documentation

#2531 Write unit tests for GitOps Run: Flux and GitOps Dashboard installation Part 1
  cmd/gitops/beta/run/cmd.go
  pkg/run/get_kube_client_test.go
  pkg/run/install_flux_test.go
  pkg/run/run_suite_test.go
  pkg/run/utils_test.go
Labels: exclude from release notes, team/denim

#2522 Make authentication method selection explicit
  charts/gitops-server/templates/token_review_crb.yaml
  cmd/gitops-server/cmd/cmd.go
  pkg/server/auth/auth.go
  pkg/server/auth/auth_method_type.go
  pkg/server/auth/auth_method_type_test.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/init.go
  pkg/server/auth/init_test.go
  pkg/server/auth/jwt.go
  pkg/server/auth/jwt_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
Labels: enhancement

#2517 expose errors coming from sources API calls
  ui/components/AddKustomizationForm.tsx
  ui/components/AutomationsTable.tsx
  ui/components/Page.tsx
  ui/components/SourceDetail.tsx
  ui/hooks/automations.ts
  ui/hooks/sources.ts
  ui/lib/types.ts
  ui/pages/v2/Automations.tsx
  ui/pages/v2/Sources.tsx
Labels: enhancement

#2493 Refactor SortWithType to use OrderBy from lodash so we will be able to Order/Sort Data by Fields to generate Unique Collection that is not Flick.
  ui/components/AutomationsTable.tsx
  ui/components/ControllersTable.tsx
  ui/components/DataTable.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/DataTable.test.tsx
  ui/components/__tests__/FilterableTable.test.tsx
  ui/index.ts
Labels: enhancement

#2536 Don't allow login method unless _both_ cli arg _and_ feature flag is set
  pkg/server/auth/auth.go
Labels: bug

#2532 Add gzip compression
  cmd/gitops-server/cmd/cmd.go
  go.mod
  go.sum
Labels: enhancement, team/denim

#2524 chart: Remove backwards compatibility for v0.8.0 and before
  charts/gitops-server/templates/admin-user.yaml
  charts/gitops-server/templates/custom-admin-user.yaml
Labels: exclude from release notes, team/denim

#2537 new icons and text wrapping for easier editing
  website/docs/guides/delivery.mdx
  website/static/img/ab.svg
  website/static/img/blue-green.svg
  website/static/img/canary.svg
  website/static/img/mirroring.svg
  website/versioned_docs/version-0.9.1/guides/delivery.mdx
Labels: documentation, exclude from release notes

#2540 fix styling
  website/docs/guides/delivery.mdx
  website/versioned_docs/version-0.9.1/guides/delivery.mdx
Labels: documentation, exclude from release notes

#2541 avoid line breaks
  website/docs/guides/delivery.mdx
  website/versioned_docs/version-0.9.1/guides/delivery.mdx
Labels: documentation, exclude from release notes

#2539 Install & wait for extra components when specified
  cmd/gitops/beta/run/cmd.go
  go.mod
Labels: enhancement

#2542 Fix local development
  Tiltfile
  cmd/gitops-server/cmd/cmd.go
  pkg/server/auth/init.go
  pkg/server/auth/init_test.go
  pkg/server/auth/token_signer_verifier.go
Labels: exclude from release notes

#2538 Extend automation details with tabs
  ui/components/AutomationDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/hooks/automations.ts
  ui/index.ts
Labels: enhancement

#2544 extend-automation-details-with-tabs
  ui/components/AutomationDetail.tsx
  ui/components/SubRouterTabs.tsx
Labels: bug

#2543 add an `-n` option not to print a newline when generating hash
  website/docs/getting-started.mdx
Labels: exclude from release notes

#2546 Fix pod not found error.
  cmd/gitops/beta/run/cmd.go
  pkg/run/install_dashboard.go
Labels: exclude from release notes, team/denim

#2549 Fix bcrypt-hash example in more places
  cmd/gitops/get/bcrypt/cmd.go
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/docs/installation.mdx
  website/versioned_docs/version-0.9.1/configuration/securing-access-to-the-dashboard.mdx
  website/versioned_docs/version-0.9.1/getting-started.mdx
  website/versioned_docs/version-0.9.1/installation.mdx
  website/versioned_docs/version-0.9.1/references/cli-reference/gitops_get_bcrypt-hash.md
Labels: exclude from release notes

#2526 (almost) Support running gitops without flux-system namespace
  api/v1alpha1/application_types.go
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/admin-user-creds.yaml
  charts/gitops-server/templates/admin-user-roles.yaml
  charts/gitops-server/templates/admin-user.yaml
  cmd/gitops-server/cmd/cmd.go
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/root/cmd.go
  cmd/gitops/upgrade/cmd.go
  pkg/flux/flux_test.go
  pkg/run/get_kube_client_test.go
  pkg/run/install_dashboard.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/init.go
  pkg/server/auth/init_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
  pkg/upgrade/upgrade_test.go
  ui/lib/types.ts
Labels: enhancement, team/denim

#2550 Improve watcher and file walker when a directory is added or removed
  cmd/gitops/beta/run/cmd.go
Labels: bug

#2570 Add options parameter for hooks
  ui/hooks/automations.ts
  ui/hooks/events.ts
  ui/hooks/flux.ts
  ui/hooks/objects.ts
  ui/hooks/sources.ts
  ui/lib/types.ts
Labels: ui

#2547 Write unit tests for GitOps Run: Flux and GitOps Dashboard installation Part 2
  cmd/gitops/beta/run/cmd.go
  pkg/run/apply_manifests.go
  pkg/run/apply_manifests_test.go
  pkg/run/forward_port_test.go
  pkg/run/get_kube_client.go
  pkg/run/get_kube_client_test.go
  pkg/run/install_bucket_source_and_ks_test.go
  pkg/run/install_dashboard.go
  pkg/run/install_dashboard_test.go
  pkg/run/install_flux.go
  pkg/run/install_flux_test.go
  pkg/run/run_suite_test.go
  pkg/run/utils.go
  pkg/run/utils_test.go
Labels: exclude from release notes, team/denim

#2558 Add support for OCI Repositories
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  charts/gitops-server/templates/admin-user-roles.yaml
  core/server/internal/adapters.go
  core/server/primarykinds.go
  core/server/sources.go
  core/server/sync.go
  core/server/types/kustomization.go
  core/server/types/ocirepository.go
  core/server/types/utils.go
  go.mod
  go.sum
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  ui/App.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/OCIRepositoryDetail.tsx
  ui/components/SourcesTable.tsx
  ui/hooks/objects.ts
  ui/hooks/sources.ts
  ui/lib/__tests__/objects.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/nav.ts
  ui/lib/objects.ts
  ui/lib/types.ts
  ui/pages/v2/OCIRepositoryPage.tsx
Labels: enhancement, team/denim

#2575 Fix chart publishing
  .github/workflows/chart.yaml
Labels: bug

#2572 fix: profiles api json tags can't json.Unmarshal
  Makefile
  api/profiles/profiles.proto
  pkg/api/profiles/profiles.pb.go
  pkg/api/profiles/profiles.pb.gw.go
  pkg/services/profiles/get_test.go
Labels: bug

#2577 Fix empty error component adding whitespace
  ui/components/Page.tsx
Labels: ui

#2560 fix: add client timeout and fix namspace update
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/clustersmngrfakes/fake_clients_pool.go
  core/clustersmngr/factory.go
Labels: bug

#2559 Style Filterable Table
  ui/components/ChipGroup.tsx
  ui/components/DataTable.tsx
  ui/components/FilterableTable.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/lib/theme.ts
  ui/typedefs/styled.d.ts
Labels: bug, team/sunglow

#2580 Publish NPM package each merge
  .github/workflows/pr.yaml
Labels: exclude from release notes

#2583 Move some functions from `gitops/beta/run/cmd` and `pkg/run/utils` to more appropriate files
  cmd/gitops/beta/run/cmd.go
  pkg/run/install_bucket_source_and_ks.go
  pkg/run/install_bucket_source_and_ks_test.go
  pkg/run/install_dashboard.go
  pkg/run/install_flux.go
  pkg/run/utils.go
Labels: exclude from release notes, team/denim

#2584 Make OCI repositories opt-in, fix OCI repository permissions, fix rendering errors for sources
  charts/gitops-server/templates/admin-user-roles.yaml
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/values.yaml
  core/server/sources.go
  ui/components/SourceDetail.tsx
Labels: bug

#2586 doc: Add oci repository feature flags to to manual
  website/docs/getting-started.mdx
  website/docs/installation.mdx
Labels: documentation, exclude from release notes

#2589 website: Remove extra slash from website URLs
  website/docusaurus.config.js
Labels: exclude from release notes

#2591 Fix the changelog generation
  .github/changelog/changelog_configuration.json
  .github/workflows/prepare-release.yaml
Labels: exclude from release notes

#2565 Add new background plus header changes to match
  ui/components/Breadcrumbs.tsx
  ui/components/Button.tsx
  ui/components/Icon.tsx
  ui/components/Layout.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
  ui/images/General-backgroundok.png
  ui/images/bg-circles.png
  ui/lib/images.ts
  ui/lib/theme.ts
  ui/typedefs/styled.d.ts
Labels: ui

#2599 Fix `get bycrypt-hash` reading of stdin
  cmd/gitops/get/bcrypt/cmd.go
Labels: bug

#2548 document installing agent with WGE and update agent docs
  website/docs/installation.mdx
  website/docs/policy/getting-started.mdx
  website/docs/policy/weave-policy-profile.mdx
Labels: exclude from release notes

#2519 docs: Removes the word "test" from the example WGE ClusterRoleBinding
  website/docs/cluster-management/assets/rbac/wego-admin.yaml
  website/docs/policy/assets/bootstrap/calico-crs-configmap.yaml
  website/docs/policy/assets/bootstrap/calico-crs.yaml
  website/docs/policy/assets/bootstrap/capi-gitops-cluster-bootstrap-config.yaml
  website/docs/policy/assets/profiles/profile-repo.yaml
  website/docs/policy/assets/rbac/wego-admin.yaml
  website/docs/policy/assets/templates/.keep
  website/docs/policy/assets/templates/capd-template.yaml
  website/versioned_docs/version-0.9.1/cluster-management/assets/rbac/wego-admin.yaml
Labels: exclude from release notes

#2588 Report broken main branch in #team-denim
  .github/workflows/pr.yaml
Labels: exclude from release notes

#2611 auth: Revert to the old auth method order
  pkg/server/auth/auth.go
Labels: bug

#2573 [UI,BE] Filter resources by tenant
  api/core/core.swagger.json
  api/core/types.proto
  charts/gitops-server/values.yaml
  cmd/gitops-server/cmd/cmd.go
  core/server/helm_release.go
  core/server/kustomization.go
  core/server/objects.go
  core/server/sources.go
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/gitrepository_test.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/helmrelease_test.go
  core/server/types/helmrepository.go
  core/server/types/helmrepository_test.go
  core/server/types/kustomization.go
  core/server/types/kustomization_test.go
  core/server/types/objects.go
  core/server/types/ocirepository.go
  core/server/utils.go
  pkg/api/core/types.pb.go
  pkg/featureflags/featureflags.go
  tools/helm-values-dev.yaml
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/OCIRepositoryDetail.tsx
  ui/components/SourcesTable.tsx
  ui/hooks/featureflags.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/objects.ts
Labels: enhancement

#2571 docs: Aligning creation docs for existing cluster with CAPI
  website/docs/cluster-management/managing-existing-clusters.mdx
  website/versioned_docs/version-0.9.1/cluster-management/managing-existing-clusters.mdx
  website/versioned_docs/version-0.9.2/cluster-management/managing-existing-clusters.mdx
  website/versioned_docs/version-0.9.3/cluster-management/managing-existing-clusters.mdx
Labels: exclude from release notes

#2605 Add Nav Styles
  ui/components/Flex.tsx
  ui/components/Icon.tsx
  ui/components/Layout.tsx
  ui/components/Link.tsx
  ui/components/Nav.tsx
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/components/__tests__/__snapshots__/Version.test.tsx.snap
  ui/images/flux-icon-hover.svg
  ui/images/flux-icon.svg
  ui/lib/images.ts
Labels: ui

#2613 Fix spacing of nodes with child nodes
  ui/components/ReconciliationGraph.tsx
Labels: bug, team/denim

#2615 Update getTenant to GetTenant
  core/server/helm_release.go
  core/server/kustomization.go
  core/server/objects.go
  core/server/sources.go
  core/server/utils.go
Labels: exclude from release notes

#2620 Log when a resource is suspended or synced
  core/server/suspend.go
  core/server/sync.go
Labels: enhancement

#2604 Return Added and Removed Clusters in Clusters.Set()
  core/clustersmngr/factory_caches.go
  core/clustersmngr/factory_caches_test.go
Labels: enhancement, team/pesto

#2616 ui: Make source details do http requests from the top, too
  ui/components/BucketDetail.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/OCIRepositoryDetail.tsx
  ui/components/SourceDetail.tsx
  ui/hooks/objects.ts
  ui/lib/__tests__/utils.test.ts
  ui/lib/objects.ts
  ui/lib/utils.ts
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
  ui/pages/v2/OCIRepositoryPage.tsx
Labels: ui

#2590 Raise an error if an empty `UserPrincipal` is passed to `ClientConfigWithUser`
  core/clustersmngr/client_test.go
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/clustersmngr_test.go
  core/server/suite_test.go
  pkg/server/auth/auth.go
  pkg/server/auth/auth_test.go
Labels: bug

#2626 Make the whole release flow use the release commit
  .github/workflows/release.yaml
Labels: bug

#2625 fix log message
  cmd/gitops-server/cmd/cmd.go
Labels: bug

#2627 ui: PageStatus should display Failed when state is bad
  .eslintrc
  ui/components/PageStatus.tsx
  ui/components/SourcesTable.tsx
Labels: bug

#2609 CLI command for creating GitOps Dashboard
  .prettierignore
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/cmderrors/errors.go
  cmd/gitops/create/cmd.go
  cmd/gitops/create/dashboard/cmd.go
  cmd/gitops/root/cmd.go
  go.mod
  pkg/run/forward_port.go
  pkg/run/forward_port_test.go
  pkg/run/install_dashboard.go
  pkg/run/install_dashboard_test.go
  pkg/run/install_dev_bucket_server.go
  website/docs/getting-started.mdx
Labels: enhancement, team/denim

#2633 Re-add a missing link to the Getting Started guide
  website/docs/getting-started.mdx
Labels: exclude from release notes, team/denim

#2636 Fix install
  website/docs/installation.mdx
  website/versioned_docs/version-0.9.3/installation.mdx
Labels: documentation, exclude from release notes

#2641 Hide the cluster column in WG OSS
  charts/gitops-server/values.yaml
  tools/helm-values-dev.yaml
  ui/components/AutomationsTable.tsx
  ui/components/BucketDetail.tsx
  ui/components/ControllersTable.tsx
  ui/components/CrdsTable.tsx
  ui/components/GitRepositoryDetail.tsx
  ui/components/HelmChartDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/HelmRepositoryDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/OCIRepositoryDetail.tsx
  ui/components/SourcesTable.tsx
  ui/hooks/featureflags.ts
Labels: enhancement, team/denim

#2644 ui: Fix sort by Reason or Timestamp in the Events table
  ui/components/EventsTable.tsx
Labels: bug, team/denim

#2581 Add ADR-15 summarising current auth strategy
  doc/adr/0005-wego-core-auth-strategy.md
  doc/adr/0015-current-api-authentication-strategy.md
Labels: documentation, exclude from release notes

#2646 ui: Fix sort direction not reversed sometimes when clicking on the header of a selected sort column
  ui/components/DataTable.tsx
Labels: bug, team/denim

#2645 Make feature flags part of context
  ui/components/__tests__/Page.test.tsx
  ui/contexts/CoreClientContext.tsx
  ui/contexts/__tests__/CoreClientContext.test.tsx
  ui/hooks/featureflags.ts
Labels: ui

#2653 add vscode setting folder to gitignore
  .gitignore
Labels: exclude from release notes

#2639 doc: add multi tenancy
  website/docs/enterprise/multi-tenancy.mdx
Labels: documentation, exclude from release notes

#2654 ui: Sort events by newest first
  ui/components/DataTable.tsx
  ui/components/EventsTable.tsx
Labels: enhancement, team/denim

#2655 clustersmngr: Reduce the number of ways we create cluster configs
  core/clustersmngr/clustersmngr.go
  core/clustersmngr/factory.go
Labels: bug

#2638 GetProfiles and GetProfileValues to accept HelmRepo details
  api/profiles/profiles.proto
  api/profiles/profiles.swagger.json
  pkg/api/profiles/profiles.pb.go
  pkg/api/profiles/profiles.pb.gw.go
  pkg/server/profiles.go
  pkg/server/profiles_test.go
  ui/lib/api/profiles/profiles.pb.ts
Labels: enhancement

#2652 Initial pendo integration
  cmd/gitops-server/cmd/cmd.go
  core/server/server.go
  package-lock.json
  package.json
  pkg/server/auth/init.go
  pkg/server/auth/init_test.go
  pkg/telemetry/telemetry.go
  tools/helm-values-dev.yaml
  ui/App.tsx
  ui/components/Pendo.tsx
Labels: enhancement

#2659 Remove extra top padding
  ui/components/Layout.tsx
  ui/components/UserSettings.tsx
Labels: ui

#2624 Passthrough token
  Makefile
  cmd/gitops-server/cmd/cmd.go
  core/clustersmngr/clustersmngr_test.go
  core/clustersmngr/factory.go
  pkg/git/gogit.go
  pkg/helm/charts.go
  pkg/helm/charts_test.go
  pkg/kube/config_getter.go
  pkg/runner/runner_suite_test.go
  pkg/server/auth/auth.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/jwt.go
  pkg/server/auth/jwt_test.go
  pkg/server/auth/passthrough.go
  pkg/server/auth/passthrough_test.go
  pkg/server/auth/server.go
  pkg/server/server_test.go
  pkg/services/auth/github.go
  pkg/services/auth/gitlab_test.go
  pkg/services/gitrepo/service.go
  pkg/utils/common.go
  pkg/utils/common_test.go
Labels: enhancement, customer issue

#2663 Fix titles overflowing graph nodes
  ui/components/GraphNode.tsx
  ui/lib/theme.ts
Labels: ui

#2662 Fixes apps/sources working for clusters that are reachable
  core/clustersmngr/factory.go
  core/clustersmngr/factory_test.go
Labels: exclude from release notes

#2668 Update exports for EE
  ui/index.ts
Labels: exclude from release notes

#2665 Exit more gracefully in ListHelmReleases when a HelmRelease revision is missing
  core/server/helm_release.go
  core/server/helm_release_test.go
Labels: bug

#2669 Fix error logs in UI tests
  package-lock.json
  package.json
  ui/contexts/CoreClientContext.tsx
  ui/lib/test-utils.tsx
Labels: bug

#2649 Suspend/Resume All
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/fluxruntime.go
  core/server/suspend.go
  core/server/suspend_test.go
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/helmchart.go
  core/server/types/helmrelease.go
  core/server/types/helmrepository.go
  core/server/types/kustomization.go
  core/server/types/ocirepository.go
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/AutomationsTable.tsx
  ui/components/Button.tsx
  ui/components/CheckboxActions.tsx
  ui/components/ControllersTable.tsx
  ui/components/CrdsTable.tsx
  ui/components/DataTable.tsx
  ui/components/FilterDialog.tsx
  ui/components/FilterableTable.tsx
  ui/components/Icon.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/SourceDetail.tsx
  ui/components/SourcesTable.tsx
  ui/components/URLAddressableTable.tsx
  ui/components/__tests__/Breadcrumbs.test.tsx
  ui/components/__tests__/CheckboxActions.test.tsx
  ui/components/__tests__/DataTable.test.tsx
  ui/components/__tests__/DataTableFilters.test.tsx
  ui/components/__tests__/FilterDialog.test.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/hooks/flux.ts
  ui/index.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/objects.ts
Labels: ui

#2658 Add listObjects, make sources table use it
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/objects.go
  core/server/objects_test.go
  core/server/sources.go
  core/server/sources_test.go
  core/server/suite_test.go
  core/server/types/bucket.go
  core/server/types/gitrepository.go
  core/server/types/gitrepository_test.go
  core/server/types/helmrepository.go
  core/server/types/helmrepository_test.go
  core/server/types/objects.go
  core/server/types/ocirepository.go
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  ui/components/SourceDetail.tsx
  ui/components/SourcesTable.tsx
  ui/hooks/objects.ts
  ui/hooks/sources.ts
  ui/lib/__tests__/objects.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/objects.ts
Labels: enhancement

#2671 Remove the label error flow
  .github/workflows/label.yaml
Labels: exclude from release notes

#2621 security documentation added for vulnerability management process
  website/docusaurus.config.js
  website/src/pages/security/cve/enterprise/CVE-2022-38790.md
  website/src/pages/security/index.md
Labels: enhancement

#2651 Update user-guide to mention ocirepositories in permissions
  website/docs/cluster-management/assets/rbac/wego-admin.yaml
  website/docs/configuration/recommended-rbac-configuration.mdx
  website/docs/configuration/user-permissions.mdx
  website/docs/guides/setting-up-dex.md
Labels: exclude from release notes

#2660 Install core cli
  tools/update-docs.sh
  website/docs/getting-started.mdx
  website/docs/installation.mdx
  website/versioned_docs/version-0.9.3/getting-started.mdx
  website/versioned_docs/version-0.9.3/installation.mdx
Labels: documentation, exclude from release notes
