Repository weaveworks/weave-gitops, pull requests merged in 2022-10, with the labels that each got.

#2793 documentation added for pipelines
  website/docs/enterprise/pipelines/_category_.json
  website/docs/enterprise/pipelines/authorization.mdx
  website/docs/enterprise/pipelines/getting-started.mdx
  website/docs/enterprise/pipelines/img/view-pipeline-details.png
  website/docs/enterprise/pipelines/img/view-pipelines.png
  website/docs/enterprise/pipelines/intro.mdx
  website/docs/enterprise/pipelines/spec/_category_.json
  website/docs/enterprise/pipelines/spec/v1alpha1/pipeline.mdx
  website/docs/enterprise/releases.mdx
Labels: documentation

#2800 Add yaml pop-ups for objects that aren't flux primitives
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  go.mod
  go.sum
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  ui/components/AlertsTable.tsx
  ui/components/AutomationDetail.tsx
  ui/components/DependenciesView.tsx
  ui/components/Footer.tsx
  ui/components/GraphNode.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/SourcesTable.tsx
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/contexts/AppContext.tsx
  ui/hooks/__tests__/flux.test.tsx
  ui/hooks/flux.ts
  ui/lib/__tests__/dependencies.test.ts
  ui/lib/__tests__/graph.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/graph.ts
  ui/lib/nav.ts
  ui/lib/objects.ts
Labels: ui

#2835 Fix styling bug on filter chips
  ui/components/ChipGroup.tsx
  ui/components/DataTable.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
Labels: ui

#2855 Revert "Add LinkResolver for customized routing when running as "embedded""
  ui/components/ReconciledObjectsTable.tsx
  ui/contexts/AppContext.tsx
  ui/contexts/LinkResolverContext.tsx
  ui/contexts/__tests__/LinkResolverContext.test.tsx
  ui/index.ts
  ui/pages/OAuthCallback.tsx
Labels: exclude from release notes

#2852 gitops run: Add silly little struct for paths
  cmd/gitops/beta/run/cmd.go
  pkg/run/install/install.go
  pkg/run/paths.go
Labels: exclude from release notes

#2859 minor rewording
  README.md
Labels: exclude from release notes

#2860 Make it possible to set env vars for flux exec & bootstrap
  pkg/fluxexec/bootstrap_bitbucket.go
  pkg/fluxexec/bootstrap_github.go
  pkg/fluxexec/bootstrap_gitlab.go
  pkg/fluxexec/fluxexec.go
Labels: exclude from release notes

#2832 update ListFluxCrds to support querying multiple clusters
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
Labels: enhancement

#2853 gitops run bootstrapping
  cmd/gitops/beta/run/cmd.go
  pkg/run/bootstrap/bootstrap.go
  pkg/run/bootstrap/bootstrap_wizard.go
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_dashboard_test.go
  pkg/run/install/session.go
  pkg/run/paths.go
Labels: enhancement

#2869 update status icons used in tables update user setting style
  ui/components/DataTable.tsx
  ui/components/Icon.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/components/SubRouterTabs.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
Labels: ui

#2871 fix bootstrapping process in the session mode
  cmd/gitops/beta/run/cmd.go
  pkg/run/install/session.go
Labels: team/denim

#2894 Add WGE v0.9.6 release notes to docs
  website/docs/enterprise/releases.mdx
  website/versioned_docs/version-0.10.0/enterprise/releases.mdx
  website/versioned_docs/version-0.9.6/enterprise/releases.mdx
Labels: documentation

#2905 gitops-run: Session names have to be lower-case
  cmd/gitops/beta/run/cmd.go
Labels: bug

#2919 reset signal in session
  pkg/run/install/session.go
Labels: team/denim

#2926 Update installation.mdx
  website/docs/installation.mdx
  website/versioned_docs/version-0.10.0/installation.mdx
Labels: documentation, exclude from release notes

#2924 Fix overlapping UI elements in bootstrap wizard if height of terminal window is insufficient
  package-lock.json
  pkg/run/bootstrap/bootstrap_wizard.go
  pkg/run/bootstrap/bootstrap_wizard_ui.go
Labels: bug, team/denim

#2930 Fix displaying bootstrap wizard error message
  pkg/run/bootstrap/bootstrap_wizard.go
  pkg/run/bootstrap/bootstrap_wizard_ui.go
Labels: exclude from release notes, team/denim

#2931 Replace text inputs with checkboxes in the bootstrap wizard UI
  pkg/run/bootstrap/bootstrap_wizard.go
  pkg/run/bootstrap/bootstrap_wizard_ui.go
Labels: enhancement, team/denim

#2940 Fix the last input not highlighted on focus properly.
  pkg/run/bootstrap/bootstrap_wizard_ui.go
Labels: exclude from release notes, team/denim

#2807 user-guide: Templates organization
  website/docs/assets/templates/.keep
  website/docs/assets/templates/capd-template.yaml
  website/docs/cluster-management/getting-started.mdx
  website/docs/cluster-management/templates.mdx
  website/docs/gitops-templates/_category_.json
  website/docs/gitops-templates/templates.mdx
  website/docs/guides/assets/templates/capa-template.yaml
  website/docs/guides/deploying-capa.mdx
Labels: documentation

#2950 new issue template - feature request
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, exclude from release notes
