Repository weaveworks/weave-gitops, pull requests merged in 2022-09, with the labels that each got.

#2679 Fix displaying errors with useListSources
  ui/hooks/sources.ts
Labels: bug

#2622 implement installer and exec packages for flux cli
  go.mod
  pkg/fluxexec/README.md
  pkg/fluxexec/bootstrap.go
  pkg/fluxexec/bootstrap_github.go
  pkg/fluxexec/bootstrap_github_test.go
  pkg/fluxexec/cmd.go
  pkg/fluxexec/cmd_default.go
  pkg/fluxexec/errors.go
  pkg/fluxexec/exit_errors.go
  pkg/fluxexec/fluxexec.go
  pkg/fluxexec/fluxexec_suite_test.go
  pkg/fluxexec/install.go
  pkg/fluxexec/install_test.go
  pkg/fluxexec/option_consts.go
  pkg/fluxexec/options.go
  pkg/fluxinstall/errors/errors.go
  pkg/fluxinstall/fluxinstall_suite_test.go
  pkg/fluxinstall/installer.go
  pkg/fluxinstall/installer_test.go
  pkg/fluxinstall/internal/httpclient/httpclient.go
  pkg/fluxinstall/internal/src/src.go
  pkg/fluxinstall/product.go
  pkg/fluxinstall/product_test.go
  pkg/fluxinstall/src/src.go
Labels: enhancement

#2685 Add Sync All functionality
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/suspend_test.go
  core/server/sync.go
  core/server/sync_test.go
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/CheckboxActions.tsx
  ui/components/SourceDetail.tsx
  ui/hooks/automations.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
Labels: ui

#2701 flux-exec: implement bootstrap gitlab and global flags
  pkg/fluxexec/bootstrap_github.go
  pkg/fluxexec/bootstrap_github_test.go
  pkg/fluxexec/bootstrap_gitlab.go
  pkg/fluxexec/bootstrap_gitlab_test.go
  pkg/fluxexec/global.go
  pkg/fluxexec/options_for_global.go
Labels: enhancement

#2637 Update `UpdateClusters` to notify watchers with the added and removed clusters
  cmd/gitops-server/cmd/cmd.go
  core/clustersmngr/clustersmngrfakes/fake_clusters_manager.go
  core/clustersmngr/factory.go
  core/clustersmngr/factory_test.go
  core/server/events.go
  core/server/featureflags_test.go
  core/server/fluxruntime.go
  core/server/helm_release.go
  core/server/kustomization.go
  core/server/objects.go
  core/server/server.go
  core/server/suite_test.go
  core/server/suspend.go
  core/server/sync.go
  core/server/version.go
  pkg/telemetry/telemetry.go
Labels: enhancement, team/pesto

#2677 Add Notification Providers
  buf.lock
  charts/gitops-server/templates/admin-user-roles.yaml
  core/server/primarykinds.go
  go.mod
  go.sum
  ui/App.tsx
  ui/components/DataTable.tsx
  ui/components/ErrorBoundary.tsx
  ui/components/ErrorPage.tsx
  ui/components/FilterDialog.tsx
  ui/components/Nav.tsx
  ui/components/NotificationsTable.tsx
  ui/components/Page.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/hooks/notifications.ts
  ui/hooks/objects.ts
  ui/lib/nav.ts
  ui/lib/objects.ts
  ui/lib/types.ts
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmReleasePage.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
  ui/pages/v2/KustomizationPage.tsx
  ui/pages/v2/Notifications.tsx
  ui/pages/v2/OCIRepositoryPage.tsx
Labels: ui

#2608 Update policy agent configuration document
  website/docs/policy/weave-policy-profile.mdx
Labels: exclude from release notes

#2717 update CLI ref link in readme
  README.md
Labels: exclude from release notes

#2719 gitops run: Don't abort uploading on error
  pkg/run/install_bucket_source_and_ks.go
Labels: bug

#2715 flux-exec: add wrapper for bootstrap git
  pkg/fluxexec/bootstrap_git.go
  pkg/fluxexec/bootstrap_git_test.go
  pkg/fluxexec/options.go
Labels: team/denim

#2718 gitops run: Abort if dev-bucket resources couldn't be installed
  pkg/run/install_bucket_source_and_ks.go
Labels: bug

#2714 Add filtering by undefined and fix searching by name
  ui/components/ChipGroup.tsx
  ui/components/DataTable.tsx
  ui/components/FilterDialog.tsx
  ui/components/__tests__/ChipGroup.test.tsx
  ui/components/__tests__/DataTable.test.tsx
  ui/components/__tests__/DataTableFilters.test.tsx
  ui/components/__tests__/FilterDialog.test.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
Labels: ui

#2680 Add cluster kind annotations in getting started docs
  website/docs/cluster-management/getting-started.mdx
Labels: documentation

#2728 Automate upgrading flux
  .github/workflows/upgrade-flux.yaml
Labels: exclude from release notes

#2730 ci: Run go mod tidy when upgrading flux
  .github/workflows/upgrade-flux.yaml
Labels: exclude from release notes

#2732 Automate updating the helm chart in gitops run, remove mentions of flux 0.31
  .github/workflows/release.yaml
  .goreleaser.yml
  Makefile
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/values.yaml
  cmd/gitops/beta/run/cmd.go
  website/docs/getting-started.mdx
  website/docs/installation.mdx
Labels: exclude from release notes

#2727 remove display name annotation from docs
  website/docs/cluster-management/templates.mdx
Labels: documentation, exclude from release notes

#2705 adding add application section to docs
  website/docs/cluster-management/add-applications.mdx
  website/docs/cluster-management/img/add-application-btn.png
  website/docs/cluster-management/img/add-application-form.png
  website/docs/cluster-management/img/add-application-helm-release.png
  website/docs/cluster-management/img/add-application-kustomization.png
  website/docs/cluster-management/img/add-application-select-source.png
Labels: documentation

#2713 2486 dependency tab on workloads page
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/objects.go
  core/server/objects_test.go
  core/server/types/helmrelease.go
  core/server/types/helmrelease_test.go
  core/server/types/kustomization.go
  core/server/types/kustomization_test.go
  package-lock.json
  package.json
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/AutomationsTable.tsx
  ui/components/DagGraph.tsx
  ui/components/DependenciesView.tsx
  ui/components/DirectedGraph.tsx
  ui/components/Flex.tsx
  ui/components/GraphNode.tsx
  ui/components/ReconciliationGraph.tsx
  ui/components/SourceDetail.tsx
  ui/hooks/automations.ts
  ui/hooks/objects.ts
  ui/index.ts
  ui/lib/__tests__/dependencies.test.ts
  ui/lib/__tests__/utils.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/dependencies.ts
  ui/lib/objects.ts
  ui/lib/utils.ts
Labels: enhancement, team/denim

#2739 Bump the Helm Chart
  charts/gitops-server/Chart.yaml
Labels: exclude from release notes

#2744 Add help message when user has no notifications
  ui/components/NotificationsTable.tsx
  ui/pages/v2/Notifications.tsx
Labels: ui

#2735 Link to filtered tables from alert event sources
  ui/components/AlertsTable.tsx
  ui/components/__tests__/AlertsTable.test.tsx
Labels: ui

#2748 Add pop up for Alert yaml
  ui/components/AlertsTable.tsx
  ui/components/Text.tsx
  ui/components/YamlView.tsx
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
  ui/lib/theme.ts
Labels: ui

#2753 Add `.DS_Store` files to `.gitignore`.
  .gitignore
Labels: exclude from release notes

#2751 Make automation details use getObject instead of dedicated endpoints
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  core/server/helm_release.go
  core/server/helm_release_test.go
  core/server/kustomization.go
  core/server/kustomization_test.go
  core/server/objects.go
  core/server/objects_test.go
  core/server/types/objects.go
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
  ui/components/AutomationDetail.tsx
  ui/components/DependenciesView.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/ReconciliationGraph.tsx
  ui/hooks/automations.ts
  ui/index.ts
  ui/lib/__tests__/objects.test.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/objects.ts
  ui/pages/v2/HelmReleasePage.tsx
  ui/pages/v2/KustomizationPage.tsx
Labels: enhancement

#2760 Fix console warning about styled components
  ui/components/DependenciesView.tsx
  ui/lib/objects.ts
Labels: exclude from release notes

#2754 update tenancy doc with deployment RBAC
  website/docs/enterprise/multi-tenancy.mdx
Labels: exclude from release notes, team/pesto

#2523 docs: Delivery UI permissions
  website/docs/configuration/recommended-rbac-configuration.mdx
  website/docs/enterprise/multi-tenancy.mdx
  website/docs/enterprise/user-permissions.mdx
  website/versioned_docs/version-0.9.1/configuration/recommended-rbac-configuration.mdx
  website/versioned_docs/version-0.9.1/enterprise/user-permissions.mdx
  website/versioned_docs/version-0.9.2/configuration/recommended-rbac-configuration.mdx
  website/versioned_docs/version-0.9.2/enterprise/user-permissions.mdx
  website/versioned_docs/version-0.9.3/configuration/recommended-rbac-configuration.mdx
  website/versioned_docs/version-0.9.3/enterprise/user-permissions.mdx
  website/versioned_docs/version-0.9.4/configuration/recommended-rbac-configuration.mdx
  website/versioned_docs/version-0.9.4/enterprise/multi-tenancy.mdx
  website/versioned_docs/version-0.9.4/enterprise/user-permissions.mdx
  website/versioned_docs/version-0.9.5/configuration/recommended-rbac-configuration.mdx
  website/versioned_docs/version-0.9.5/enterprise/multi-tenancy.mdx
  website/versioned_docs/version-0.9.5/enterprise/user-permissions.mdx
Labels: documentation, exclude from release notes

#2769 Remove unused components
  .storybook/main.js
  .storybook/preview.js
  ui/components/FancyCard.tsx
  ui/components/Nav.tsx
  ui/images/fancy-card-background-blue.svg
  ui/images/fancy-card-background-orange.svg
  ui/images/fancy-card-background.svg
  ui/lib/images.ts
Labels: ui

#2733 Automatically raise PRs against EE when PRs are merged, released
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
Labels: exclude from release notes

#2773 Adds 'null' to undefined values in chips
  ui/components/ChipGroup.tsx
  ui/components/__tests__/ChipGroup.test.tsx
Labels: ui

#2774 Weave Gitops Enterprise v0.9.5 release notes
  website/docs/assets/example-enterprise-helm.yaml
  website/docs/enterprise/releases.mdx
  website/docs/installation.mdx
  website/versioned_docs/version-0.9.5/assets/example-enterprise-helm.yaml
  website/versioned_docs/version-0.9.5/enterprise/multi-tenancy.mdx
  website/versioned_docs/version-0.9.5/enterprise/releases.mdx
  website/versioned_docs/version-0.9.5/installation.mdx
Labels: exclude from release notes

#2762 Add audit frequency and policy library source reference documentation
  website/docs/policy/weave-policy-profile.mdx
Labels: exclude from release notes

#2776 Add useListProviders to exports for EE
  ui/index.ts
Labels: exclude from release notes

#2779 Change dashboard installation to use OCI
  pkg/run/install_dashboard.go
Labels: bug

#2781 helm: Add network policy
  charts/gitops-server/templates/network-policy.yaml
  charts/gitops-server/values.yaml
Labels: enhancement

#2780 Set security context that passes enforce:restricted pod security
  charts/gitops-server/values.yaml
Labels: enhancement

#2783 Add version and revision info to Helm detail pages
  ui/components/HelmChartDetail.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/lib/objects.ts
Labels: ui

#2791 #2790: enable adding annotations to the weave-gitops deployment
  charts/gitops-server/Chart.yaml
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/values.yaml
Labels: enhancement

#2799 Add additional Flex snapshot tests
  ui/components/__tests__/Flex.test.tsx
  ui/components/__tests__/__snapshots__/Flex.test.tsx.snap
Labels: exclude from release notes

#2798 Export the bootstrap wizard commands as flux-exec options
  cmd/gitops/beta/run/cmd.go
  pkg/run/bootstrap_wizard.go
  pkg/run/bootstrap_wizard_ui.go
Labels: exclude from release notes, team/denim

#2804 Split pkg/run into 3 packages
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/create/dashboard/cmd.go
  pkg/run/bootstrap/bootstrap_suite_test.go
  pkg/run/bootstrap/bootstrap_wizard.go
  pkg/run/bootstrap/bootstrap_wizard_ui.go
  pkg/run/forward_port_test.go
  pkg/run/install/apply_manifests.go
  pkg/run/install/apply_manifests_test.go
  pkg/run/install/install.go
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_dashboard_test.go
  pkg/run/install/install_flux.go
  pkg/run/install/install_flux_test.go
  pkg/run/install/install_suite_test.go
  pkg/run/install/install_test.go
  pkg/run/utils.go
  pkg/run/utils_test.go
  pkg/run/watch/dashboard.go
  pkg/run/watch/forward_port.go
  pkg/run/watch/install_bucket_source_and_ks.go
  pkg/run/watch/install_bucket_source_and_ks_test.go
  pkg/run/watch/install_dev_bucket_server.go
  pkg/run/watch/watch_suite_test.go
Labels: exclude from release notes

#2809 ui: Don't flatten children for the graph
  ui/components/ReconciliationGraph.tsx
  ui/hooks/flux.ts
Labels: bug

#2802 update filter options chip color
  ui/components/ChipGroup.tsx
  ui/components/DataTable.tsx
  ui/components/Page.tsx
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/lib/theme.ts
  ui/typedefs/styled.d.ts
Labels: exclude from release notes
