Repository weaveworks/weave-gitops, pull requests merged in 2023-04, with the labels that each got.

#3542 Use dynamic Secret name for admin credentials
  .prettierignore
  charts/gitops-server/templates/_helpers.tpl
  charts/gitops-server/templates/admin-user-creds.yaml
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/templates/role.yaml
  charts/gitops-server/values.yaml
  cmd/gitops-server/cmd/cmd.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/init.go
  pkg/server/auth/init_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
  tools/helm-values-dev.yaml
  website/docs/configuration/emergency-user.mdx
  website/docs/configuration/service-account-permissions.mdx
  website/docs/references/helm-reference.md
Labels: enhancement

#3583 Split up DataTable component and add column click handler (v2)
  ui/components/DataTable/DataTable.tsx
  ui/components/DataTable/SortableLabel.tsx
  ui/components/DataTable/__tests__/DataTable.test.tsx
  ui/components/DataTable/__tests__/DataTableFilters.test.tsx
  ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/DataTable/helpers.ts
  ui/components/DataTable/index.ts
  ui/components/DataTable/types.ts
  ui/components/__tests__/FilterDialog.test.tsx
Labels: exclude from release notes

#3569 Add Manage External Secretes UI docs
  website/docs/secrets/imgs/create-secret-1.png
  website/docs/secrets/imgs/create-secret-2.png
  website/docs/secrets/imgs/create-secret-3.png
  website/docs/secrets/imgs/create-secret-sops.png
  website/docs/secrets/imgs/eso-details-1.png
  website/docs/secrets/imgs/external-secret-events-1.png
  website/docs/secrets/imgs/secretes-overview-1.png
  website/docs/secrets/imgs/secrets-overview-2.png
  website/docs/secrets/imgs/sops-secret-pr.png
  website/docs/secrets/manage-secrets-gui.mdx
  website/docs/secrets/manage-secrets-ui.mdx
  website/sidebars.js
Labels: documentation

#3562 Dashboard reconciliation stuck when running GitOps Run in the no session mode with OSS dashboard already installed
  charts/gitops-server/templates/_helpers.tpl
  charts/gitops-server/templates/deployment.yaml
  cmd/gitops/beta/run/cmd.go
  core/server/fluxruntime_test.go
  core/server/inventory_test.go
  core/server/objects.go
  core/server/objects_test.go
  core/server/session_logs.go
  core/server/types/app.go
  core/server/version.go
  core/server/version_test.go
  pkg/flux/flux.go
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_dashboard_test.go
  pkg/run/install/install_flux.go
  pkg/run/install/install_flux_test.go
  pkg/run/install/install_vcluster.go
  pkg/run/session/get.go
  pkg/run/session/list.go
  pkg/run/utils_test.go
  pkg/run/watch/install_dev_bucket_server.go
Labels: bug

#3595 review hotfixes and typo fixes for docs
  website/docs/secrets/manage-secrets-ui.mdx
  website/docs/secrets/managing-secrets-with-sops.mdx
  website/docs/secrets/setup-secrets-operator.mdx
Labels: exclude from release notes

#3609 Swap out some nav icons
  ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/Icon.tsx
  ui/components/NavIcons/GitOpsRunIcon.tsx
  ui/components/NavIcons/NotificationsIcon.tsx
  ui/components/NavIcons/SourcesIcon.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
Labels: ui

#3612 docs: Add instructions on configuring WGE to create PRs in Azure DevOps
  website/docs/installation/weave-gitops-enterprise/index.mdx
  website/static/img/oauth-azure-devops-success.png
  website/static/img/oauth-azure-devops.png
Labels: documentation

#3618 Revert PR #3542
  Tiltfile
  charts/gitops-server/templates/_helpers.tpl
  charts/gitops-server/templates/admin-user-creds.yaml
  charts/gitops-server/templates/deployment.yaml
  charts/gitops-server/templates/role.yaml
  charts/gitops-server/values.yaml
  cmd/gitops-server/cmd/cmd.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/init.go
  pkg/server/auth/init_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
  tools/helm-values-dev.yaml
  website/docs/configuration/emergency-user.mdx
  website/docs/configuration/service-account-permissions.mdx
Labels: bug, exclude from release notes

#3620 Add docs for using a private helm repository in wge-profiles
  website/docs/cluster-management/getting-started.mdx
  website/docs/cluster-management/profiles.mdx
Labels: documentation

#3610 Wge 2693 - explorer documentation
  website/docs/explorer/configuration.mdx
  website/docs/explorer/getting-started.mdx
  website/docs/explorer/imgs/debug-access-rules.png
  website/docs/explorer/imgs/explorer-query-and.png
  website/docs/explorer/imgs/explorer-query-filter-cluster.png
  website/docs/explorer/imgs/explorer-query-filter-kind.png
  website/docs/explorer/imgs/explorer-query-overview.png
  website/docs/explorer/imgs/explorer-ui.png
  website/docs/explorer/imgs/getting-started-failed.png
  website/docs/explorer/imgs/getting-started-querying-app.png
  website/docs/explorer/intro.mdx
  website/docs/explorer/operations.mdx
  website/docs/explorer/querying.mdx
  website/sidebars.js
Labels: documentation, exclude from release notes

#3611 Add OIDC prefix support for impersonation
  cmd/gitops-server/cmd/cmd.go
  core/clustersmngr/client_test.go
  core/clustersmngr/cluster/single.go
  core/clustersmngr/cluster/single_test.go
  core/clustersmngr/factory_caches_test.go
  core/clustersmngr/factory_test.go
  core/clustersmngr/fetcher/single_test.go
  core/clustersmngr/suite_test.go
  core/nsaccess/nsaccess_test.go
  core/server/featureflags_test.go
  core/server/suite_test.go
  pkg/kube/config_getter.go
  pkg/kube/config_getter_test.go
  pkg/server/auth/server.go
  pkg/services/crd/suite_test.go
Labels: enhancement, team/pesto

#3623 Update frontend dev process docs
  doc/development-process.md
Labels: documentation

#3617 GitOps Run failing validation on non-Kubernetes yaml files
  cmd/gitops/beta/run/cmd.go
  go.mod
  go.sum
  pkg/run/watch/setup_dev_ks.go
  pkg/sourceignore/sourceignore.go
  pkg/sourceignore/sourceignore_test.go
  pkg/validate/validate.go
Labels: enhancement, gitops-run

#3640 Fix the vulnerability in the `yaml` NPM package
  package-lock.json
  package.json
  website/package.json
  website/yarn.lock
Labels: bug

#3654 Add WGE 0.22.0 release notes
  website/docs/assets/example-enterprise-helm.yaml
  website/docs/installation/weave-gitops-enterprise/index.mdx
  website/docs/releases.mdx
  website/versioned_docs/version-0.22.0/assets/example-enterprise-helm.yaml
  website/versioned_docs/version-0.22.0/installation/weave-gitops-enterprise/index.mdx
  website/versioned_docs/version-0.22.0/releases.mdx
Labels: documentation

#3643 adding authz documentation for collector
  website/docs/explorer/configuration.mdx
  website/docs/explorer/intro.mdx
  website/versioned_docs/version-0.22.0/explorer/configuration.mdx
  website/versioned_docs/version-0.22.0/explorer/intro.mdx
Labels: exclude from release notes

#3657 Update docs for explorer v22 configuration on `useQueryServiceBackend`
  website/docs/explorer/configuration.mdx
  website/docs/releases.mdx
  website/versioned_docs/version-0.22.0/explorer/configuration.mdx
  website/versioned_docs/version-0.22.0/releases.mdx
Labels: exclude from release notes
