Repository weaveworks/weave-gitops, pull requests merged in 2023-03, with the labels that each got.

#3450 review workspaces documentation
  website/docs/workspaces/imgs/list-workspaces-view.png
  website/docs/workspaces/imgs/workspace-details-view.png
  website/docs/workspaces/multi-tenancy.mdx
  website/docs/workspaces/view-workspaces.mdx
Labels: documentation

#3474 Bump 0.17 to 0.18
  website/docs/installation/weave-gitops-enterprise/index.mdx
  website/docs/releases.mdx
  website/versioned_docs/version-0.18.0/releases.mdx
Labels: documentation

#3465 docs: Add instruction for how to disable CAPI
  website/docs/cluster-management/disable-capi.mdx
  website/sidebars.js
Labels: documentation

#3452 Uninstall Fluent Bit when stopping a GitOps Run session
  cmd/gitops/beta/run/cleanup.go
  cmd/gitops/beta/run/cleanup_test.go
  cmd/gitops/beta/run/cmd.go
  core/server/session_logs_test.go
  pkg/run/install/install_fluent_bit.go
Labels: bug, gitops-run

#3455 docs: Add issue template for documentation
  .github/ISSUE_TEMPLATE/docs.md
Labels: documentation

#3481 Add clear docs link to navbar
  website/docs/references/helm-reference.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: documentation

#3467 docs: Tidy up the GitOpsTemplate docs
  website/docs/cluster-management/getting-started.mdx
  website/docs/gitops-templates/annotations.mdx
  website/docs/gitops-templates/capd-example.mdx
  website/docs/gitops-templates/cli.mdx
  website/docs/gitops-templates/create-cluster-example.mdx
  website/docs/gitops-templates/creating-templates.mdx
  website/docs/gitops-templates/intro.mdx
  website/docs/gitops-templates/params.mdx
  website/docs/gitops-templates/profiles.mdx
  website/docs/gitops-templates/quickstart-templates.mdx
  website/docs/gitops-templates/repo-rendered-paths.mdx
  website/docs/gitops-templates/supported-langs.mdx
  website/docs/gitops-templates/templates.mdx
  website/docs/gitops-templates/versions.mdx
  website/docs/guides/deploying-capa.mdx
  website/docs/intro-ee.mdx
  website/docs/pipelines/pipeline-templates.mdx
  website/docs/releases.mdx
  website/sidebars.js
Labels: documentation

#3454 docs: Minor improvements to custom metadata guide
  website/docs/getting-started/ui.mdx
  website/docs/guides/displaying-custom-metadata.mdx
  website/docs/installation/weave-gitops.mdx
  website/static/img/metadata-display.png
Labels: documentation

#3483 skip port-forward annotation when no port-forward is setup
  cmd/gitops/beta/run/cmd.go
  pkg/run/install/install_vcluster.go
  pkg/run/install/install_vcluster_test.go
Labels: bug

#3462 Add DetailModal component, and convert pop up YamlViews to use it
  ui/components/AlertsTable.tsx
  ui/components/AutomationDetail.tsx
  ui/components/DetailModal.tsx
  ui/components/FluxObjectsTable.tsx
  ui/components/GraphNode.tsx
  ui/components/Layout.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/YamlView.tsx
  ui/contexts/AppContext.tsx
  ui/lib/theme.ts
Labels: ui

#3468 Disconnect new nav from oss nav hooks and export it
  ui/components/DeliveryIcon.tsx
  ui/components/GitOpsRunIcon.tsx
  ui/components/Icon.tsx
  ui/components/ImageAutomationIcon.tsx
  ui/components/Layout.tsx
  ui/components/Logo.tsx
  ui/components/Nav.tsx
  ui/components/PipelinesIcon.tsx
  ui/components/SourcesIcon.tsx
  ui/components/TerraformIcon.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
  ui/index.ts
  ui/lib/nav.ts
  ui/lib/theme.ts
Labels: ui

#3498 Expand area that is clickable for logo and collapse in nav
  ui/components/Logo.tsx
  ui/components/Nav.tsx
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/lib/utils.ts
Labels: ui

#3471 docs: Tidy up the Policy docs
  website/docs/policy/authorization.mdx
  website/docs/policy/commit-time-checks.mdx
  website/docs/policy/configuration.mdx
  website/docs/policy/getting-started.mdx
  website/docs/policy/img/policy-ecosystem.png
  website/docs/policy/img/weave-policy-profile.png
  website/docs/policy/intro.mdx
  website/docs/policy/policy-configuration.mdx
  website/docs/policy/policy-set.mdx
  website/docs/policy/policy.mdx
  website/docs/policy/weave-policy-profile.mdx
  website/sidebars.js
Labels: documentation

#3515 Update GitOpsSets docs
  website/docs/gitopssets/features.mdx
  website/docs/gitopssets/git-generator.mdx
  website/docs/gitopssets/intro.mdx
  website/docs/gitopssets/list-generator.mdx
  website/docs/gitopssets/matrix-generator.mdx
  website/docs/gitopssets/pull-request-generator.mdx
Labels: documentation

#3516 Fix Sandbox Bypass vulnerability in Docusaurus
  website/package.json
  website/yarn.lock
Labels: exclude from release notes

#3511 Fix dashboard password prompt accepting an empty string as a
  cmd/gitops/beta/run/cmd.go
  pkg/run/install/install_dashboard.go
Labels: bug, gitops-run

#3518 Enable unparam linter
  .golangci.yaml
  cmd/gitops/beta/run/cmd.go
  cmd/gitops/remove/run/cmd.go
  core/clustersmngr/client_test.go
  core/clustersmngr/cluster/delegating_cache.go
  core/clustersmngr/factory.go
  core/nsaccess/nsaccess.go
  core/server/crd_test.go
  core/server/events_test.go
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/objects.go
  core/server/server.go
  core/server/session_logs.go
  core/server/suite_test.go
  core/server/suspend_test.go
  core/server/sync_test.go
  core/server/version_test.go
  pkg/fluxexec/bootstrap_bitbucket.go
  pkg/fluxexec/bootstrap_bitbucket_test.go
  pkg/fluxexec/bootstrap_git.go
  pkg/fluxexec/bootstrap_git_test.go
  pkg/fluxexec/bootstrap_github.go
  pkg/fluxexec/bootstrap_github_test.go
  pkg/fluxexec/bootstrap_gitlab.go
  pkg/fluxexec/bootstrap_gitlab_test.go
  pkg/fluxexec/install.go
  pkg/fluxexec/install_test.go
  pkg/gitproviders/provider_org.go
  pkg/run/install/apply_manifests.go
  pkg/run/install/install_fluent_bit.go
  pkg/run/install/install_vcluster.go
  pkg/run/install/install_vcluster_test.go
  pkg/run/session/connect/connect.go
  pkg/run/session/localkubernetes/configure.go
  pkg/server/auth/server_test.go
  pkg/services/crd/fetcher.go
  pkg/services/crd/fetcher_test.go
  pkg/services/crd/suite_test.go
Labels: enhancement

#3520 Enabled additional linters
  .golangci.yaml
  cmd/gitops-server/cmd/cmd.go
  cmd/gitops/beta/run/cleanup.go
  core/clustersmngr/client.go
  core/clustersmngr/cluster/single_test.go
  core/logger/logger.go
  core/nsaccess/nsaccess_test.go
  core/server/fluxruntime.go
  core/server/objects.go
  core/server/session_logs.go
  core/server/suspend_test.go
  core/server/types/objects.go
  pkg/config/config.go
  pkg/flux/flux_test.go
  pkg/fluxexec/fluxexec.go
  pkg/fluxinstall/product.go
  pkg/fluxinstall/product_test.go
  pkg/git/git.go
  pkg/git/gogit.go
  pkg/git/gogit_test.go
  pkg/gitproviders/dryrun.go
  pkg/gitproviders/provider.go
  pkg/gitproviders/provider_org.go
  pkg/gitproviders/provider_user.go
  pkg/gitproviders/repo_url.go
  pkg/kube/kubehttp.go
  pkg/logger/logger.go
  pkg/run/bootstrap/bootstrap_wizard.go
  pkg/run/bootstrap/bootstrap_wizard_ui.go
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_fluent_bit.go
  pkg/run/install/install_vcluster.go
  pkg/run/install/install_vcluster_test.go
  pkg/run/paths.go
  pkg/run/session/connect/connect.go
  pkg/run/session/connect/delete.go
  pkg/run/session/connect/utils.go
  pkg/run/session/find/find.go
  pkg/run/session/get.go
  pkg/run/session/localkubernetes/configure.go
  pkg/run/session/portforward/portforward.go
  pkg/run/session/portforward/start.go
  pkg/run/unused_ports.go
  pkg/run/watch/dashboard.go
  pkg/run/watch/forward_port.go
  pkg/run/watch/setup_dev_ks.go
  pkg/s3/auth_middleware.go
  pkg/server/auth/init.go
  pkg/server/auth/passthrough.go
  pkg/services/auth/auth.go
  pkg/services/auth/internal/verifier.go
  pkg/testutils/grpc_error_matcher.go
  pkg/testutils/testutils.go
  pkg/utils/common_test.go
  pkg/utils/string.go
  pkg/validate/validate.go
Labels: enhancement, ci

#3521 Docs: add new feature to git generator
  website/docs/gitopssets/git-generator.mdx
  website/versioned_docs/version-0.18.0/gitopssets/git-generator.mdx
Labels: documentation

#3525 Flaky test when running curl to a Flux URL
  .github/workflows/pr.yaml
Labels: bug, ci

#3538 Add key to text labels in Nav
  ui/components/Nav.tsx
Labels: ui, exclude from release notes

#3539 Support yaml commands for objects without a namespace
  ui/components/FormCheckbox.tsx
  ui/components/YamlView.tsx
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
  ui/index.ts
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: ui

#3541 Scroll nav at small screen heights
  ui/components/Nav.tsx
Labels: ui

#3557 add rlock to clustermgr hash to avoid a race condition
  core/clustersmngr/factory_caches.go
Labels: bug

#3559 Vertically center enterprise nav header text
  ui/components/Nav.tsx
Labels: exclude from release notes

#3524 Add detail page for Pods
  api/core/types.proto
  pkg/api/core/types.pb.go
  ui/components/DataTable.tsx
  ui/components/DetailModal.tsx
  ui/components/GraphNode.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/components/MuiTab.tsx
  ui/components/PageStatus.tsx
  ui/components/PodDetail.tsx
  ui/components/SubRouterTabs.tsx
  ui/components/SyncButton.tsx
  ui/hooks/inventory.ts
  ui/hooks/objects.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/objects.ts
  ui/lib/theme.ts
  ui/pages/v2/PodPage.tsx
Labels: ui

#3567 Fix Pendo initialization
  ui/components/Pendo.tsx
Labels: bug

#3574 Updating the props to meet what EE needs
  ui/components/AutomationDetail.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/ReconciliationGraph.tsx
  ui/hooks/inventory.ts
Labels: ui

#3577 Export Graph to be used in EE
  ui/components/Pendo.tsx
  ui/components/ReconciliationGraph.tsx
  ui/index.ts
Labels: exclude from release notes

#3579 Use custom svgs instead of MUI for Nav icons
  ui/components/Icon.tsx
  ui/components/Layout.tsx
  ui/components/Nav.tsx
  ui/components/NavIcons/ApplicationsIcon.tsx
  ui/components/NavIcons/ClustersIcon.tsx
  ui/components/NavIcons/DeliveryIcon.tsx
  ui/components/NavIcons/DocsIcon.tsx
  ui/components/NavIcons/FluxIcon.tsx
  ui/components/NavIcons/GitOpsRunIcon.tsx
  ui/components/NavIcons/GitOpsSetsIcon.tsx
  ui/components/NavIcons/ImageAutomationIcon.tsx
  ui/components/NavIcons/NotificationsIcon.tsx
  ui/components/NavIcons/PipelinesIcon.tsx
  ui/components/NavIcons/PoliciesIcon.tsx
  ui/components/NavIcons/PolicyConfigsIcon.tsx
  ui/components/NavIcons/SecretsIcon.tsx
  ui/components/NavIcons/SourcesIcon.tsx
  ui/components/NavIcons/TemplatesIcon.tsx
  ui/components/NavIcons/TerraformIcon.tsx
  ui/components/NavIcons/WorkspacesIcon.tsx
  ui/components/Pendo.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
  ui/images/flux-icon-hover.svg
  ui/images/flux-icon.svg
  ui/index.ts
  ui/lib/images.ts
Labels: ui

#3476 add bootstrapping secrets page
  website/docs/secrets/bootstraping-secrets.mdx
  website/docs/secrets/spec/index.mdx
  website/docs/secrets/spec/v1alpha1/secretSync.mdx
  website/sidebars.js
Labels: exclude from release notes
