Repository weaveworks/weave-gitops, pull requests merged in 2023-12, with the labels that each got.

#4147 Add comment to suspend action
  ui/components/InfoModal.tsx
  ui/components/Modal.tsx
  ui/components/Sync/CheckboxActions.tsx
  ui/components/Sync/SuspendMessageModal.tsx
  ui/components/Sync/SyncActions.tsx
Labels: type/enhancement

#4161 update homebrew configuration for ruby 3
  .goreleaser.brew.yml
Labels: exclude from release notes, ci

#4160 add docs for extra controllers for WGE onboarding CLI
  website/docs/enterprise/getting-started/install-enterprise-cli.mdx
  website/versioned_docs/version-0.38.0/enterprise/getting-started/install-enterprise-cli.mdx
Labels: documentation

#4163 adding export documentation to bootstrapping command
  website/docs/enterprise/getting-started/install-enterprise-cli.mdx
Labels: documentation

#4164 removed blanks for install cli docs flags when no short flag
  website/docs/enterprise/getting-started/install-enterprise-cli.mdx
Labels: documentation

#4171 backported enterprise release changes to v0.38 so it has 0.38 and 0.38.1
  website/versioned_docs/version-0.38.0/enterprise/getting-started/releases-enterprise.mdx
Labels: documentation

#4162 allow extending flux runtime ui beyond flux to create gitops runtime
  api/core/core.proto
  api/core/core.swagger.json
  charts/gitops-server/values.yaml
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/session_logs.go
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/run/install/install_flux_test.go
  tools/helm-values-dev.yaml
  ui/App.tsx
  ui/components/FluxRuntime.tsx
  ui/hooks/flux.ts
  ui/index.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/types.ts
  ui/pages/v2/Runtime.tsx
  website/docs/open-source/getting-started/install-OSS.mdx
  website/docs/open-source/getting-started/ui-OSS.mdx
  website/static/img/dashboard-flux-runtime-terraform-crds.png
  website/static/img/dashboard-flux-runtime-versions.png
Labels: type/enhancement

#4181 Add support for V2Routes.Runtime in navigation getParentNavRouteValue
  ui/lib/nav.ts
Labels: area/ui, exclude from release notes
