Repository weaveworks/weave-gitops, pull requests merged in 2023-08, with the labels that each got.

#3887 Verified sources
  CONTRIBUTING.MD
  ui/components/AutomationsTable.tsx
  ui/components/SourcesTable.tsx
  ui/components/UserSettings.tsx
  ui/components/VerifiedStatus.tsx
  ui/lib/objects.ts
Labels: enhancement

#3905 update upgrade fluxga docs to get ready for v0.29 release
  website/docs/guides/fluxga-upgrade.mdx
Labels: exclude from release notes

#3540 Extending pipeline promotions token security documentation
  website/docs/pipelines/img/pipeline-security-violations.png
  website/docs/pipelines/promoting-applications.mdx
  website/versioned_docs/version-0.29.0/pipelines/img/pipeline-security-violations.png
  website/versioned_docs/version-0.29.0/pipelines/promoting-applications.mdx
Labels: exclude from release notes

#3914 added wge v0.29 release notes documentation
  website/docs/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.29.0/enterprise/getting-started/releases-enterprise.mdx
Labels: exclude from release notes

#3915 Update video on main docs page
  website/src/components/HomepageFeatures/index.js
Labels: user-guide

#3922 Update Flux GA guide
  website/docs/guides/fluxga-upgrade.mdx
Labels: exclude from release notes, user-guide

#3931 Add redirects for orphaned website pages
  website/docusaurus.config.js
Labels: exclude from release notes

#3927 Filter duplicate error messages
  ui/components/Page.tsx
Labels: ui

#3934 Add redirect for another orphaned docs page
  website/docusaurus.config.js
Labels: documentation, exclude from release notes

#3937 Added incident report for latest v0.29 out of ordering artefact pubishing
  doc/incidents/issues-3907/README.md
  doc/incidents/issues-3907/imgs/first-time-noticed.png
  doc/incidents/issues-3907/imgs/main-protection.png
  doc/incidents/issues-3907/imgs/release-protection.png
  doc/incidents/issues-3907/imgs/validate-non-release-pr-after-build.png
  doc/incidents/issues-3907/imgs/validate-non-release-pr.png
  doc/incidents/issues-3907/imgs/validate-release-pr-approved.png
  doc/incidents/issues-3907/imgs/validate-release-pr-happened.png
  doc/incidents/issues-3907/imgs/validate-release-pr-prepared.png
  doc/incidents/issues-3907/imgs/weave-gitops-protection-approval.png
  doc/incidents/issues-3907/imgs/weave-gitops-protection-status-checks.png
Labels: exclude from release notes

#3924 WGE install pages updates
  website/docs/enterprise/getting-started/install-enterprise-airgap.mdx
  website/docs/enterprise/getting-started/install-enterprise.mdx
Labels: user-guide

#3941 Fixes github-oauth link in Install WGE page
  website/docs/enterprise/getting-started/install-enterprise.mdx
Labels: bug, user-guide

#3939 Remove titles from detail pages for consistency
  ui/components/AutomationDetail.tsx
  ui/components/ImageAutomation/ImageAutomationDetails.tsx
  ui/components/PageStatus.tsx
  ui/components/PodDetail.tsx
  ui/components/SourceDetail.tsx
Labels: ui

#3955 User docs changes in WGE install guide, cluster mgmt pages
  website/docs/cluster-management/cluster-management-intro.mdx
  website/docs/cluster-management/managing-clusters-without-capi.mdx
  website/docs/configuration/emergency-user.mdx
  website/docs/configuration/oidc-access.mdx
  website/docs/configuration/recommended-rbac-configuration.mdx
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/docs/configuration/service-account-permissions.mdx
  website/docs/configuration/user-permissions.mdx
  website/docs/enterprise/getting-started/install-enterprise.mdx
  website/docs/enterprise/getting-started/releases-enterprise.mdx
  website/docs/explorer/configuration.mdx
  website/docs/open-source/getting-started/install-OSS.mdx
  website/docs/open-source/getting-started/ui-OSS.mdx
  website/sidebars.js
  website/versioned_docs/version-0.30.0/cluster-management/cluster-management-intro.mdx
  website/versioned_docs/version-0.30.0/cluster-management/managing-clusters-without-capi.mdx
  website/versioned_docs/version-0.30.0/configuration/emergency-user.mdx
  website/versioned_docs/version-0.30.0/configuration/oidc-access.mdx
  website/versioned_docs/version-0.30.0/configuration/recommended-rbac-configuration.mdx
  website/versioned_docs/version-0.30.0/configuration/securing-access-to-the-dashboard.mdx
  website/versioned_docs/version-0.30.0/configuration/service-account-permissions.mdx
  website/versioned_docs/version-0.30.0/configuration/user-permissions.mdx
  website/versioned_docs/version-0.30.0/enterprise/getting-started/install-enterprise.mdx
  website/versioned_docs/version-0.30.0/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.30.0/explorer/configuration.mdx
  website/versioned_docs/version-0.30.0/open-source/getting-started/install-OSS.mdx
  website/versioned_docs/version-0.30.0/open-source/getting-started/ui-OSS.mdx
  website/versioned_sidebars/version-0.30.0-sidebars.json
Labels: team/wild-watermelon, user-guide

#3921 Add Azure-related pages to user docs
  website/docs/enterprise/getting-started/install-enterprise-azure.mdx
  website/docs/enterprise/getting-started/join-cluster-azure-flux.mdx
  website/docs/guides/cert-manager.md
  website/docs/open-source/getting-started/install-OSS.mdx
  website/sidebars.js
  website/versioned_docs/version-0.29.0/guides/cert-manager.md
Labels: user-guide

#3953 Add Flex with breakpoint prop
  ui/components/AutomationDetail.tsx
  ui/components/ImageAutomation/ImageAutomationDetails.tsx
  ui/components/LargeInfo.tsx
  ui/components/SourceDetail.tsx
  ui/components/SyncActions.tsx
  ui/components/__tests__/SyncActions.test.tsx
  ui/components/__tests__/__snapshots__/SyncActions.test.tsx.snap
Labels: ui

#3964 User docs cleanup
  website/README.md
  website/docs/cluster-management/managing-clusters-without-capi.mdx
  website/docs/configuration/tls.md
  website/docs/enterprise/getting-started/install-enterprise-azure.mdx
  website/docs/enterprise/getting-started/join-cluster-azure-flux.mdx
  website/docs/guides/cert-manager.md
  website/docs/guides/setting-up-dex.md
  website/docs/terraform/using-terraform-templates.mdx
  website/sidebars.js
  website/versioned_docs/version-0.30.0/configuration/tls.md
  website/versioned_docs/version-0.30.0/guides/cert-manager.md
  website/versioned_docs/version-0.30.0/guides/setting-up-dex.md
  website/versioned_docs/version-0.30.0/terraform/using-terraform-templates.mdx
  website/versioned_sidebars/version-0.30.0-sidebars.json
Labels: documentation, team/wild-watermelon, user-guide

#3965 docs: Add SECURITY.md
  website/SECURITY.md
Labels: documentation

#3952 Convert to yarn for package management
  .github/workflows/pr.yaml
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
  Makefile
  doc/development-process.md
  package-lock.json
  package.json
  test/library/test.sh
  tsconfig.json
  ui/App.tsx
  ui/components/ErrorBoundary.tsx
  ui/components/ErrorList.tsx
  ui/components/Policies/Utils/MarkdownEditor.tsx
  ui/components/SubRouterTabs.tsx
  ui/contexts/AuthContext.tsx
  ui/lib/utils.ts
  yarn.lock
Labels: exclude from release notes

#3667 Improve feedback to user when objects aren't retrieved due to RBAC
  api/core/core.proto
  api/core/core.swagger.json
  core/clustersmngr/client.go
  core/server/objects.go
  core/server/utils.go
  pkg/api/core/core.pb.go
  ui/components/AutomationsTable.tsx
  ui/components/DataTable/DataTable.tsx
  ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/Icon.tsx
  ui/components/InfoModal.tsx
  ui/components/Modal.tsx
  ui/components/SourcesTable.tsx
  ui/hooks/automations.ts
  ui/hooks/sources.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/types.ts
  ui/pages/v2/Automations.tsx
  ui/pages/v2/Sources.tsx
Labels: enhancement

#3827 adding flux compatibility section to the release notes
  .github/workflows/prepare-release.yaml
Labels: exclude from release notes

#3972 add timeout for yarn
  Makefile
Labels: exclude from release notes
