Repository weaveworks/weave-gitops, pull requests merged in 2023-05, with the labels that each got.

#3651 Add an additional page status for automations that summarizes their canaries
  package-lock.json
  package.json
  ui/components/AutomationDetail.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/hooks/__tests__/inventory.test.tsx
  ui/hooks/inventory.ts
Labels: ui

#3660 Update nav icons and colors
  package-lock.json
  ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/Icon.tsx
  ui/components/Nav.tsx
  ui/components/NavIcons/ApplicationsIcon.tsx
  ui/components/NavIcons/ClustersIcon.tsx
  ui/components/NavIcons/DeliveryIcon.tsx
  ui/components/NavIcons/DocsIcon.tsx
  ui/components/NavIcons/ExploreIcon.tsx
  ui/components/NavIcons/FluxIcon.tsx
  ui/components/NavIcons/GitOpsRunIcon.tsx
  ui/components/NavIcons/GitOpsSetsIcon.tsx
  ui/components/NavIcons/ImageAutomationIcon.tsx
  ui/components/NavIcons/NotificationsIcon.tsx
  ui/components/NavIcons/PipelinesIcon.tsx
  ui/components/NavIcons/PoliciesIcon.tsx
  ui/components/NavIcons/PolicyConfigsIcon.tsx
  ui/components/NavIcons/SecretsIcon.tsx
  ui/components/NavIcons/SourcesIcon.tsx
  ui/components/NavIcons/TemplatesIcon.tsx
  ui/components/NavIcons/TerraformIcon.tsx
  ui/components/NavIcons/WorkspacesIcon.tsx
  ui/components/SearchField.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
Labels: ui, team/denim

#3655 2704 redesign application details
  ui/components/AutomationDetail.tsx
  ui/components/Collapsible.tsx
  ui/components/Flex.tsx
  ui/components/HealthCheckAgg.tsx
  ui/components/HelmReleaseDetail.tsx
  ui/components/Icon.tsx
  ui/components/KustomizationDetail.tsx
  ui/components/ReconciledObjectsTable.tsx
Labels: ui

#3662 Improve release process docs
  doc/release-process.md
Labels: documentation

#3656 added impersonation to explorer configuration documentation
  website/docs/explorer/configuration.mdx
Labels: documentation, exclude from release notes

#3658 Add icon and status for tf plans that are waiting for user action
  ui/components/Icon.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/images/pending-action.svg
  ui/lib/images.ts
Labels: ui

#3675 Change "G" logo to Weaveworks logo
  ui/components/Logo.tsx
  ui/images/logoDark.svg
  ui/images/logoLight.svg
  ui/lib/images.ts
  ui/pages/SignIn.tsx
Labels: ui

#3676 Add syntax highlighting to the YamlView
  package-lock.json
  package.json
  ui/components/YamlView.tsx
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
Labels: ui

#3685 Fix code tag style of `react-syntax-highlighter`
  ui/components/YamlView.tsx
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
Labels: exclude from release notes

#3688 docs: Minor addition to mention PAT usage
  website/docs/pipelines/promoting-applications.mdx
Labels: documentation

#3689 Added a redirect for getting started page
  .github/workflows/docs.yaml
  README.md
  ui/pages/SignIn.tsx
  website/docs/installation/aws-marketplace.mdx
  website/docusaurus.config.js
  website/package.json
  website/versioned_docs/version-0.22.0/installation/aws-marketplace.mdx
  website/yarn.lock
Labels: documentation

#3694 Fix url for enterprise intro page
  website/docs/policy/policy.mdx
  website/versioned_docs/version-0.22.0/policy/policy.mdx
  website/versioned_docs/version-0.23.0/policy/policy.mdx
Labels: documentation

#3696 Adding missing namespace in sops doc command
  website/docs/secrets/setup-sops.mdx
  website/versioned_docs/version-0.20.0/secrets/setup-sops.mdx
  website/versioned_docs/version-0.21.1/secrets/setup-sops.mdx
  website/versioned_docs/version-0.21.2/secrets/setup-sops.mdx
  website/versioned_docs/version-0.22.0/secrets/setup-sops.mdx
  website/versioned_docs/version-0.23.0/secrets/setup-sops.mdx
Labels: exclude from release notes

#3677 Add dark mode theme to the UI
  package-lock.json
  package.json
  ui/App.tsx
  ui/components/Alert.tsx
  ui/components/Animations/SignInBackground.tsx
  ui/components/AutomationDetail.tsx
  ui/components/Breadcrumbs.tsx
  ui/components/Button.tsx
  ui/components/ChipGroup.tsx
  ui/components/Collapsible.tsx
  ui/components/CopyToCliboard.tsx
  ui/components/DataTable/DataTable.tsx
  ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/DetailModal.tsx
  ui/components/DirectedGraph.tsx
  ui/components/Footer.tsx
  ui/components/GraphNode.tsx
  ui/components/Layout.tsx
  ui/components/Link.tsx
  ui/components/LoadingPage.tsx
  ui/components/Logo.tsx
  ui/components/MessageBox.tsx
  ui/components/Metadata.tsx
  ui/components/Nav.tsx
  ui/components/Page.tsx
  ui/components/SyncButton.tsx
  ui/components/UserSettings.tsx
  ui/components/YamlView.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/components/__tests__/__snapshots__/MessageBox.test.tsx.snap
  ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
  ui/contexts/AppContext.tsx
  ui/hooks/theme.ts
  ui/images/bg-dark.png
  ui/images/dark-mode-icon.svg
  ui/images/light-mode-icon.svg
  ui/images/logotypeLight.svg
  ui/images/signInWheelDark.svg
  ui/lib/images.ts
  ui/lib/test-utils.tsx
  ui/lib/theme.ts
  ui/pages/SignIn.tsx
  ui/pages/__tests__/Signin.test.tsx
  ui/typedefs/styled.d.ts
Labels: ui

#3708 App Observability - Surface Flagger Status
  ui/components/AutomationDetail.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/hooks/__tests__/inventory.test.tsx
  ui/hooks/inventory.ts
Labels: team/sunglow

#3710 Export baseTheme and ThemeTypes for Enterprise dark mode
  ui/index.ts
  ui/lib/theme.ts
Labels: ui

#3711 Add prop to hide dark mode switch
  ui/components/Logo.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
Labels: ui

#3715 Fix Divider styling on Sign In page
  ui/pages/SignIn.tsx
Labels: ui

#3716 Properly set up Link styled-component
  ui/components/Link.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/components/__tests__/__snapshots__/Version.test.tsx.snap
Labels: bug, ui

#3724 Dark Mode UI bug follow ups
  ui/components/DataTable/DataTable.tsx
  ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/SyncButton.tsx
Labels: ui

#3717 add docs to upgrade to Flux GA
  website/docs/guides/fluxga-upgrade.mdx
  website/sidebars.js
  website/versioned_docs/version-0.22.0/guides/fluxga-upgrade.mdx
  website/versioned_docs/version-0.23.0/guides/fluxga-upgrade.mdx
  website/versioned_docs/version-0.24.0/guides/fluxga-upgrade.mdx
  website/versioned_sidebars/version-0.22.0-sidebars.json
  website/versioned_sidebars/version-0.23.0-sidebars.json
  website/versioned_sidebars/version-0.24.0-sidebars.json
Labels: exclude from release notes

#3731 Fix navigation
  ui/components/Breadcrumbs.tsx
  ui/components/ErrorBoundary.tsx
  ui/components/ImageAutomation/policies/ImagePolicyDetails.tsx
  ui/components/ImageAutomation/repositories/ImageAutomationRepoDetails.tsx
  ui/components/ImageAutomation/updates/ImageAutomationUpdatesDetails.tsx
  ui/components/Layout.tsx
  ui/components/Logo.tsx
  ui/components/Page.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/Breadcrumbs.test.tsx
  ui/components/__tests__/Page.test.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/pages/Error.tsx
  ui/pages/v2/Automations.tsx
  ui/pages/v2/BucketDetail.tsx
  ui/pages/v2/FluxRuntime.tsx
  ui/pages/v2/GitRepositoryDetail.tsx
  ui/pages/v2/HelmChartDetail.tsx
  ui/pages/v2/HelmReleasePage.tsx
  ui/pages/v2/HelmRepositoryDetail.tsx
  ui/pages/v2/ImageAutomationPage.tsx
  ui/pages/v2/KustomizationPage.tsx
  ui/pages/v2/Notifications.tsx
  ui/pages/v2/OCIRepositoryPage.tsx
  ui/pages/v2/ProviderPage.tsx
  ui/pages/v2/Sources.tsx
  ui/pages/v2/UserInfo.tsx
Labels: enhancement

#3712 Show Application Violations in WeaveGitOps OSS
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.swagger.json
  core/server/policy_violations.go
  core/server/utils.go
  go.mod
  package-lock.json
  package.json
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  ui/App.tsx
  ui/components/AutomationDetail.tsx
  ui/components/Breadcrumbs.tsx
  ui/components/Icon.tsx
  ui/components/Policies/PolicyViolations/PolicyViolationDetails.tsx
  ui/components/Policies/PolicyViolations/PolicyViolationPage.tsx
  ui/components/Policies/PolicyViolations/Table/index.tsx
  ui/components/Policies/Utils/HeaderRows.tsx
  ui/components/Policies/Utils/Parameters.tsx
  ui/components/Policies/Utils/PolicyUtils.tsx
  ui/components/Policies/Utils/Severity.tsx
  ui/components/Policies/__tests__/HeaderRows.test.tsx
  ui/components/Policies/__tests__/Parameters.test.tsx
  ui/components/Policies/__tests__/Severity.test.tsx
  ui/components/YamlView.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/hooks/policyViolations.ts
  ui/index.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/nav.ts
  ui/lib/theme.ts
  ui/lib/types.ts
Labels: enhancement
