Repository weaveworks/weave-gitops, pull requests merged in 2023-07, with the labels that each got.

#3804 Terraform section docs changes
  website/docs/cluster-management/deploying-capa-eks.mdx
  website/docs/enterprise/getting-started/install-enterprise.mdx
  website/docs/enterprise/getting-started/intro-enterprise.mdx
  website/docs/terraform/aws-eks.mdx
  website/docs/terraform/backup-and-restore.mdx
  website/docs/terraform/environment-variables.mdx
  website/docs/terraform/get-started-terraform.mdx
  website/docs/terraform/get-started.mdx
  website/docs/terraform/oci-artifact.mdx
  website/docs/terraform/overview.mdx
  website/docs/terraform/terraform-enterprise.mdx
  website/docs/terraform/terraform-intro.mdx
  website/docs/terraform/tfctl.mdx
  website/docs/terraform/using-terraform-cr/custom-backend.mdx
  website/docs/terraform/using-terraform-cr/customize-runner.mdx
  website/docs/terraform/using-terraform-cr/depends-on.mdx
  website/docs/terraform/using-terraform-cr/detect-drifts-only-without-plan-or-apply.mdx
  website/docs/terraform/using-terraform-cr/drift-detection-disabled.mdx
  website/docs/terraform/using-terraform-cr/modules.mdx
  website/docs/terraform/using-terraform-cr/plan-and-manually-apply-terraform-resources.mdx
  website/docs/terraform/using-terraform-cr/provision-resources-and-auto-approve.mdx
  website/docs/terraform/using-terraform-cr/provision-resources-and-write-output-data.mdx
  website/docs/terraform/using-terraform-cr/set-variables-for-trraform-resources.mdx
  website/docs/terraform/using-terraform-templates.mdx
  website/sidebars.js
  website/static/img/dashboard-terraform.png
  website/static/img/wge-dashboard-dark-mode.png
  website/static/img/wge-dashboard-ui.png
Labels: documentation, team/wild-watermelon, user-guide

#3826 disabled snyk checks for both PRs and main
  .github/workflows/pr.yaml
Labels: exclude from release notes

#3829 Allow for custom actions for data table checkboxes
  ui/components/CheckboxActions.tsx
  ui/components/DataTable/DataTable.tsx
  ui/components/SyncButton.tsx
  ui/hooks/automations.ts
  ui/lib/types.ts
Labels: ui

#3834 Enhance types in checkbox actions for EE terraform sync/suspend all
  ui/components/CheckboxActions.tsx
Labels: ui

#3841 Changes to progressive delivery guide
  website/docs/enterprise/getting-started/intro-enterprise.mdx
  website/docs/guides/cert-manager.md
  website/docs/guides/flagger-manual-gating.mdx
  website/docs/progressive-delivery/flagger-manual-gating.mdx
  website/docs/progressive-delivery/progressive-delivery-flagger-install.mdx
  website/sidebars.js
Labels: documentation, team/wild-watermelon, user-guide

#3849 enabled dependabot with daily schedule and eng teams as reviewers
  .github/dependabot.yml
Labels: exclude from release notes

#3869 docs: Add v0.28.0 Release Notes
  website/docs/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.28.0/enterprise/getting-started/releases-enterprise.mdx
Labels: exclude from release notes

#3871 Tweaking dependabot to just raise PRs for security updates.
  .github/dependabot.yml
Labels: exclude from release notes

#3870 docs: add missing entry for v0.28.0 release notes
  website/docs/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.28.0/enterprise/getting-started/releases-enterprise.mdx
Labels: exclude from release notes

#3847 Update Create External Secrets Docs
  website/docs/secrets/imgs/add-property-1.png
  website/docs/secrets/imgs/add-secret-key-1.png
  website/docs/secrets/imgs/create-secret-1.png
  website/docs/secrets/imgs/create-secret-2.png
  website/docs/secrets/imgs/create-secret-3.png
  website/docs/secrets/imgs/enter-property-1.png
  website/docs/secrets/imgs/eso-details-1.png
  website/docs/secrets/imgs/eso-details-2.png
  website/docs/secrets/imgs/include-all-properties-1.png
  website/docs/secrets/manage-secrets-ui.mdx
Labels: documentation, exclude from release notes, user-guide

#3883 update External Secrets docs
  website/versioned_docs/version-0.28.0/secrets/imgs/add-property-1.png
  website/versioned_docs/version-0.28.0/secrets/imgs/add-secret-key-1.png
  website/versioned_docs/version-0.28.0/secrets/imgs/create-secret-1.png
  website/versioned_docs/version-0.28.0/secrets/imgs/create-secret-2.png
  website/versioned_docs/version-0.28.0/secrets/imgs/create-secret-3.png
  website/versioned_docs/version-0.28.0/secrets/imgs/enter-property-1.png
  website/versioned_docs/version-0.28.0/secrets/imgs/eso-details-1.png
  website/versioned_docs/version-0.28.0/secrets/imgs/eso-details-2.png
  website/versioned_docs/version-0.28.0/secrets/imgs/include-all-properties-1.png
  website/versioned_docs/version-0.28.0/secrets/manage-secrets-ui.mdx
Labels: documentation, exclude from release notes, user-guide

#3879 Fix missing key prop in checkbox actions, and provide "-" default text for large info
  ui/components/LargeInfo.tsx
Labels: ui

#3889 upgrade flux v2 dependencies take 4
  Makefile
  Tiltfile
  cmd/gitops/beta/run/cmd.go
  core/clustersmngr/client_test.go
  core/clustersmngr/cluster/delegating_cache.go
  core/clustersmngr/factory.go
  core/fluxsync/adapters.go
  core/fluxsync/fluxsync.go
  core/server/events_test.go
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/inventory.go
  core/server/inventory_test.go
  core/server/objects.go
  core/server/objects_test.go
  core/server/primarykinds.go
  core/server/primarykinds_test.go
  core/server/session_logs.go
  core/server/session_logs_test.go
  core/server/suspend_test.go
  core/server/sync.go
  core/server/sync_test.go
  go.mod
  go.sum
  pkg/api/core/core.pb.go
  pkg/api/core/types.pb.go
  pkg/kube/kubehttp.go
  pkg/run/install/apply_manifests_test.go
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_dashboard_test.go
  pkg/run/install/install_fluent_bit.go
  pkg/run/install/install_flux.go
  pkg/run/install/install_vcluster.go
  pkg/run/session/connect/connect.go
  pkg/run/session/connect/utils.go
  pkg/run/session/localkubernetes/configure.go
  pkg/run/session/portforward/start.go
  pkg/run/session/remove.go
  pkg/run/watch/setup_bucket_source.go
  pkg/run/watch/setup_dev_helm.go
  pkg/run/watch/setup_dev_ks.go
  pkg/run/watch/setup_dev_ks_test.go
  pkg/services/crd/fetcher.go
  pkg/testutils/testutils.go
  tools/testcrds/helm.toolkit.fluxcd.io_helmreleases.yaml
  tools/testcrds/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  tools/testcrds/source.toolkit.fluxcd.io_buckets.yaml
  tools/testcrds/source.toolkit.fluxcd.io_gitrepositories.yaml
  tools/testcrds/source.toolkit.fluxcd.io_helmcharts.yaml
  tools/testcrds/source.toolkit.fluxcd.io_helmrepositories.yaml
  tools/testcrds/source.toolkit.fluxcd.io_ocirepositories.yaml
Labels: breaking-change

#3899 Update old `/releases` link with new `/enterprise/getting-started/releases-enterprise/` urls
  website/versioned_docs/version-0.25.0/guides/fluxga-upgrade.mdx
  website/versioned_docs/version-0.26.0/guides/fluxga-upgrade.mdx
  website/versioned_docs/version-0.27.0/guides/fluxga-upgrade.mdx
  website/versioned_docs/version-0.28.0/guides/fluxga-upgrade.mdx
Labels: bug, documentation

#3892 ad docs and dashboard for indexer RED metrics
  website/docs/assets/dashboards/explorer.json
  website/docs/explorer/operations.mdx
Labels: exclude from release notes, team/tangerine
