Repository weaveworks/weave-gitops, pull requests merged in 2023-06, with the labels that each got.

#3742 updated cache-control upload-file staging-release step according to readme recommendations
  .github/workflows/docs.yaml
Labels: exclude from release notes

#3705 adding monitoring section for explorer
  website/docs/explorer/imgs/explorer-query-metrics.png
  website/docs/explorer/operations.mdx
  website/docs/explorer/resources/dashboard.json
Labels: exclude from release notes

#3714 Show Policies in WeaveGitOps OSS
  .gitignore
  api/core/core.proto
  api/core/core.swagger.json
  core/server/policies.go
  core/server/policies_test.go
  go.mod
  go.sum
  package-lock.json
  pkg/api/core/core.pb.go
  pkg/api/core/core.pb.gw.go
  pkg/api/core/core_grpc.pb.go
  pkg/kube/kubehttp.go
  ui/App.tsx
  ui/components/Icon.tsx
  ui/components/Layout.tsx
  ui/components/Policies/PolicyDetails/PolicyDetails.tsx
  ui/components/Policies/PolicyList/PolicyTable.tsx
  ui/components/Policies/PolicyViolations/PolicyViolationDetails.tsx
  ui/components/Policies/PolicyViolations/PolicyViolationPage.tsx
  ui/components/Policies/Utils/HeaderRows.tsx
  ui/components/Policies/Utils/PolicyMode.tsx
  ui/components/Policies/Utils/PolicyUtils.tsx
  ui/hooks/Policies.ts
  ui/lib/api/core/core.pb.ts
  ui/lib/nav.ts
  ui/lib/types.ts
  ui/pages/v2/PoliciesList.tsx
  ui/pages/v2/PolicyDetailsPage.tsx
Labels: enhancement

#3738 Refactor docs to clarify open source and Enterprise
  website/docs/getting-started/ui.mdx
  website/docs/installation/weave-gitops.mdx
  website/docs/intro-ee.mdx
  website/docs/intro.mdx
Labels: user-guide

#3740 Add dark mode switch to sign in page
  ui/App.tsx
  ui/components/DarkModeSwitch.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/pages/SignIn.tsx
Labels: ui

#3749 Disable Sync btn while loading and invalidate the react-query cache
  ui/components/AutomationDetail.tsx
  ui/components/CheckboxActions.tsx
  ui/components/SourceDetail.tsx
  ui/components/SyncButton.tsx
Labels: bug

#3752 Add linter for Protobuf files
  .protolint.yaml
  Makefile
  api/core/core.proto
  api/core/core.swagger.json
  api/core/types.proto
  pkg/api/core/core.pb.go
  pkg/api/core/core_grpc.pb.go
  pkg/api/core/types.pb.go
Labels: enhancement

#3460 Openshift: Allow removal of securityContext with Helm values
  charts/gitops-server/templates/deployment.yaml
Labels: enhancement, team/wild-watermelon

#3764 add entity kind to policy violation
  api/core/core.proto
  api/core/core.swagger.json
  core/server/policy_violations.go
  pkg/api/core/core.pb.go
  ui/components/Policies/PolicyViolations/PolicyViolationDetails.tsx
  ui/lib/api/core/core.pb.ts
Labels: enhancement

#3765 Update Nav highlight for Policy-details
  ui/lib/nav.ts
Labels: team/timber-wolf

#3755 add unit tests for policy validations
  core/server/policy_violations_test.go
Labels: exclude from release notes

#3768 Add clusterName to policies list
  core/server/policies.go
  core/server/policies_test.go
Labels: exclude from release notes

#3771 fix getting started location for helm-docs
  charts/gitops-server/README.md.gotmpl
Labels: exclude from release notes

#3773 fix main page index
  website/docusaurus.config.js
Labels: exclude from release notes

#3774 fix config file
  website/docusaurus.config.js
Labels: exclude from release notes

#3780 Warn users if Weave GitOps is already installed
  cmd/gitops/create/dashboard/cmd.go
Labels: enhancement

#3781 Add edit icon, modify Pipelines and Delivery icons for EE dark mode
  ui/components/Icon.tsx
  ui/components/NavIcons/DeliveryIcon.tsx
  ui/components/NavIcons/PipelinesIcon.tsx
Labels: ui

#3671 Update query syntax docs
  website/docs/explorer/getting-started.mdx
  website/docs/explorer/imgs/explorer-filter-terms.png
  website/docs/explorer/imgs/explorer-intro.png
  website/docs/explorer/imgs/explorer-match.png
  website/docs/explorer/imgs/explorer-multi-terms.png
  website/docs/explorer/imgs/explorer-open-new.png
  website/docs/explorer/querying.mdx
  website/versioned_docs/version-0.24.0/explorer/imgs/explorer-filter-terms.png
  website/versioned_docs/version-0.24.0/explorer/imgs/explorer-intro.png
  website/versioned_docs/version-0.24.0/explorer/imgs/explorer-match.png
  website/versioned_docs/version-0.24.0/explorer/imgs/explorer-multi-terms.png
  website/versioned_docs/version-0.24.0/explorer/imgs/explorer-open-new.png
  website/versioned_docs/version-0.24.0/explorer/imgs/explorer-query-metrics.png
  website/versioned_docs/version-0.25.0/explorer/imgs/explorer-filter-terms.png
  website/versioned_docs/version-0.25.0/explorer/imgs/explorer-intro.png
  website/versioned_docs/version-0.25.0/explorer/imgs/explorer-match.png
  website/versioned_docs/version-0.25.0/explorer/imgs/explorer-multi-terms.png
  website/versioned_docs/version-0.25.0/explorer/imgs/explorer-open-new.png
Labels: user-guide

#3792 Add policy full details to list endpoint
  core/server/policies.go
Labels: exclude from release notes

#3793 Swap success and feedback colors for EE dark mode
  ui/lib/theme.ts
Labels: ui

#3794 Link PolicyName in violationDetails to policyDetails page
  ui/components/AutomationDetail.tsx
  ui/components/Policies/PolicyDetails/PolicyDetails.tsx
  ui/components/Policies/PolicyViolations/PolicyViolationDetails.tsx
  ui/components/Policies/Utils/PolicyMode.tsx
Labels: ui, team/timber-wolf

#3795 Consistent use of topBarHeight variable
  ui/components/Logo.tsx
  ui/components/Nav.tsx
  ui/components/Page.tsx
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
Labels: ui

#3798 Update layout to accept components
  ui/App.tsx
  ui/components/Layout.tsx
Labels: exclude from release notes

#3803 Pipelines icon dark mode fix
  ui/components/NavIcons/PipelinesIcon.tsx
Labels: ui, team/wild-watermelon

#3806 Prevent white background on input autofill in dark mode
  ui/lib/theme.ts
Labels: bug, ui

#3807 Add dark mode color for input borders
  ui/lib/theme.ts
  ui/typedefs/styled.d.ts
Labels: ui
