Repository weaveworks/weave-gitops, pull requests merged in 2023-11, with the labels that each got.

#4124 Ensure the yarn.lock file is being used in container images
  gitops-server.dockerfile
Labels: exclude from release notes

#3846 fix duplicate icons
  ui/components/Icon.tsx
  ui/components/NavIcons/PoliciesIcon.tsx
  ui/components/Policies/Utils/PolicyMode.tsx
Labels: area/ui

#4122 Reorders sidebar and fixes typos
  website/docs/operations/monitoring.mdx
  website/sidebars.js
  website/versioned_sidebars/version-0.35.0-sidebars.json
Labels: team/wild-watermelon

#4073 add gitops-ee bootstrap cli user documentation
  website/docs/enterprise/getting-started/install-enterprise-cli.mdx
  website/sidebars.js
Labels: documentation

#4090 Refactor /inventory code to expose some helpers
  Makefile
  core/server/inventory.go
  core/server/inventory_internal_test.go
  core/server/inventory_test.go
  gitops-server.dockerfile
Labels: type/enhancement

#4125 ci: Simplify docs creation
  .github/workflows/docs.yaml
Labels: exclude from release notes

#4132 Fix website README
  website/README.md
Labels: documentation

#4131 Add suspended annotations
  Makefile
  api/core/core.proto
  api/core/core.swagger.json
  buf.lock
  core/server/suspend.go
  core/server/suspend_test.go
  pkg/api/core/core.pb.go
  ui/lib/api/core/core.pb.ts
Labels: type/enhancement

#4138 add wge release notes for v0.32 to v0.3.60
  website/docs/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.36.0/enterprise/getting-started/releases-enterprise.mdx
Labels: documentation

#4133 Add monitoring to object cleaner
  website/docs/explorer/operations.mdx
Labels: documentation

#4137 added docs suggestions while reviewing
  website/docs/enterprise/getting-started/install-enterprise-cli.mdx
Labels: documentation

#4139 show suspended by annotations to metadata component
  core/server/suspend.go
  core/server/suspend_test.go
Labels: type/enhancement

#4141 UI | fix markdown editor overflow style
  ui/components/Policies/Utils/MarkdownEditor.tsx
Labels: area/ui, team/timber-wolf

#4136 Add CLI bootstrap flux documentation
  website/docs/enterprise/getting-started/install-enterprise-cli.mdx
  website/versioned_docs/version-0.36.0/enterprise/getting-started/install-enterprise-cli.mdx
Labels: documentation

#4142 added repo url examples in cli bootstrapping docs
  website/docs/enterprise/getting-started/install-enterprise-cli.mdx
  website/versioned_docs/version-0.36.0/enterprise/getting-started/install-enterprise-cli.mdx
Labels: documentation

#4149 Add release notes for version-0.37.0
  website/docs/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.37.0/enterprise/getting-started/releases-enterprise.mdx
Labels: documentation

#4150 add weave gitops oss release notes links for v0.37
  website/docs/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.37.0/enterprise/getting-started/releases-enterprise.mdx
Labels: documentation

#4148 Fix invalid JSX properties on inline SVG
  ui/components/NavIcons/PoliciesIcon.tsx
Labels: exclude from release notes
