Repository weaveworks/weave-gitops, pull requests merged in 2023-02, with the labels that each got.

#3355 Improve formatting of log message timestamp in the log UI
  ui/index.ts
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: ui, gitops-run

#3365 Update 0.16 website docs
  website/docs/releases.mdx
  website/versioned_docs/version-0.16.0/releases.mdx
Labels: exclude from release notes

#3370 add artifact list to release guide
  doc/release-process.md
Labels: exclude from release notes

#3291 Added weave gitops quickstart templates
  website/docs/gitops-templates/imgs/quickstart-templates-deployed.png
  website/docs/gitops-templates/imgs/quickstart-templates-view.png
  website/docs/gitops-templates/quickstart-templates.mdx
Labels: documentation, team/sunglow

#3332 docs: Add Helm and CLI reference to nav bar
  website/docs/getting-started.mdx
  website/docs/references/helm-reference.md
  website/docs/releases.mdx
  website/docusaurus.config.js
  website/sidebars.js
  website/src/pages/feedback-and-telemetry/index.md
  website/src/pages/help-and-support/index.md
  website/versioned_sidebars/version-0.15.0-sidebars.json
  website/versioned_sidebars/version-0.16.0-sidebars.json
Labels: documentation

#3368 Fix log timestamp format string
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: ui, exclude from release notes, gitops-run

#3328 docs: Add a dedicated Enterprise page
  website/docs/_components/TierLabel.jsx
  website/docs/cluster-management/add-applications.mdx
  website/docs/cluster-management/deleting-a-cluster.mdx
  website/docs/cluster-management/gitrepo-selection.mdx
  website/docs/cluster-management/managing-existing-clusters.mdx
  website/docs/cluster-management/profiles.mdx
  website/docs/cluster-management/provider-identities.mdx
  website/docs/configuration/user-permissions.mdx
  website/docs/getting-started.mdx
  website/docs/gitops-templates/templates.mdx
  website/docs/guides/delivery.mdx
  website/docs/guides/deploying-capa.mdx
  website/docs/guides/using-terraform-templates.mdx
  website/docs/installation/weave-gitops-enterprise/airgap.mdx
  website/docs/installation/weave-gitops-enterprise/index.mdx
  website/docs/installation/weave-gitops.mdx
  website/docs/intro-ee.mdx
  website/docs/intro.md
  website/docs/intro.mdx
  website/docs/pipelines/authorization.mdx
  website/docs/pipelines/getting-started.mdx
  website/docs/pipelines/pipeline-templates.mdx
  website/docs/pipelines/promoting-applications.mdx
  website/docs/pipelines/spec/v1alpha1/pipeline.mdx
  website/docs/policy/commit-time-checks.mdx
  website/docs/policy/configuration.mdx
  website/docs/policy/getting-started.mdx
  website/docs/policy/policy-configuration.mdx
  website/docs/policy/policy-set.mdx
  website/docs/policy/releases.mdx
  website/docs/policy/weave-policy-profile.mdx
  website/docs/releases.mdx
  website/sidebars.js
Labels: documentation

#3366 Initial import of the GitOpsSets user-guide
  website/docs/gitopssets/_rbac_warning.mdx
  website/docs/gitopssets/features.mdx
  website/docs/gitopssets/git-generator.mdx
  website/docs/gitopssets/intro.mdx
  website/docs/gitopssets/list-generator.mdx
  website/docs/gitopssets/matrix-generator.mdx
  website/docs/gitopssets/pull-request-generator.mdx
  website/sidebars.js
Labels: documentation

#3371 Improve detection of OSS dashboard
  cmd/gitops/beta/run/cmd.go
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_dashboard_test.go
Labels: gitops-run

#3378 add gitopsets docs to version v0.16.0
  website/versioned_docs/version-0.16.0/gitopssets/_rbac_warning.mdx
  website/versioned_docs/version-0.16.0/gitopssets/features.mdx
  website/versioned_docs/version-0.16.0/gitopssets/git-generator.mdx
  website/versioned_docs/version-0.16.0/gitopssets/intro.mdx
  website/versioned_docs/version-0.16.0/gitopssets/list-generator.mdx
  website/versioned_docs/version-0.16.0/gitopssets/matrix-generator.mdx
  website/versioned_docs/version-0.16.0/gitopssets/pull-request-generator.mdx
  website/versioned_sidebars/version-0.16.0-sidebars.json
Labels: documentation

#3380 Add text search to table urls
  ui/components/DataTable.tsx
  ui/components/__tests__/DataTableFilters.test.tsx
Labels: ui

#3382 add imagePolicy details
  ui/App.tsx
  ui/components/ImageAutomation/policies/ImagePoliciesTable.tsx
  ui/components/ImageAutomation/policies/ImagePolicyDetails.tsx
  ui/components/Nav.tsx
  ui/lib/nav.ts
  ui/lib/types.ts
Labels: enhancement, team/sunglow

#3385 Add optional tooltip to Timestamp component
  ui/components/Timestamp.tsx
Labels: ui

#3386 docs: document how to set up Jenkins with Pipeline promotion events
  website/docs/pipelines/img/pipelines-jenkins/post-content-param.png
  website/docs/pipelines/img/pipelines-jenkins/token.png
  website/docs/pipelines/pipelines-with-jenkins.mdx
  website/sidebars.js
Labels: exclude from release notes

#3387 GitOps Run cannot detect Enterprise Dashboard
  cmd/gitops/beta/run/cmd.go
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_dashboard_test.go
Labels: enhancement, gitops-run

#3401 another attempt to fix ARM builds
  .npmrc
Labels: exclude from release notes

#3294 Add exports and updates for gitopsset details in EE
  package-lock.json
  ui/components/AutomationDetail.tsx
  ui/components/ReconciledObjectsTable.tsx
  ui/components/ReconciliationGraph.tsx
  ui/index.ts
Labels: exclude from release notes

#3398 docs: document how to set up Tekton with Pipeline promotion events
  website/docs/pipelines/pipelines-with-tekton.mdx
  website/sidebars.js
Labels: exclude from release notes

#3412 docs: Expand the website readme
  website/README.md
Labels: documentation

#3414 Extend ImageAutomation views with cluster information
  ui/index.ts
  ui/lib/objects.ts
Labels: ui

#3419 address GitOps Run "ask twice" issue by handling "no" answer correctly
  cmd/gitops/beta/run/cmd.go
  pkg/run/install/session.go
Labels: bug

#3400 docs: Revamp the GitOps Run docs
  website/docs/gitops-run/get-started.mdx
  website/docs/gitops-run/overview.mdx
  website/sidebars.js
Labels: documentation

#3410 docs: Add instructions for BitBucket Server
  website/docs/installation/weave-gitops-enterprise/index.mdx
  website/static/img/oauth-bitbucket.png
Labels: documentation, team/sunglow

#3373 docs: Updates following runthrough pt1
  website/docs/configuration/emergency-user.mdx
  website/docs/configuration/oidc-access.mdx
  website/docs/configuration/recommended-rbac-configuration.mdx
  website/docs/configuration/securing-access-to-the-dashboard.mdx
  website/docs/configuration/service-account-permissions.mdx
  website/docs/configuration/tls.md
  website/docs/configuration/user-permissions.mdx
  website/docs/getting-started/ui.mdx
  website/docs/guides/delivery.mdx
  website/docs/guides/deploying-capa.mdx
  website/docs/guides/displaying-custom-metadata.mdx
  website/docs/guides/flagger-manual-gating.mdx
  website/docs/guides/using-terraform-templates.mdx
  website/docs/intro.mdx
  website/sidebars.js
  website/static/img/dashboard-application-events.png
  website/static/img/dashboard-application-flux.png
  website/static/img/dashboard-application-reconciliation.png
  website/static/img/dashboard-application-yaml.png
  website/static/img/dashboard-applications-overview.png
  website/static/img/dashboard-applications-with-podinfo.png
  website/static/img/dashboard-flux-runtime-crd.png
  website/static/img/dashboard-flux-runtime.png
  website/static/img/dashboard-login.png
  website/static/img/dashboard-podinfo-details-suspended.png
  website/static/img/dashboard-podinfo-details.png
  website/static/img/dashboard-podinfo-suspended.png
  website/static/img/dashboard-podinfo-updated.png
  website/static/img/dashboard-source-flux.png
  website/static/img/dashboard-sources.png
Labels: documentation

#3406 Errors on GitOps Run object details pages before GitOps Run objects are ready
  api/core/core.swagger.json
  api/core/types.proto
  cmd/gitops/beta/run/cmd.go
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/objects.go
  core/server/objects_test.go
  core/server/session_logs.go
  core/server/suite_test.go
  core/server/types/objects.go
  pkg/api/core/types.pb.go
  pkg/run/constants/constants.go
  pkg/run/install/install_fluent_bit.go
  pkg/run/install/install_fluent_bit_test.go
  pkg/run/install/install_vcluster.go
  pkg/run/watch/install_dev_bucket_server.go
  pkg/run/watch/setup_bucket_source.go
  pkg/run/watch/setup_dev_helm.go
  pkg/run/watch/setup_dev_ks.go
  pkg/run/watch/setup_dev_ks_test.go
  ui/lib/api/core/types.pb.ts
  ui/lib/objects.ts
Labels: bug, ui, gitops-run, mvp

#3423 Fix broken search in Image Automation page
  ui/components/ImageAutomation/policies/ImagePoliciesTable.tsx
  ui/components/ImageAutomation/repositories/ImageRepositoriesTable.tsx
  ui/components/ImageAutomation/updates/ImageAutomationUpdatesTable.tsx
  ui/hooks/imageautomation.ts
Labels: ui

#3330 docs: Add landing page with features highlight
  website/docusaurus.config.js
  website/package.json
  website/src/components/CoreFeatures/index.js
  website/src/components/CoreFeatures/styles.module.css
  website/src/components/EnterpriseFeatures/index.js
  website/src/components/EnterpriseFeatures/styles.module.css
  website/src/components/HomepageFeatures/index.js
  website/src/components/HomepageFeatures/styles.module.css
  website/src/css/custom.css
  website/src/pages/index.js
  website/src/pages/index.module.css
  website/yarn.lock
Labels: documentation

#3405 docs: Desaturate the docs of all the yaml
  website/docs/cluster-management/managing-existing-clusters.mdx
  website/docs/configuration/recommended-rbac-configuration.mdx
  website/docs/configuration/user-permissions.mdx
  website/docs/getting-started/deploy.mdx
  website/docs/gitops-templates/quickstart-templates.mdx
  website/docs/gitops-templates/templates.mdx
  website/docs/gitopssets/_rbac_warning.mdx
  website/docs/guides/cert-manager.md
  website/docs/guides/delivery.mdx
  website/docs/guides/setting-up-dex.md
  website/docs/guides/using-terraform-templates.mdx
  website/docs/installation/aws-marketplace.mdx
  website/docs/installation/weave-gitops-enterprise/airgap.mdx
  website/docs/installation/weave-gitops-enterprise/index.mdx
  website/docs/pipelines/getting-started.mdx
  website/docs/pipelines/pipeline-templates.mdx
  website/docs/pipelines/pipelines-with-jenkins.mdx
  website/docs/pipelines/promoting-applications.mdx
  website/docs/policy/commit-time-checks.mdx
  website/docs/policy/policy-configuration.mdx
  website/docs/terraform/oci-artifact.mdx
  website/docs/terraform/using-terraform-cr/custom-backend.mdx
  website/docs/terraform/using-terraform-cr/customize-runner.mdx
  website/docs/terraform/using-terraform-cr/depends-on.mdx
  website/docs/terraform/using-terraform-cr/modules.mdx
  website/docs/terraform/using-terraform-cr/set-variables-for-trraform-resources.mdx
  website/docs/workspaces/multi-tenancy.mdx
  website/sidebars.js
Labels: documentation

#3427 fix: Ctrl+C not working during GitOps Run setup phase
  cmd/gitops/beta/run/cmd.go
  pkg/run/install/install_fluent_bit.go
Labels: bug, gitops-run

#3424 fix enterprise installation docs
  website/docs/installation/weave-gitops-enterprise/index.mdx
Labels: documentation

#3429 Error getting GitOps Run logs before GitOps Run objects are ready
  core/server/session_logs.go
  core/server/session_logs_int_test.go
  ui/components/AutomationDetail.tsx
  ui/components/DataTable.tsx
Labels: bug, ui, gitops-run

#3426 [docs] extending security considerations for pipeline credentials
  website/docs/_components/_alpha_warning.mdx
  website/docs/pipelines/authorization.mdx
  website/docs/pipelines/getting-started.mdx
  website/docs/pipelines/img/bot-account.png
  website/docs/pipelines/img/create-token-with-expiration.png
  website/docs/pipelines/img/fine-grained-token.png
  website/docs/pipelines/img/manage-fine-grained.png
  website/docs/pipelines/intro.mdx
  website/docs/pipelines/promoting-applications.mdx
  website/docs/pipelines/spec/v1alpha1/pipeline.mdx
Labels: documentation

#3440 Error getting GitOps Run logs before GitOps Run objects are ready
  core/server/session_logs.go
  core/server/session_logs_int_test.go
Labels: bug, ui, exclude from release notes, gitops-run

#3442 Error getting GitOps Run logs before GitOps Run objects are ready
  core/server/session_logs.go
Labels: exclude from release notes, gitops-run

#3435 skip reconciliation of dotfiles in GitOps Run
  cmd/gitops/beta/run/cmd.go
Labels: bug, gitops-run

#3445 Error getting GitOps Run logs before GitOps Run objects are ready
  core/server/session_logs.go
Labels: bug, exclude from release notes, gitops-run

#3441 versioned installation docs: link to correct artifacts
  website/versioned_docs/version-0.15.0/installation/weave-gitops-enterprise/index.mdx
  website/versioned_docs/version-0.16.0/installation/weave-gitops-enterprise/index.mdx
  website/versioned_docs/version-0.17.0/installation/weave-gitops-enterprise/index.mdx
Labels: documentation

#3444 Add collapsible nav redesign
  ui/App.tsx
  ui/components/Icon.tsx
  ui/components/ImageAutomationIcon.tsx
  ui/components/Layout.tsx
  ui/components/Logo.tsx
  ui/components/Nav.tsx
  ui/components/SourcesIcon.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/Logo.test.tsx
  ui/components/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  ui/components/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
  ui/components/__tests__/__snapshots__/Logo.test.tsx.snap
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
  ui/images/logo.svg
  ui/images/logotype.svg
  ui/images/weaveG.svg
  ui/lib/images.ts
Labels: ui
