Repository weaveworks/weave-gitops, pull requests merged in 2023-10, with the labels that each got.

#4055 Standardize the column names on Events tabs
  ui/components/EventsTable.tsx
Labels: area/ui

#3989 UI - update tabs view
  ui/components/SubRouterTabs.tsx
  ui/lib/theme.ts
Labels: area/ui, ui_triage

#4063 upgrades postcss to address https://www.npmjs.com/advisories/1094239
  package.json
Labels: type/enhancement

#4061 Added weave gitops enterprise monitoring user documentation
  website/docs/explorer/operations.mdx
  website/docs/operations/imgs/monitoring-dashboard-list.png
  website/docs/operations/imgs/monitoring-dashboard-overview.png
  website/docs/operations/imgs/monitoring-dashboard-runtime.png
  website/docs/operations/monitoring.mdx
  website/sidebars.js
Labels: documentation, exclude from release notes

#4067 Verified sources update to not display status "Pending" for objects where verification has not been set
  ui/components/AutomationsTable.tsx
  ui/components/SourcesTable.tsx
  ui/components/VerifiedStatus.tsx
Labels: bug

#4069 Move header creation outside yaml view to allow for custom text
  ui/components/AutomationDetail.tsx
  ui/components/DetailModal.tsx
  ui/components/ImageAutomation/ImageAutomationDetails.tsx
  ui/components/PodDetail.tsx
  ui/components/ProviderDetail.tsx
  ui/components/SourceDetail.tsx
  ui/components/YamlView.tsx
  ui/components/__tests__/YamlView.test.tsx
  ui/lib/__tests__/utils.test.ts
  ui/lib/utils.ts
Labels: area/ui

#4071 override default tabs min-width at (600px) media query
  ui/components/SubRouterTabs.tsx
Labels: area/ui

#4084 Add colors and exports for new EE pipelines UI
  ui/App.tsx
  ui/components/Alert.tsx
  ui/components/ChipGroup.tsx
  ui/components/DetailModal.tsx
  ui/components/ErrorList.tsx
  ui/components/FluxObjectsTable.tsx
  ui/components/GraphNode.tsx
  ui/components/HealthCheckStatusIndicator.tsx
  ui/components/KubeStatusIndicator.tsx
  ui/components/Modal.tsx
  ui/components/Page.tsx
  ui/components/PodDetail.tsx
  ui/components/Policies/Utils/Parameters.tsx
  ui/components/Policies/Utils/PolicyUtils.tsx
  ui/components/SyncButton.tsx
  ui/components/UserSettings.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
  ui/components/__tests__/__snapshots__/SyncActions.test.tsx.snap
  ui/index.ts
  ui/lib/theme.ts
  ui/pages/SignIn.tsx
  ui/typedefs/styled.d.ts
Labels: type/enhancement, area/ui

#4089 added profiling docs
  website/docs/operations/imgs/profiling-pprof-web-ui.png
  website/docs/operations/monitoring.mdx
Labels: documentation

#4095 fixed format for monitoring docs
  website/docs/operations/monitoring.mdx
Labels: documentation, exclude from release notes

#4103 generate sitemap
  website/docusaurus.config.js
Labels: documentation

#4074 Remove webkit-scrollbar css
  ui/lib/theme.ts
Labels: area/ui

#4091 Cleanup datatable
  ui/components/DataTable/DataTable.tsx
  ui/components/DataTable/SortableLabel.tsx
  ui/components/DataTable/TableView/SearchedNamespacesModal.tsx
  ui/components/DataTable/TableView/SortableLabelView.tsx
  ui/components/DataTable/TableView/TableBody.tsx
  ui/components/DataTable/TableView/TableHeader.tsx
  ui/components/DataTable/TableView/TableView.tsx
  ui/components/DataTable/TableView/types.ts
  ui/components/DataTable/__tests__/DataTableFilters.test.tsx
  ui/components/DataTable/__tests__/__snapshots__/DataTable.test.tsx.snap
  ui/components/__tests__/FluxObjectsTable.test.tsx
Labels: area/ui

#4107 refactor: refactor away from deprecated wait.Poll calls
  core/clustersmngr/cluster/delegating_cache.go
  core/clustersmngr/cluster/single.go
  go.mod
  go.sum
  pkg/run/install/install_dashboard.go
  pkg/run/install/install_fluent_bit.go
  pkg/run/install/install_vcluster.go
  pkg/run/session/connect/connect.go
  pkg/run/session/remove.go
  pkg/run/watch/setup_dev_ks.go
Labels: exclude from release notes

#4080 Standardize the sync/suspend/edit buttons
  ui/components/AutomationDetail.tsx
  ui/components/CheckboxActions.tsx
  ui/components/DataTable/DataTable.tsx
  ui/components/Icon.tsx
  ui/components/ImageAutomation/ImageAutomationDetails.tsx
  ui/components/SourceDetail.tsx
  ui/components/Sync/CheckboxActions.tsx
  ui/components/Sync/ResumeIcon.tsx
  ui/components/Sync/SyncActions.tsx
  ui/components/Sync/SyncControls.tsx
  ui/components/Sync/__tests__/CheckboxActions.test.tsx
  ui/components/Sync/__tests__/SyncActions.test.tsx
  ui/components/Sync/__tests__/SyncControls.test.tsx
  ui/components/Sync/__tests__/__snapshots__/SyncActions.test.tsx.snap
  ui/components/Sync/__tests__/__snapshots__/SyncControls.test.tsx.snap
  ui/components/SyncActions.tsx
  ui/components/SyncButton.tsx
  ui/components/__tests__/__snapshots__/SyncActions.test.tsx.snap
  ui/index.ts
  ui/lib/theme.ts
Labels: type/enhancement
