Repository weaveworks/weave-gitops, pull requests merged in 2023-09, with the labels that each got.

#3923 Move stray Progressive Delivery text to related page
  website/docs/intro-weave-gitops.mdx
  website/docs/open-source/getting-started/ui-OSS.mdx
  website/docs/progressive-delivery/progressive-delivery-flagger-install.mdx
  website/static/img/dashboard-applications-delivery.png
Labels: user-guide

#3982 Adds Troubleshooting section to WGE TF-Controller docs
  website/docs/terraform/get-started-terraform.mdx
Labels: documentation, terraform, team/wild-watermelon, user-guide

#3981 Adds Troubleshooting Section to GitOps Run user docs
  website/docs/gitops-run/gitops-run-get-started.mdx
Labels: documentation, team/wild-watermelon, user-guide

#3987 Fix the error could not not resolve module "node:os" from cosmiconfig preventing to build the UI
  package.json
  yarn.lock
Labels: bug

#3985 fix Space in between buttons
  ui/components/CheckboxActions.tsx
  ui/components/CustomActions.tsx
  ui/components/SyncActions.tsx
  ui/components/SyncButton.tsx
  ui/components/__tests__/__snapshots__/SyncActions.test.tsx.snap
Labels: ui

#3993 Fix backporting gaps to prevent old docs versions from showing up in search
  website/versioned_docs/version-0.24.0/cluster-management/getting-started.mdx
  website/versioned_docs/version-0.24.0/enterprise/getting-started/aws-marketplace.mdx
  website/versioned_docs/version-0.24.0/enterprise/getting-started/install-enterprise-airgap.mdx
  website/versioned_docs/version-0.24.0/enterprise/getting-started/install-enterprise.mdx
  website/versioned_docs/version-0.24.0/enterprise/getting-started/intro-enterprise.mdx
  website/versioned_docs/version-0.24.0/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.24.0/explorer/configuration.mdx
  website/versioned_docs/version-0.24.0/explorer/getting-started.mdx
  website/versioned_docs/version-0.24.0/getting-started/intro.mdx
  website/versioned_docs/version-0.24.0/gitops-run/get-started.mdx
  website/versioned_docs/version-0.24.0/gitops-templates/cli.mdx
  website/versioned_docs/version-0.24.0/gitops-templates/quickstart-templates.mdx
  website/versioned_docs/version-0.24.0/guides/cert-manager.md
  website/versioned_docs/version-0.24.0/guides/deploying-capa.mdx
  website/versioned_docs/version-0.24.0/guides/displaying-custom-metadata.mdx
  website/versioned_docs/version-0.24.0/guides/setting-up-dex.md
  website/versioned_docs/version-0.24.0/guides/using-terraform-templates.mdx
  website/versioned_docs/version-0.24.0/installation/index.mdx
  website/versioned_docs/version-0.24.0/intro-weave-gitops.mdx
  website/versioned_docs/version-0.24.0/open-source/getting-started/deploy-OSS.mdx
  website/versioned_docs/version-0.24.0/open-source/getting-started/install-OSS.mdx
  website/versioned_docs/version-0.24.0/open-source/getting-started/ui-OSS.mdx
  website/versioned_docs/version-0.24.0/references/helm-reference.md
  website/versioned_docs/version-0.24.0/secrets/bootstraping-secrets.mdx
  website/versioned_sidebars/version-0.24.0-sidebars.json
Labels: team/wild-watermelon

#3994 Add eslint rule to alphabetize imports
  .eslintrc
  package.json
  ui/components/DataTable/DataTable.tsx
  ui/components/Icon.tsx
  ui/components/NotificationsTable.tsx
  ui/components/Policies/PolicyList/PolicyTable.tsx
  ui/components/Policies/PolicyViolations/PolicyViolationDetails.tsx
  ui/components/Policies/PolicyViolations/PolicyViolationPage.tsx
  ui/components/Policies/PolicyViolations/Table/index.tsx
  ui/components/Policies/__tests__/Severity.test.tsx
  ui/components/__tests__/Link.test.tsx
  ui/contexts/CoreClientContext.tsx
  ui/hooks/Policies.ts
  ui/hooks/policyViolations.ts
  ui/lib/__tests__/graph.test.ts
  ui/lib/__tests__/objects.test.ts
  ui/lib/objects.ts
  ui/pages/Error.tsx
  ui/pages/v2/UserInfo.tsx
  yarn.lock
Labels: area/ui, ui_triage

#4004 Add Policies nav-item to the side nav
  ui/App.tsx
Labels: area/ui

#4002 Add Artifact Metadata section to OCI Repository detail pages
  ui/components/Metadata.tsx
  ui/components/OCIRepositoryDetail.tsx
  ui/components/SourceDetail.tsx
  ui/components/__tests__/Metadata.test.tsx
  ui/components/__tests__/__snapshots__/Metadata.test.tsx.snap
  ui/lib/__tests__/objects.test.ts
  ui/lib/objects.ts
Labels: area/ui

#4000 Adds Image Automation info to user docs
  website/docs/open-source/getting-started/ui-OSS.mdx
Labels: documentation, team/wild-watermelon, user-guide

#3913 Backstage Plugin overview.
  website/docs/backstage/img/helm-releases-in-overview.png
  website/docs/backstage/img/kustomizations-tab.png
  website/docs/backstage/intro.mdx
  website/sidebars.js
Labels: user-guide

#4014 Adds OpenSSF badge and updates user docs links
  README.md
Labels: documentation, team/wild-watermelon

#4009 Preserve format when copy/paste yaml file
  ui/components/CopyToCliboard.tsx
  ui/components/YamlView.tsx
  ui/components/__tests__/__snapshots__/YamlView.test.tsx.snap
Labels: area/ui

#3991 Add GitOpsSets documentation.
  website/docs/gitopssets/gitopssets-installation.mdx
  website/docs/gitopssets/gitopssets-intro.mdx
  website/docs/gitopssets/gitopssets-releases.mdx
  website/docs/gitopssets/templating-from-generators.mdx
Labels: documentation, user-guide

#4027 updating explorer kind docs to reflect latest changes
  website/docs/explorer/configuration.mdx
Labels: exclude from release notes

#4025 Import `ImageAutomation` components to be used in EE
  ui/components/ImageAutomation/policies/ImagePoliciesTable.tsx
  ui/components/ImageAutomation/policies/ImagePolicyDetails.tsx
  ui/components/ImageAutomation/repositories/ImageAutomationRepoDetails.tsx
  ui/components/ImageAutomation/repositories/ImageRepositoriesTable.tsx
  ui/components/ImageAutomation/updates/ImageAutomationUpdatesDetails.tsx
  ui/components/ImageAutomation/updates/ImageAutomationUpdatesTable.tsx
  ui/index.ts
Labels: area/ui

#4028 Fix 'cluster not found' error when requesting source from automation `sourceRef`
  ui/components/AutomationsTable.tsx
  ui/components/UserSettings.tsx
  ui/components/VerifiedStatus.tsx
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
Labels: area/ui

#4029 Add noText prop to kubeStatusIndicator
  ui/components/KubeStatusIndicator.tsx
  ui/components/__tests__/KubeStatusIndicator.test.tsx
  ui/components/__tests__/__snapshots__/KubeStatusIndicator.test.tsx.snap
Labels: area/ui

#4031 Removes error on Progressive Delivery page and adds info about UI views
  website/docs/open-source/getting-started/ui-OSS.mdx
  website/docs/progressive-delivery/progressive-delivery-flagger-install.mdx
Labels: documentation, team/wild-watermelon, user-guide

#4030 Fix Suspend button width on Source details pages with short status message
  ui/components/SyncActions.tsx
  ui/components/__tests__/__snapshots__/SyncActions.test.tsx.snap
Labels: bug, area/ui

#4035 Link clusterName in image automation details
  ui/components/ImageAutomation/ImageAutomationDetails.tsx
  ui/components/ImageAutomation/policies/ImagePolicyDetails.tsx
  ui/components/ImageAutomation/repositories/ImageAutomationRepoDetails.tsx
  ui/components/ImageAutomation/updates/ImageAutomationUpdatesDetails.tsx
  ui/components/Policies/Utils/HeaderRows.tsx
Labels: area/ui

#4037 Resolves skipped backporting between versions 0.29.0 and 0.30.0
  website/versioned_docs/version-0.29.0/enterprise/getting-started/releases-enterprise.mdx
  website/versioned_docs/version-0.29.0/gitops-run/gitops-run-get-started.mdx
  website/versioned_docs/version-0.29.0/gitops-run/gitops-run-overview.mdx
  website/versioned_docs/version-0.29.0/gitops-templates/quickstart-templates.mdx
  website/versioned_docs/version-0.29.0/gitopssets/gitopssets-api-reference.mdx
  website/versioned_docs/version-0.29.0/gitopssets/gitopssets-installation.mdx
  website/versioned_docs/version-0.29.0/gitopssets/gitopssets-intro.mdx
  website/versioned_docs/version-0.29.0/gitopssets/gitopssets-releases.mdx
  website/versioned_docs/version-0.29.0/gitopssets/templating-from-generators.mdx
  website/versioned_docs/version-0.29.0/pipelines/pipelines-getting-started.mdx
  website/versioned_docs/version-0.29.0/pipelines/pipelines-intro.mdx
  website/versioned_docs/version-0.29.0/pipelines/pipelines-templates.mdx
  website/versioned_docs/version-0.29.0/pipelines/promoting-applications.mdx
  website/versioned_sidebars/version-0.29.0-sidebars.json
Labels: documentation, user-guide

#4042 Add templates to explorer supported kinds docs
  website/README.md
  website/docs/explorer/configuration.mdx
Labels: documentation

#4044 Pin GitHub Actions versions
  .github/workflows/chart.yaml
  .github/workflows/docs.yaml
  .github/workflows/nightly.yaml
  .github/workflows/ossf.yaml
  .github/workflows/pr.yaml
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/upgrade-flux.yaml
Labels: ci
