Repository weaveworks/weave-gitops, pull requests merged in 2023-01, with the labels that each got.

#3211 Fix return of false on images getter
  ui/lib/objects.ts
Labels: ui

#3213 Remove Pendo init from the Signin page
  ui/App.tsx
  ui/pages/SignIn.tsx
Labels: bug

#3212 Fix brew hanging
  .goreleaser.brew.yml
  cmd/gitops/config/options.go
  cmd/gitops/root/cmd.go
Labels: bug

#3227 Fix typo in Workspace docs
  website/docs/workspaces/view-workspaces.mdx
  website/versioned_docs/version-0.13.0/workspaces/view-workspaces.mdx
Labels: documentation, exclude from release notes

#3224 Fix irrelevant error messages about log upload during shutdown for gitops run
  cmd/gitops/beta/run/cmd.go
Labels: enhancement, gitops-run

#3228 fix npm timeouts in docker builds
  .npmrc
  gitops-server.dockerfile
Labels: bug, ci, skip-release-notes, flake

#3234 Allow customisation of the scopes.
  cmd/gitops-server/cmd/cmd.go
  package-lock.json
  pkg/server/auth/auth_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
Labels: enhancement

#3240 update calendly links
  website/docs/feedback-and-telemetry.md
  website/versioned_docs/version-0.14.1/feedback-and-telemetry.md
Labels: documentation, exclude from release notes

#3006 docs to install weave gitops enterprise airgap / offline mode
  website/docs/installation/index.mdx
  website/docs/installation/weave-gitops-enterprise/_category_.json
  website/docs/installation/weave-gitops-enterprise/airgap.mdx
  website/docs/installation/weave-gitops-enterprise/index.mdx
Labels: documentation

#3250 add tests for SetupBucketSourceAndKS
  .gitignore
  pkg/run/watch/setup_bucket_source.go
  pkg/run/watch/setup_dev_ks_test.go
  pkg/run/watch/watch_suite_test.go
  pkg/testutils/testutils.go
Labels: bug, severity/medium, team/denim, gitops-run

#2667 refresh OIDC tokens after expiry
  cmd/gitops-server/cmd/cmd.go
  core/clustersmngr/factory_caches.go
  pkg/server/auth/auth.go
  pkg/server/auth/auth_test.go
  pkg/server/auth/server.go
  pkg/server/auth/server_test.go
Labels: exclude from release notes

#3187 add explicit linter configuration; disable wsl
  .golangci.yaml
Labels: exclude from release notes, ci, team/denim

#3251 Loop over namespaces when listing reconciled objects
  core/server/events_test.go
  core/server/fluxruntime.go
  core/server/fluxruntime_test.go
  core/server/suite_test.go
  core/server/suspend_test.go
  core/server/sync_test.go
  core/server/version_test.go
Labels: bug, ui

#3262 clean up Docker targets in Makefile
  Makefile
Labels: exclude from release notes, ci

#3287 update year in footer to the current year
  ui/components/Footer.tsx
  ui/components/__tests__/__snapshots__/Footer.test.tsx.snap
  ui/components/__tests__/__snapshots__/Page.test.tsx.snap
Labels: team/sunglow

#3258 Init image automation
  api/core/types.proto
  pkg/api/core/types.pb.go
  ui/App.tsx
  ui/components/Breadcrumbs.tsx
  ui/components/ImageAutomation/ImageAutomation.tsx
  ui/components/ImageAutomation/ImageAutomationDetails.tsx
  ui/components/ImageAutomation/SyncActions.tsx
  ui/components/ImageAutomation/repositories/ImageAutomationRepoDetails.tsx
  ui/components/ImageAutomation/repositories/ImagePolicy.tsx
  ui/components/ImageAutomation/repositories/ImageRepositoriesTable.tsx
  ui/components/ImageAutomation/updates/ImageAutomationUpdatesDetails.tsx
  ui/components/ImageAutomation/updates/ImageAutomationUpdatesTable.tsx
  ui/components/Layout.tsx
  ui/components/Page.tsx
  ui/components/SubRouterTabs.tsx
  ui/hooks/imageautomation.ts
  ui/hooks/objects.ts
  ui/lib/api/core/types.pb.ts
  ui/lib/nav.ts
  ui/lib/objects.ts
  ui/lib/types.ts
  ui/pages/v2/ImageAutomationPage.tsx
Labels: team/sunglow

#3293 Display policy info
  ui/components/ImageAutomation/repositories/ImagePolicy.tsx
Labels: enhancement, team/sunglow

#3295 Set up a new bucket for gitops run logs
  cmd/gitops/beta/run/cmd.go
  core/server/session_logs.go
  core/server/session_logs_int_test.go
  pkg/logger/s3_log_writer.go
Labels: gitops-run

#3252 Update gitrepo selection in cluster management
  website/docs/cluster-management/gitrepo-selection.mdx
  website/versioned_docs/version-0.15.0/cluster-management/gitrepo-selection.mdx
Labels: documentation

#3296 Release docs for WGE v.0.15.0
  website/docs/releases.mdx
  website/versioned_docs/version-0.15.0/releases.mdx
Labels: documentation

#3307 Sort port forward shortcuts
  pkg/run/watch/forward_port.go
Labels: enhancement, gitops-run, mvp

#3310 Minor updates to user docs
  doc/development-process.md
  website/README.md
  website/docs/releases.mdx
  website/docusaurus.config.js
  website/versioned_docs/version-0.15.0/releases.mdx
Labels: documentation

#3314 Return timestamp, source, level and message in GitOps Run log endpoint
  api/core/core.proto
  api/core/core.swagger.json
  core/server/session_logs.go
  core/server/session_logs_int_test.go
  pkg/api/core/core.pb.go
  pkg/logger/s3_log_writer.go
  ui/lib/api/core/core.pb.ts
Labels: ui, gitops-run, mvp

#3311 Fix spacing between graph nodes and lines
  ui/components/DagGraph.tsx
Labels: ui

#3073 Move GitAuth to EE
  api/applications/applications.proto
  api/applications/applications.swagger.json
  cmd/gitops-server/cmd/cmd.go
  pkg/api/applications/applications.pb.go
  pkg/api/applications/applications.pb.gw.go
  pkg/api/applications/applications_grpc.pb.go
  pkg/server/handler.go
  pkg/server/server.go
  pkg/server/server_suite_test.go
  pkg/server/server_test.go
  ui/components/AddGitRepoForm.tsx
  ui/components/AuthAlert.tsx
  ui/components/GithubAuthButton.tsx
  ui/components/GithubDeviceAuthModal.tsx
  ui/components/GitlabAuthButton.tsx
  ui/components/RepoInputWithAuth.tsx
  ui/components/__tests__/GithubAuthButton.test.tsx
  ui/components/__tests__/GithubDeviceAuthModal.test.tsx
  ui/components/__tests__/RepoInputWithAuth.test.tsx
  ui/components/__tests__/__snapshots__/GithubDeviceAuthModal.test.tsx.snap
  ui/contexts/AppContext.tsx
  ui/contexts/CallbackStateContext.tsx
  ui/hooks/__tests__/auth.test.tsx
  ui/hooks/applications.ts
  ui/hooks/common.ts
  ui/hooks/gitprovider.ts
  ui/index.ts
  ui/lib/__tests__/utils.test.ts
  ui/lib/api/applications/applications.pb.ts
  ui/lib/storage.ts
  ui/lib/test-utils.tsx
  ui/lib/types.ts
  ui/lib/utils.ts
  ui/pages/OAuthCallback.tsx
Labels: exclude from release notes

#3327 Add gitops run command as an alias to gitops beta run
  cmd/gitops/root/cmd.go
Labels: gitops-run, mvp

#3333 fix flux namespace discovery in session_logs endpoint
  core/server/session_logs.go
Labels: bug
